# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracerpki.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tracerpki.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftracerpki.proto\x12\ttracerpki\"S\n\x10TraceRPKIRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12!\n\x06\x66\x61mily\x18\x03 \x01(\x0e\x32\x11.tracerpki.Family\"1\n\x11TraceRPKIResponse\x12\x1c\n\x04hops\x18\x01 \x03(\x0b\x32\x0e.tracerpki.hop\"r\n\x03hop\x12\x0b\n\x03hop\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0b\n\x03rtt\x18\x03 \x01(\r\x12\x0c\n\x04rdns\x18\x04 \x01(\t\x12\x11\n\tas_number\x18\x05 \x01(\r\x12\x0f\n\x07\x61s_name\x18\x06 \x01(\t\x12\x13\n\x0brpki_status\x18\x07 \x01(\t*\x1c\n\x06\x46\x61mily\x12\x08\n\x04IPv6\x10\x00\x12\x08\n\x04IPv4\x10\x01\x32V\n\tTraceRPKI\x12I\n\x0cGetTraceRPKI\x12\x1b.tracerpki.TraceRPKIRequest\x1a\x1c.tracerpki.TraceRPKIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracerpki_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAMILY']._serialized_start=282
  _globals['_FAMILY']._serialized_end=310
  _globals['_TRACERPKIREQUEST']._serialized_start=30
  _globals['_TRACERPKIREQUEST']._serialized_end=113
  _globals['_TRACERPKIRESPONSE']._serialized_start=115
  _globals['_TRACERPKIRESPONSE']._serialized_end=164
  _globals['_HOP']._serialized_start=166
  _globals['_HOP']._serialized_end=280
  _globals['_TRACERPKI']._serialized_start=312
  _globals['_TRACERPKI']._serialized_end=398
# @@protoc_insertion_point(module_scope)
