// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tracerpki.proto

package tracerpki

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Family int32

const (
	Family_IPv6 Family = 0
	Family_IPv4 Family = 1
)

var Family_name = map[int32]string{
	0: "IPv6",
	1: "IPv4",
}

var Family_value = map[string]int32{
	"IPv6": 0,
	"IPv4": 1,
}

func (x Family) String() string {
	return proto.EnumName(Family_name, int32(x))
}

func (Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c8cfb22cc4deb4e, []int{0}
}

type TraceRPKIRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Locale               string   `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Family               Family   `protobuf:"varint,3,opt,name=family,proto3,enum=tracerpki.Family" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceRPKIRequest) Reset()         { *m = TraceRPKIRequest{} }
func (m *TraceRPKIRequest) String() string { return proto.CompactTextString(m) }
func (*TraceRPKIRequest) ProtoMessage()    {}
func (*TraceRPKIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8cfb22cc4deb4e, []int{0}
}

func (m *TraceRPKIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceRPKIRequest.Unmarshal(m, b)
}
func (m *TraceRPKIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceRPKIRequest.Marshal(b, m, deterministic)
}
func (m *TraceRPKIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceRPKIRequest.Merge(m, src)
}
func (m *TraceRPKIRequest) XXX_Size() int {
	return xxx_messageInfo_TraceRPKIRequest.Size(m)
}
func (m *TraceRPKIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceRPKIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraceRPKIRequest proto.InternalMessageInfo

func (m *TraceRPKIRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TraceRPKIRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *TraceRPKIRequest) GetFamily() Family {
	if m != nil {
		return m.Family
	}
	return Family_IPv6
}

type TraceRPKIResponse struct {
	Hops                 []*Hop   `protobuf:"bytes,1,rep,name=hops,proto3" json:"hops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceRPKIResponse) Reset()         { *m = TraceRPKIResponse{} }
func (m *TraceRPKIResponse) String() string { return proto.CompactTextString(m) }
func (*TraceRPKIResponse) ProtoMessage()    {}
func (*TraceRPKIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8cfb22cc4deb4e, []int{1}
}

func (m *TraceRPKIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceRPKIResponse.Unmarshal(m, b)
}
func (m *TraceRPKIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceRPKIResponse.Marshal(b, m, deterministic)
}
func (m *TraceRPKIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceRPKIResponse.Merge(m, src)
}
func (m *TraceRPKIResponse) XXX_Size() int {
	return xxx_messageInfo_TraceRPKIResponse.Size(m)
}
func (m *TraceRPKIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceRPKIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TraceRPKIResponse proto.InternalMessageInfo

func (m *TraceRPKIResponse) GetHops() []*Hop {
	if m != nil {
		return m.Hops
	}
	return nil
}

type Hop struct {
	Hop                  uint32   `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Rtt                  uint32   `protobuf:"varint,3,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Rdns                 string   `protobuf:"bytes,4,opt,name=rdns,proto3" json:"rdns,omitempty"`
	AsNumber             uint32   `protobuf:"varint,5,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	AsName               string   `protobuf:"bytes,6,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	RpkiStatus           string   `protobuf:"bytes,7,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hop) Reset()         { *m = Hop{} }
func (m *Hop) String() string { return proto.CompactTextString(m) }
func (*Hop) ProtoMessage()    {}
func (*Hop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8cfb22cc4deb4e, []int{2}
}

func (m *Hop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hop.Unmarshal(m, b)
}
func (m *Hop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hop.Marshal(b, m, deterministic)
}
func (m *Hop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hop.Merge(m, src)
}
func (m *Hop) XXX_Size() int {
	return xxx_messageInfo_Hop.Size(m)
}
func (m *Hop) XXX_DiscardUnknown() {
	xxx_messageInfo_Hop.DiscardUnknown(m)
}

var xxx_messageInfo_Hop proto.InternalMessageInfo

func (m *Hop) GetHop() uint32 {
	if m != nil {
		return m.Hop
	}
	return 0
}

func (m *Hop) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Hop) GetRtt() uint32 {
	if m != nil {
		return m.Rtt
	}
	return 0
}

func (m *Hop) GetRdns() string {
	if m != nil {
		return m.Rdns
	}
	return ""
}

func (m *Hop) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

func (m *Hop) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *Hop) GetRpkiStatus() string {
	if m != nil {
		return m.RpkiStatus
	}
	return ""
}

func init() {
	proto.RegisterEnum("tracerpki.Family", Family_name, Family_value)
	proto.RegisterType((*TraceRPKIRequest)(nil), "tracerpki.TraceRPKIRequest")
	proto.RegisterType((*TraceRPKIResponse)(nil), "tracerpki.TraceRPKIResponse")
	proto.RegisterType((*Hop)(nil), "tracerpki.hop")
}

func init() {
	proto.RegisterFile("tracerpki.proto", fileDescriptor_0c8cfb22cc4deb4e)
}

var fileDescriptor_0c8cfb22cc4deb4e = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0xb6, 0x80, 0x0b, 0x3b, 0x08, 0x2e, 0x73, 0xd0, 0x46, 0x48, 0x24, 0x7b, 0x42, 0x0f, 0x1c,
	0xd0, 0xe8, 0x1b, 0x68, 0x88, 0x09, 0x21, 0xd5, 0x78, 0x25, 0x05, 0x6b, 0xd8, 0xc8, 0xd2, 0xda,
	0x16, 0x13, 0xdf, 0xc7, 0x07, 0x35, 0x9d, 0xdd, 0xc0, 0xc6, 0x78, 0xda, 0xef, 0x67, 0x36, 0xf3,
	0x7d, 0x1d, 0x38, 0xf5, 0x56, 0xae, 0x94, 0x35, 0x1f, 0xd9, 0xd8, 0x58, 0xed, 0x35, 0xc6, 0x7b,
	0x21, 0xcd, 0x20, 0x79, 0x09, 0x44, 0xcc, 0x9f, 0xa6, 0x42, 0x7d, 0xee, 0x94, 0xf3, 0x88, 0xd0,
	0x58, 0x6b, 0xe7, 0x39, 0x1b, 0xb2, 0x51, 0x2c, 0x08, 0xe3, 0x19, 0x44, 0x1b, 0xbd, 0x92, 0x1b,
	0xc5, 0x6b, 0xa4, 0x96, 0x0c, 0xaf, 0x20, 0x7a, 0x97, 0x79, 0xb6, 0xf9, 0xe6, 0xf5, 0x21, 0x1b,
	0x75, 0x27, 0xbd, 0xf1, 0x61, 0xd9, 0x03, 0x19, 0xa2, 0x1c, 0x48, 0xef, 0xa1, 0x57, 0x59, 0xe5,
	0x8c, 0xde, 0x3a, 0x85, 0x69, 0xd8, 0x65, 0x1c, 0x67, 0xc3, 0xfa, 0xa8, 0x3d, 0xe9, 0x56, 0xfe,
	0x5e, 0x6b, 0x23, 0xc8, 0x4b, 0x7f, 0x18, 0xd4, 0xd7, 0xda, 0x60, 0x42, 0x1f, 0x8a, 0xd5, 0x11,
	0xa4, 0x74, 0xa1, 0x96, 0x99, 0x32, 0x51, 0x2d, 0xa3, 0x09, 0xeb, 0x3d, 0x45, 0xe9, 0x88, 0x00,
	0x43, 0x17, 0xfb, 0xb6, 0x75, 0xbc, 0x51, 0x74, 0x09, 0x18, 0xfb, 0x10, 0x4b, 0xb7, 0xd8, 0xee,
	0xf2, 0xa5, 0xb2, 0xfc, 0x98, 0x66, 0x5b, 0xd2, 0xcd, 0x88, 0xe3, 0x39, 0x34, 0x83, 0x29, 0x73,
	0xc5, 0xa3, 0xa2, 0xa9, 0x74, 0x33, 0x99, 0x2b, 0xbc, 0x84, 0x76, 0xc8, 0xb5, 0x70, 0x5e, 0xfa,
	0x9d, 0xe3, 0x4d, 0x32, 0x21, 0x48, 0xcf, 0xa4, 0x5c, 0x0f, 0x20, 0x2a, 0x1a, 0x63, 0x0b, 0x1a,
	0xd3, 0xf9, 0xd7, 0x5d, 0x72, 0x54, 0xa2, 0xdb, 0x84, 0x4d, 0x5e, 0x21, 0xde, 0xb7, 0xc7, 0x29,
	0x9c, 0x3c, 0x2a, 0x7f, 0xe0, 0xfd, 0x4a, 0xef, 0xbf, 0xe7, 0xb8, 0x18, 0xfc, 0x6f, 0x16, 0x0f,
	0xb8, 0x8c, 0xe8, 0xa4, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0xcc, 0x66, 0x2e, 0xe5,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TraceRPKIClient is the client API for TraceRPKI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraceRPKIClient interface {
	GetTraceRPKI(ctx context.Context, in *TraceRPKIRequest, opts ...grpc.CallOption) (*TraceRPKIResponse, error)
}

type traceRPKIClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceRPKIClient(cc grpc.ClientConnInterface) TraceRPKIClient {
	return &traceRPKIClient{cc}
}

func (c *traceRPKIClient) GetTraceRPKI(ctx context.Context, in *TraceRPKIRequest, opts ...grpc.CallOption) (*TraceRPKIResponse, error) {
	out := new(TraceRPKIResponse)
	err := c.cc.Invoke(ctx, "/tracerpki.TraceRPKI/GetTraceRPKI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceRPKIServer is the server API for TraceRPKI service.
type TraceRPKIServer interface {
	GetTraceRPKI(context.Context, *TraceRPKIRequest) (*TraceRPKIResponse, error)
}

// UnimplementedTraceRPKIServer can be embedded to have forward compatible implementations.
type UnimplementedTraceRPKIServer struct {
}

func (*UnimplementedTraceRPKIServer) GetTraceRPKI(ctx context.Context, req *TraceRPKIRequest) (*TraceRPKIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraceRPKI not implemented")
}

func RegisterTraceRPKIServer(s *grpc.Server, srv TraceRPKIServer) {
	s.RegisterService(&_TraceRPKI_serviceDesc, srv)
}

func _TraceRPKI_GetTraceRPKI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRPKIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceRPKIServer).GetTraceRPKI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracerpki.TraceRPKI/GetTraceRPKI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceRPKIServer).GetTraceRPKI(ctx, req.(*TraceRPKIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TraceRPKI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tracerpki.TraceRPKI",
	HandlerType: (*TraceRPKIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraceRPKI",
			Handler:    _TraceRPKI_GetTraceRPKI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracerpki.proto",
}
