# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glass_pb2 as glass__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in glass_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class looking_glassStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.origin = channel.unary_unary(
                '/glass.looking_glass/origin',
                request_serializer=glass__pb2.origin_request.SerializeToString,
                response_deserializer=glass__pb2.origin_response.FromString,
                _registered_method=True)
        self.aspath = channel.unary_unary(
                '/glass.looking_glass/aspath',
                request_serializer=glass__pb2.aspath_request.SerializeToString,
                response_deserializer=glass__pb2.aspath_response.FromString,
                _registered_method=True)
        self.route = channel.unary_unary(
                '/glass.looking_glass/route',
                request_serializer=glass__pb2.route_request.SerializeToString,
                response_deserializer=glass__pb2.route_response.FromString,
                _registered_method=True)
        self.asname = channel.unary_unary(
                '/glass.looking_glass/asname',
                request_serializer=glass__pb2.asname_request.SerializeToString,
                response_deserializer=glass__pb2.asname_response.FromString,
                _registered_method=True)
        self.asnames = channel.unary_unary(
                '/glass.looking_glass/asnames',
                request_serializer=glass__pb2.empty.SerializeToString,
                response_deserializer=glass__pb2.asnames_response.FromString,
                _registered_method=True)
        self.roa = channel.unary_unary(
                '/glass.looking_glass/roa',
                request_serializer=glass__pb2.roa_request.SerializeToString,
                response_deserializer=glass__pb2.roa_response.FromString,
                _registered_method=True)
        self.sourced = channel.unary_unary(
                '/glass.looking_glass/sourced',
                request_serializer=glass__pb2.source_request.SerializeToString,
                response_deserializer=glass__pb2.source_response.FromString,
                _registered_method=True)
        self.totals = channel.unary_unary(
                '/glass.looking_glass/totals',
                request_serializer=glass__pb2.empty.SerializeToString,
                response_deserializer=glass__pb2.total_response.FromString,
                _registered_method=True)
        self.total_asns = channel.unary_unary(
                '/glass.looking_glass/total_asns',
                request_serializer=glass__pb2.empty.SerializeToString,
                response_deserializer=glass__pb2.total_asns_response.FromString,
                _registered_method=True)
        self.location = channel.unary_unary(
                '/glass.looking_glass/location',
                request_serializer=glass__pb2.location_request.SerializeToString,
                response_deserializer=glass__pb2.location_response.FromString,
                _registered_method=True)
        self.invalids = channel.unary_unary(
                '/glass.looking_glass/invalids',
                request_serializer=glass__pb2.invalids_request.SerializeToString,
                response_deserializer=glass__pb2.invalid_response.FromString,
                _registered_method=True)
        self.vrps = channel.unary_unary(
                '/glass.looking_glass/vrps',
                request_serializer=glass__pb2.vrps_request.SerializeToString,
                response_deserializer=glass__pb2.vrps_response.FromString,
                _registered_method=True)
        self.origin_asname_roa = channel.unary_unary(
                '/glass.looking_glass/origin_asname_roa',
                request_serializer=glass__pb2.origin_asname_roa_request.SerializeToString,
                response_deserializer=glass__pb2.origin_asname_roa_response.FromString,
                _registered_method=True)
        self.ip_coordinates = channel.unary_unary(
                '/glass.looking_glass/ip_coordinates',
                request_serializer=glass__pb2.coordinates_request.SerializeToString,
                response_deserializer=glass__pb2.coordinates_response.FromString,
                _registered_method=True)


class looking_glassServicer(object):
    """Missing associated documentation comment in .proto file."""

    def origin(self, request, context):
        """origin will return the origin AS number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def aspath(self, request, context):
        """aspath will return the aspath.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def route(self, request, context):
        """route will return the full ip route output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asname(self, request, context):
        """asname will return the AS name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asnames(self, request, context):
        """asnames will return all as number to as names	
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def roa(self, request, context):
        """roa will return the roa status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sourced(self, request, context):
        """sourced will return all the IPv4 and IPv6 prefixes sources by an AS number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def totals(self, request, context):
        """totals will return the current IPv4 and IPv6 BGP count.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def total_asns(self, request, context):
        """Total number of ASNs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def location(self, request, context):
        """location will return the city, country, lat/long co-ordinates, and Google maps image of an airport.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def invalids(self, request, context):
        """invalids will return a list of ASNs originating invalid prefixes, plus a list of prefixes actually originated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def vrps(self, request, context):
        """vrps will return a list of all VRPs for a source AS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def origin_asname_roa(self, request, context):
        """origin_asname_roa will return the three required fields for a tracerpki hop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ip_coordinates(self, request, context):
        """ip_coordinates will attempt to return the longitude and latitude of an IP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_looking_glassServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'origin': grpc.unary_unary_rpc_method_handler(
                    servicer.origin,
                    request_deserializer=glass__pb2.origin_request.FromString,
                    response_serializer=glass__pb2.origin_response.SerializeToString,
            ),
            'aspath': grpc.unary_unary_rpc_method_handler(
                    servicer.aspath,
                    request_deserializer=glass__pb2.aspath_request.FromString,
                    response_serializer=glass__pb2.aspath_response.SerializeToString,
            ),
            'route': grpc.unary_unary_rpc_method_handler(
                    servicer.route,
                    request_deserializer=glass__pb2.route_request.FromString,
                    response_serializer=glass__pb2.route_response.SerializeToString,
            ),
            'asname': grpc.unary_unary_rpc_method_handler(
                    servicer.asname,
                    request_deserializer=glass__pb2.asname_request.FromString,
                    response_serializer=glass__pb2.asname_response.SerializeToString,
            ),
            'asnames': grpc.unary_unary_rpc_method_handler(
                    servicer.asnames,
                    request_deserializer=glass__pb2.empty.FromString,
                    response_serializer=glass__pb2.asnames_response.SerializeToString,
            ),
            'roa': grpc.unary_unary_rpc_method_handler(
                    servicer.roa,
                    request_deserializer=glass__pb2.roa_request.FromString,
                    response_serializer=glass__pb2.roa_response.SerializeToString,
            ),
            'sourced': grpc.unary_unary_rpc_method_handler(
                    servicer.sourced,
                    request_deserializer=glass__pb2.source_request.FromString,
                    response_serializer=glass__pb2.source_response.SerializeToString,
            ),
            'totals': grpc.unary_unary_rpc_method_handler(
                    servicer.totals,
                    request_deserializer=glass__pb2.empty.FromString,
                    response_serializer=glass__pb2.total_response.SerializeToString,
            ),
            'total_asns': grpc.unary_unary_rpc_method_handler(
                    servicer.total_asns,
                    request_deserializer=glass__pb2.empty.FromString,
                    response_serializer=glass__pb2.total_asns_response.SerializeToString,
            ),
            'location': grpc.unary_unary_rpc_method_handler(
                    servicer.location,
                    request_deserializer=glass__pb2.location_request.FromString,
                    response_serializer=glass__pb2.location_response.SerializeToString,
            ),
            'invalids': grpc.unary_unary_rpc_method_handler(
                    servicer.invalids,
                    request_deserializer=glass__pb2.invalids_request.FromString,
                    response_serializer=glass__pb2.invalid_response.SerializeToString,
            ),
            'vrps': grpc.unary_unary_rpc_method_handler(
                    servicer.vrps,
                    request_deserializer=glass__pb2.vrps_request.FromString,
                    response_serializer=glass__pb2.vrps_response.SerializeToString,
            ),
            'origin_asname_roa': grpc.unary_unary_rpc_method_handler(
                    servicer.origin_asname_roa,
                    request_deserializer=glass__pb2.origin_asname_roa_request.FromString,
                    response_serializer=glass__pb2.origin_asname_roa_response.SerializeToString,
            ),
            'ip_coordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.ip_coordinates,
                    request_deserializer=glass__pb2.coordinates_request.FromString,
                    response_serializer=glass__pb2.coordinates_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glass.looking_glass', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glass.looking_glass', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class looking_glass(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def origin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/origin',
            glass__pb2.origin_request.SerializeToString,
            glass__pb2.origin_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def aspath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/aspath',
            glass__pb2.aspath_request.SerializeToString,
            glass__pb2.aspath_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/route',
            glass__pb2.route_request.SerializeToString,
            glass__pb2.route_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/asname',
            glass__pb2.asname_request.SerializeToString,
            glass__pb2.asname_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asnames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/asnames',
            glass__pb2.empty.SerializeToString,
            glass__pb2.asnames_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def roa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/roa',
            glass__pb2.roa_request.SerializeToString,
            glass__pb2.roa_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sourced(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/sourced',
            glass__pb2.source_request.SerializeToString,
            glass__pb2.source_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def totals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/totals',
            glass__pb2.empty.SerializeToString,
            glass__pb2.total_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def total_asns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/total_asns',
            glass__pb2.empty.SerializeToString,
            glass__pb2.total_asns_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def location(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/location',
            glass__pb2.location_request.SerializeToString,
            glass__pb2.location_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def invalids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/invalids',
            glass__pb2.invalids_request.SerializeToString,
            glass__pb2.invalid_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def vrps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/vrps',
            glass__pb2.vrps_request.SerializeToString,
            glass__pb2.vrps_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def origin_asname_roa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/origin_asname_roa',
            glass__pb2.origin_asname_roa_request.SerializeToString,
            glass__pb2.origin_asname_roa_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ip_coordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glass.looking_glass/ip_coordinates',
            glass__pb2.coordinates_request.SerializeToString,
            glass__pb2.coordinates_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
