// Code generated by protoc-gen-go. DO NOT EDIT.
// source: glass.proto

package glass

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoaResponse_ROAStatus int32

const (
	RoaResponse_UNKNOWN RoaResponse_ROAStatus = 0
	RoaResponse_VALID   RoaResponse_ROAStatus = 1
	RoaResponse_INVALID RoaResponse_ROAStatus = 2
)

var RoaResponse_ROAStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "VALID",
	2: "INVALID",
}

var RoaResponse_ROAStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"VALID":   1,
	"INVALID": 2,
}

func (x RoaResponse_ROAStatus) String() string {
	return proto.EnumName(RoaResponse_ROAStatus_name, int32(x))
}

func (RoaResponse_ROAStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{27, 0}
}

type IpAddress struct {
	// An address is made up of a string prefix and a int mask. Both IPv4 and IPv6.
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mask                 uint32   `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpAddress) Reset()         { *m = IpAddress{} }
func (m *IpAddress) String() string { return proto.CompactTextString(m) }
func (*IpAddress) ProtoMessage()    {}
func (*IpAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{0}
}

func (m *IpAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpAddress.Unmarshal(m, b)
}
func (m *IpAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpAddress.Marshal(b, m, deterministic)
}
func (m *IpAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpAddress.Merge(m, src)
}
func (m *IpAddress) XXX_Size() int {
	return xxx_messageInfo_IpAddress.Size(m)
}
func (m *IpAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_IpAddress.DiscardUnknown(m)
}

var xxx_messageInfo_IpAddress proto.InternalMessageInfo

func (m *IpAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IpAddress) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

type OriginRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OriginRequest) Reset()         { *m = OriginRequest{} }
func (m *OriginRequest) String() string { return proto.CompactTextString(m) }
func (*OriginRequest) ProtoMessage()    {}
func (*OriginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{1}
}

func (m *OriginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginRequest.Unmarshal(m, b)
}
func (m *OriginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginRequest.Marshal(b, m, deterministic)
}
func (m *OriginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginRequest.Merge(m, src)
}
func (m *OriginRequest) XXX_Size() int {
	return xxx_messageInfo_OriginRequest.Size(m)
}
func (m *OriginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginRequest proto.InternalMessageInfo

func (m *OriginRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type CoordinatesRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CoordinatesRequest) Reset()         { *m = CoordinatesRequest{} }
func (m *CoordinatesRequest) String() string { return proto.CompactTextString(m) }
func (*CoordinatesRequest) ProtoMessage()    {}
func (*CoordinatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{2}
}

func (m *CoordinatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinatesRequest.Unmarshal(m, b)
}
func (m *CoordinatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinatesRequest.Marshal(b, m, deterministic)
}
func (m *CoordinatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatesRequest.Merge(m, src)
}
func (m *CoordinatesRequest) XXX_Size() int {
	return xxx_messageInfo_CoordinatesRequest.Size(m)
}
func (m *CoordinatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatesRequest proto.InternalMessageInfo

func (m *CoordinatesRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type CoordinatesResponse struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Lat                  string   `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 string   `protobuf:"bytes,4,opt,name=long,proto3" json:"long,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoordinatesResponse) Reset()         { *m = CoordinatesResponse{} }
func (m *CoordinatesResponse) String() string { return proto.CompactTextString(m) }
func (*CoordinatesResponse) ProtoMessage()    {}
func (*CoordinatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{3}
}

func (m *CoordinatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinatesResponse.Unmarshal(m, b)
}
func (m *CoordinatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinatesResponse.Marshal(b, m, deterministic)
}
func (m *CoordinatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatesResponse.Merge(m, src)
}
func (m *CoordinatesResponse) XXX_Size() int {
	return xxx_messageInfo_CoordinatesResponse.Size(m)
}
func (m *CoordinatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatesResponse proto.InternalMessageInfo

func (m *CoordinatesResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CoordinatesResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CoordinatesResponse) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *CoordinatesResponse) GetLong() string {
	if m != nil {
		return m.Long
	}
	return ""
}

func (m *CoordinatesResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type OriginResponse struct {
	// origin_response shows the current origin ASN for active route.
	OriginAsn            uint32   `protobuf:"varint,1,opt,name=origin_asn,json=originAsn,proto3" json:"origin_asn,omitempty"`
	Exists               bool     `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	CacheTime            uint64   `protobuf:"varint,3,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginResponse) Reset()         { *m = OriginResponse{} }
func (m *OriginResponse) String() string { return proto.CompactTextString(m) }
func (*OriginResponse) ProtoMessage()    {}
func (*OriginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{4}
}

func (m *OriginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginResponse.Unmarshal(m, b)
}
func (m *OriginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginResponse.Marshal(b, m, deterministic)
}
func (m *OriginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginResponse.Merge(m, src)
}
func (m *OriginResponse) XXX_Size() int {
	return xxx_messageInfo_OriginResponse.Size(m)
}
func (m *OriginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginResponse proto.InternalMessageInfo

func (m *OriginResponse) GetOriginAsn() uint32 {
	if m != nil {
		return m.OriginAsn
	}
	return 0
}

func (m *OriginResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *OriginResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type OriginAsnameRoaRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OriginAsnameRoaRequest) Reset()         { *m = OriginAsnameRoaRequest{} }
func (m *OriginAsnameRoaRequest) String() string { return proto.CompactTextString(m) }
func (*OriginAsnameRoaRequest) ProtoMessage()    {}
func (*OriginAsnameRoaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{5}
}

func (m *OriginAsnameRoaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginAsnameRoaRequest.Unmarshal(m, b)
}
func (m *OriginAsnameRoaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginAsnameRoaRequest.Marshal(b, m, deterministic)
}
func (m *OriginAsnameRoaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginAsnameRoaRequest.Merge(m, src)
}
func (m *OriginAsnameRoaRequest) XXX_Size() int {
	return xxx_messageInfo_OriginAsnameRoaRequest.Size(m)
}
func (m *OriginAsnameRoaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginAsnameRoaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginAsnameRoaRequest proto.InternalMessageInfo

func (m *OriginAsnameRoaRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type OriginAsnameRoaResponse struct {
	Origin               *OriginResponse `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Asname               *AsnameResponse `protobuf:"bytes,2,opt,name=asname,proto3" json:"asname,omitempty"`
	Roa                  *RoaResponse    `protobuf:"bytes,3,opt,name=roa,proto3" json:"roa,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OriginAsnameRoaResponse) Reset()         { *m = OriginAsnameRoaResponse{} }
func (m *OriginAsnameRoaResponse) String() string { return proto.CompactTextString(m) }
func (*OriginAsnameRoaResponse) ProtoMessage()    {}
func (*OriginAsnameRoaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{6}
}

func (m *OriginAsnameRoaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginAsnameRoaResponse.Unmarshal(m, b)
}
func (m *OriginAsnameRoaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginAsnameRoaResponse.Marshal(b, m, deterministic)
}
func (m *OriginAsnameRoaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginAsnameRoaResponse.Merge(m, src)
}
func (m *OriginAsnameRoaResponse) XXX_Size() int {
	return xxx_messageInfo_OriginAsnameRoaResponse.Size(m)
}
func (m *OriginAsnameRoaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginAsnameRoaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginAsnameRoaResponse proto.InternalMessageInfo

func (m *OriginAsnameRoaResponse) GetOrigin() *OriginResponse {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *OriginAsnameRoaResponse) GetAsname() *AsnameResponse {
	if m != nil {
		return m.Asname
	}
	return nil
}

func (m *OriginAsnameRoaResponse) GetRoa() *RoaResponse {
	if m != nil {
		return m.Roa
	}
	return nil
}

type SourceRequest struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{7}
}

func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (m *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(m, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

type VrpsRequest struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrpsRequest) Reset()         { *m = VrpsRequest{} }
func (m *VrpsRequest) String() string { return proto.CompactTextString(m) }
func (*VrpsRequest) ProtoMessage()    {}
func (*VrpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{8}
}

func (m *VrpsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrpsRequest.Unmarshal(m, b)
}
func (m *VrpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrpsRequest.Marshal(b, m, deterministic)
}
func (m *VrpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrpsRequest.Merge(m, src)
}
func (m *VrpsRequest) XXX_Size() int {
	return xxx_messageInfo_VrpsRequest.Size(m)
}
func (m *VrpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VrpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VrpsRequest proto.InternalMessageInfo

func (m *VrpsRequest) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

type SourceResponse struct {
	IpAddress            []*IpAddress `protobuf:"bytes,1,rep,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Exists               bool         `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	V4Count              uint32       `protobuf:"varint,3,opt,name=v4count,proto3" json:"v4count,omitempty"`
	V6Count              uint32       `protobuf:"varint,4,opt,name=v6count,proto3" json:"v6count,omitempty"`
	CacheTime            uint64       `protobuf:"varint,5,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SourceResponse) Reset()         { *m = SourceResponse{} }
func (m *SourceResponse) String() string { return proto.CompactTextString(m) }
func (*SourceResponse) ProtoMessage()    {}
func (*SourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{9}
}

func (m *SourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceResponse.Unmarshal(m, b)
}
func (m *SourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceResponse.Marshal(b, m, deterministic)
}
func (m *SourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceResponse.Merge(m, src)
}
func (m *SourceResponse) XXX_Size() int {
	return xxx_messageInfo_SourceResponse.Size(m)
}
func (m *SourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SourceResponse proto.InternalMessageInfo

func (m *SourceResponse) GetIpAddress() []*IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *SourceResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *SourceResponse) GetV4Count() uint32 {
	if m != nil {
		return m.V4Count
	}
	return 0
}

func (m *SourceResponse) GetV6Count() uint32 {
	if m != nil {
		return m.V6Count
	}
	return 0
}

func (m *SourceResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{10}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type TotalResponse struct {
	Active_4             uint32   `protobuf:"varint,2,opt,name=active_4,json=active4,proto3" json:"active_4,omitempty"`
	Active_6             uint32   `protobuf:"varint,4,opt,name=active_6,json=active6,proto3" json:"active_6,omitempty"`
	Time                 uint64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalResponse) Reset()         { *m = TotalResponse{} }
func (m *TotalResponse) String() string { return proto.CompactTextString(m) }
func (*TotalResponse) ProtoMessage()    {}
func (*TotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{11}
}

func (m *TotalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalResponse.Unmarshal(m, b)
}
func (m *TotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalResponse.Marshal(b, m, deterministic)
}
func (m *TotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalResponse.Merge(m, src)
}
func (m *TotalResponse) XXX_Size() int {
	return xxx_messageInfo_TotalResponse.Size(m)
}
func (m *TotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalResponse proto.InternalMessageInfo

func (m *TotalResponse) GetActive_4() uint32 {
	if m != nil {
		return m.Active_4
	}
	return 0
}

func (m *TotalResponse) GetActive_6() uint32 {
	if m != nil {
		return m.Active_6
	}
	return 0
}

func (m *TotalResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type AspathRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AspathRequest) Reset()         { *m = AspathRequest{} }
func (m *AspathRequest) String() string { return proto.CompactTextString(m) }
func (*AspathRequest) ProtoMessage()    {}
func (*AspathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{12}
}

func (m *AspathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AspathRequest.Unmarshal(m, b)
}
func (m *AspathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AspathRequest.Marshal(b, m, deterministic)
}
func (m *AspathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AspathRequest.Merge(m, src)
}
func (m *AspathRequest) XXX_Size() int {
	return xxx_messageInfo_AspathRequest.Size(m)
}
func (m *AspathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AspathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AspathRequest proto.InternalMessageInfo

func (m *AspathRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type AspathResponse struct {
	// aspath_response shows the current aspath for the active route.
	Asn                  []*Asn   `protobuf:"bytes,1,rep,name=asn,proto3" json:"asn,omitempty"`
	Set                  []*Asn   `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`
	Exists               bool     `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	CacheTime            uint64   `protobuf:"varint,4,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AspathResponse) Reset()         { *m = AspathResponse{} }
func (m *AspathResponse) String() string { return proto.CompactTextString(m) }
func (*AspathResponse) ProtoMessage()    {}
func (*AspathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{13}
}

func (m *AspathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AspathResponse.Unmarshal(m, b)
}
func (m *AspathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AspathResponse.Marshal(b, m, deterministic)
}
func (m *AspathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AspathResponse.Merge(m, src)
}
func (m *AspathResponse) XXX_Size() int {
	return xxx_messageInfo_AspathResponse.Size(m)
}
func (m *AspathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AspathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AspathResponse proto.InternalMessageInfo

func (m *AspathResponse) GetAsn() []*Asn {
	if m != nil {
		return m.Asn
	}
	return nil
}

func (m *AspathResponse) GetSet() []*Asn {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *AspathResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *AspathResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type Asn struct {
	Asplain              uint32   `protobuf:"varint,1,opt,name=asplain,proto3" json:"asplain,omitempty"`
	Asdot                string   `protobuf:"bytes,2,opt,name=asdot,proto3" json:"asdot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asn) Reset()         { *m = Asn{} }
func (m *Asn) String() string { return proto.CompactTextString(m) }
func (*Asn) ProtoMessage()    {}
func (*Asn) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{14}
}

func (m *Asn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asn.Unmarshal(m, b)
}
func (m *Asn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asn.Marshal(b, m, deterministic)
}
func (m *Asn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asn.Merge(m, src)
}
func (m *Asn) XXX_Size() int {
	return xxx_messageInfo_Asn.Size(m)
}
func (m *Asn) XXX_DiscardUnknown() {
	xxx_messageInfo_Asn.DiscardUnknown(m)
}

var xxx_messageInfo_Asn proto.InternalMessageInfo

func (m *Asn) GetAsplain() uint32 {
	if m != nil {
		return m.Asplain
	}
	return 0
}

func (m *Asn) GetAsdot() string {
	if m != nil {
		return m.Asdot
	}
	return ""
}

type RouteRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RouteRequest) Reset()         { *m = RouteRequest{} }
func (m *RouteRequest) String() string { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()    {}
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{15}
}

func (m *RouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteRequest.Unmarshal(m, b)
}
func (m *RouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteRequest.Marshal(b, m, deterministic)
}
func (m *RouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteRequest.Merge(m, src)
}
func (m *RouteRequest) XXX_Size() int {
	return xxx_messageInfo_RouteRequest.Size(m)
}
func (m *RouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteRequest proto.InternalMessageInfo

func (m *RouteRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type RouteResponse struct {
	// route_response shows the current prefix/mask for the active route.
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Exists               bool       `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	CacheTime            uint64     `protobuf:"varint,3,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RouteResponse) Reset()         { *m = RouteResponse{} }
func (m *RouteResponse) String() string { return proto.CompactTextString(m) }
func (*RouteResponse) ProtoMessage()    {}
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{16}
}

func (m *RouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteResponse.Unmarshal(m, b)
}
func (m *RouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteResponse.Marshal(b, m, deterministic)
}
func (m *RouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteResponse.Merge(m, src)
}
func (m *RouteResponse) XXX_Size() int {
	return xxx_messageInfo_RouteResponse.Size(m)
}
func (m *RouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteResponse proto.InternalMessageInfo

func (m *RouteResponse) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *RouteResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *RouteResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type AsnameRequest struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsnameRequest) Reset()         { *m = AsnameRequest{} }
func (m *AsnameRequest) String() string { return proto.CompactTextString(m) }
func (*AsnameRequest) ProtoMessage()    {}
func (*AsnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{17}
}

func (m *AsnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnameRequest.Unmarshal(m, b)
}
func (m *AsnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnameRequest.Marshal(b, m, deterministic)
}
func (m *AsnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnameRequest.Merge(m, src)
}
func (m *AsnameRequest) XXX_Size() int {
	return xxx_messageInfo_AsnameRequest.Size(m)
}
func (m *AsnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AsnameRequest proto.InternalMessageInfo

func (m *AsnameRequest) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

type AsnameResponse struct {
	// asname_response returns the string name for the passed AS number.
	AsName               string   `protobuf:"bytes,1,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Locale               string   `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsnameResponse) Reset()         { *m = AsnameResponse{} }
func (m *AsnameResponse) String() string { return proto.CompactTextString(m) }
func (*AsnameResponse) ProtoMessage()    {}
func (*AsnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{18}
}

func (m *AsnameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnameResponse.Unmarshal(m, b)
}
func (m *AsnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnameResponse.Marshal(b, m, deterministic)
}
func (m *AsnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnameResponse.Merge(m, src)
}
func (m *AsnameResponse) XXX_Size() int {
	return xxx_messageInfo_AsnameResponse.Size(m)
}
func (m *AsnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsnameResponse proto.InternalMessageInfo

func (m *AsnameResponse) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *AsnameResponse) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type AsnamesResponse struct {
	Asnumnames           []*AsnumberAsnames `protobuf:"bytes,1,rep,name=asnumnames,proto3" json:"asnumnames,omitempty"`
	CacheTime            uint64             `protobuf:"varint,2,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AsnamesResponse) Reset()         { *m = AsnamesResponse{} }
func (m *AsnamesResponse) String() string { return proto.CompactTextString(m) }
func (*AsnamesResponse) ProtoMessage()    {}
func (*AsnamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{19}
}

func (m *AsnamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnamesResponse.Unmarshal(m, b)
}
func (m *AsnamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnamesResponse.Marshal(b, m, deterministic)
}
func (m *AsnamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnamesResponse.Merge(m, src)
}
func (m *AsnamesResponse) XXX_Size() int {
	return xxx_messageInfo_AsnamesResponse.Size(m)
}
func (m *AsnamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsnamesResponse proto.InternalMessageInfo

func (m *AsnamesResponse) GetAsnumnames() []*AsnumberAsnames {
	if m != nil {
		return m.Asnumnames
	}
	return nil
}

func (m *AsnamesResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type AsnumberAsnames struct {
	AsNumber             uint32          `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	Names                *AsnameResponse `protobuf:"bytes,2,opt,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AsnumberAsnames) Reset()         { *m = AsnumberAsnames{} }
func (m *AsnumberAsnames) String() string { return proto.CompactTextString(m) }
func (*AsnumberAsnames) ProtoMessage()    {}
func (*AsnumberAsnames) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{20}
}

func (m *AsnumberAsnames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnumberAsnames.Unmarshal(m, b)
}
func (m *AsnumberAsnames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnumberAsnames.Marshal(b, m, deterministic)
}
func (m *AsnumberAsnames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnumberAsnames.Merge(m, src)
}
func (m *AsnumberAsnames) XXX_Size() int {
	return xxx_messageInfo_AsnumberAsnames.Size(m)
}
func (m *AsnumberAsnames) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnumberAsnames.DiscardUnknown(m)
}

var xxx_messageInfo_AsnumberAsnames proto.InternalMessageInfo

func (m *AsnumberAsnames) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

func (m *AsnumberAsnames) GetNames() *AsnameResponse {
	if m != nil {
		return m.Names
	}
	return nil
}

type VrpsResponse struct {
	Vrps                 []*Vrp   `protobuf:"bytes,1,rep,name=vrps,proto3" json:"vrps,omitempty"`
	CacheTime            uint64   `protobuf:"varint,2,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrpsResponse) Reset()         { *m = VrpsResponse{} }
func (m *VrpsResponse) String() string { return proto.CompactTextString(m) }
func (*VrpsResponse) ProtoMessage()    {}
func (*VrpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{21}
}

func (m *VrpsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrpsResponse.Unmarshal(m, b)
}
func (m *VrpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrpsResponse.Marshal(b, m, deterministic)
}
func (m *VrpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrpsResponse.Merge(m, src)
}
func (m *VrpsResponse) XXX_Size() int {
	return xxx_messageInfo_VrpsResponse.Size(m)
}
func (m *VrpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VrpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VrpsResponse proto.InternalMessageInfo

func (m *VrpsResponse) GetVrps() []*Vrp {
	if m != nil {
		return m.Vrps
	}
	return nil
}

func (m *VrpsResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type Vrp struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Max                  uint32     `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Vrp) Reset()         { *m = Vrp{} }
func (m *Vrp) String() string { return proto.CompactTextString(m) }
func (*Vrp) ProtoMessage()    {}
func (*Vrp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{22}
}

func (m *Vrp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vrp.Unmarshal(m, b)
}
func (m *Vrp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vrp.Marshal(b, m, deterministic)
}
func (m *Vrp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vrp.Merge(m, src)
}
func (m *Vrp) XXX_Size() int {
	return xxx_messageInfo_Vrp.Size(m)
}
func (m *Vrp) XXX_DiscardUnknown() {
	xxx_messageInfo_Vrp.DiscardUnknown(m)
}

var xxx_messageInfo_Vrp proto.InternalMessageInfo

func (m *Vrp) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *Vrp) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type TotalTransitRequest struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalTransitRequest) Reset()         { *m = TotalTransitRequest{} }
func (m *TotalTransitRequest) String() string { return proto.CompactTextString(m) }
func (*TotalTransitRequest) ProtoMessage()    {}
func (*TotalTransitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{23}
}

func (m *TotalTransitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalTransitRequest.Unmarshal(m, b)
}
func (m *TotalTransitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalTransitRequest.Marshal(b, m, deterministic)
}
func (m *TotalTransitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalTransitRequest.Merge(m, src)
}
func (m *TotalTransitRequest) XXX_Size() int {
	return xxx_messageInfo_TotalTransitRequest.Size(m)
}
func (m *TotalTransitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalTransitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalTransitRequest proto.InternalMessageInfo

func (m *TotalTransitRequest) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

type TotalTransitResponse struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalTransitResponse) Reset()         { *m = TotalTransitResponse{} }
func (m *TotalTransitResponse) String() string { return proto.CompactTextString(m) }
func (*TotalTransitResponse) ProtoMessage()    {}
func (*TotalTransitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{24}
}

func (m *TotalTransitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalTransitResponse.Unmarshal(m, b)
}
func (m *TotalTransitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalTransitResponse.Marshal(b, m, deterministic)
}
func (m *TotalTransitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalTransitResponse.Merge(m, src)
}
func (m *TotalTransitResponse) XXX_Size() int {
	return xxx_messageInfo_TotalTransitResponse.Size(m)
}
func (m *TotalTransitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalTransitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalTransitResponse proto.InternalMessageInfo

func (m *TotalTransitResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type TotalAsnsResponse struct {
	// Total ASNs sourcing IPv4
	As4 uint32 `protobuf:"varint,2,opt,name=as4,proto3" json:"as4,omitempty"`
	// Total ASNs sourcing IPv6
	As6 uint32 `protobuf:"varint,3,opt,name=as6,proto3" json:"as6,omitempty"`
	// Total ASNs sourcing either IPv4, IPv6, or both
	As10 uint32 `protobuf:"varint,4,opt,name=as10,proto3" json:"as10,omitempty"`
	// Total ASNs sourcing only IPv4
	As4Only uint32 `protobuf:"varint,5,opt,name=as4_only,json=as4Only,proto3" json:"as4_only,omitempty"`
	// Total ASNs sourcing only IPv6
	As6Only uint32 `protobuf:"varint,6,opt,name=as6_only,json=as6Only,proto3" json:"as6_only,omitempty"`
	// Total ASNs sourcing both IPv4 and IPv6
	AsBoth               uint32   `protobuf:"varint,1,opt,name=as_both,json=asBoth,proto3" json:"as_both,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalAsnsResponse) Reset()         { *m = TotalAsnsResponse{} }
func (m *TotalAsnsResponse) String() string { return proto.CompactTextString(m) }
func (*TotalAsnsResponse) ProtoMessage()    {}
func (*TotalAsnsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{25}
}

func (m *TotalAsnsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalAsnsResponse.Unmarshal(m, b)
}
func (m *TotalAsnsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalAsnsResponse.Marshal(b, m, deterministic)
}
func (m *TotalAsnsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalAsnsResponse.Merge(m, src)
}
func (m *TotalAsnsResponse) XXX_Size() int {
	return xxx_messageInfo_TotalAsnsResponse.Size(m)
}
func (m *TotalAsnsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalAsnsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalAsnsResponse proto.InternalMessageInfo

func (m *TotalAsnsResponse) GetAs4() uint32 {
	if m != nil {
		return m.As4
	}
	return 0
}

func (m *TotalAsnsResponse) GetAs6() uint32 {
	if m != nil {
		return m.As6
	}
	return 0
}

func (m *TotalAsnsResponse) GetAs10() uint32 {
	if m != nil {
		return m.As10
	}
	return 0
}

func (m *TotalAsnsResponse) GetAs4Only() uint32 {
	if m != nil {
		return m.As4Only
	}
	return 0
}

func (m *TotalAsnsResponse) GetAs6Only() uint32 {
	if m != nil {
		return m.As6Only
	}
	return 0
}

func (m *TotalAsnsResponse) GetAsBoth() uint32 {
	if m != nil {
		return m.AsBoth
	}
	return 0
}

type RoaRequest struct {
	IpAddress            *IpAddress `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoaRequest) Reset()         { *m = RoaRequest{} }
func (m *RoaRequest) String() string { return proto.CompactTextString(m) }
func (*RoaRequest) ProtoMessage()    {}
func (*RoaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{26}
}

func (m *RoaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoaRequest.Unmarshal(m, b)
}
func (m *RoaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoaRequest.Marshal(b, m, deterministic)
}
func (m *RoaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoaRequest.Merge(m, src)
}
func (m *RoaRequest) XXX_Size() int {
	return xxx_messageInfo_RoaRequest.Size(m)
}
func (m *RoaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoaRequest proto.InternalMessageInfo

func (m *RoaRequest) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type RoaResponse struct {
	IpAddress            *IpAddress            `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status               RoaResponse_ROAStatus `protobuf:"varint,2,opt,name=status,proto3,enum=glass.RoaResponse_ROAStatus" json:"status,omitempty"`
	Exists               bool                  `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	CacheTime            uint64                `protobuf:"varint,4,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoaResponse) Reset()         { *m = RoaResponse{} }
func (m *RoaResponse) String() string { return proto.CompactTextString(m) }
func (*RoaResponse) ProtoMessage()    {}
func (*RoaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{27}
}

func (m *RoaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoaResponse.Unmarshal(m, b)
}
func (m *RoaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoaResponse.Marshal(b, m, deterministic)
}
func (m *RoaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoaResponse.Merge(m, src)
}
func (m *RoaResponse) XXX_Size() int {
	return xxx_messageInfo_RoaResponse.Size(m)
}
func (m *RoaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoaResponse proto.InternalMessageInfo

func (m *RoaResponse) GetIpAddress() *IpAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *RoaResponse) GetStatus() RoaResponse_ROAStatus {
	if m != nil {
		return m.Status
	}
	return RoaResponse_UNKNOWN
}

func (m *RoaResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *RoaResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type LocationRequest struct {
	Airport              string   `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{28}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetAirport() string {
	if m != nil {
		return m.Airport
	}
	return ""
}

type LocationResponse struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Lat                  string   `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 string   `protobuf:"bytes,4,opt,name=long,proto3" json:"long,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationResponse) Reset()         { *m = LocationResponse{} }
func (m *LocationResponse) String() string { return proto.CompactTextString(m) }
func (*LocationResponse) ProtoMessage()    {}
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{29}
}

func (m *LocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationResponse.Unmarshal(m, b)
}
func (m *LocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationResponse.Marshal(b, m, deterministic)
}
func (m *LocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationResponse.Merge(m, src)
}
func (m *LocationResponse) XXX_Size() int {
	return xxx_messageInfo_LocationResponse.Size(m)
}
func (m *LocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocationResponse proto.InternalMessageInfo

func (m *LocationResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *LocationResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *LocationResponse) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *LocationResponse) GetLong() string {
	if m != nil {
		return m.Long
	}
	return ""
}

func (m *LocationResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type InvalidsRequest struct {
	Asn                  string   `protobuf:"bytes,1,opt,name=asn,proto3" json:"asn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidsRequest) Reset()         { *m = InvalidsRequest{} }
func (m *InvalidsRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidsRequest) ProtoMessage()    {}
func (*InvalidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{30}
}

func (m *InvalidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidsRequest.Unmarshal(m, b)
}
func (m *InvalidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidsRequest.Marshal(b, m, deterministic)
}
func (m *InvalidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidsRequest.Merge(m, src)
}
func (m *InvalidsRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidsRequest.Size(m)
}
func (m *InvalidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidsRequest proto.InternalMessageInfo

func (m *InvalidsRequest) GetAsn() string {
	if m != nil {
		return m.Asn
	}
	return ""
}

type InvalidResponse struct {
	Asn                  []*InvalidOriginator `protobuf:"bytes,1,rep,name=asn,proto3" json:"asn,omitempty"`
	CacheTime            uint64               `protobuf:"varint,2,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InvalidResponse) Reset()         { *m = InvalidResponse{} }
func (m *InvalidResponse) String() string { return proto.CompactTextString(m) }
func (*InvalidResponse) ProtoMessage()    {}
func (*InvalidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{31}
}

func (m *InvalidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidResponse.Unmarshal(m, b)
}
func (m *InvalidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidResponse.Marshal(b, m, deterministic)
}
func (m *InvalidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidResponse.Merge(m, src)
}
func (m *InvalidResponse) XXX_Size() int {
	return xxx_messageInfo_InvalidResponse.Size(m)
}
func (m *InvalidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidResponse proto.InternalMessageInfo

func (m *InvalidResponse) GetAsn() []*InvalidOriginator {
	if m != nil {
		return m.Asn
	}
	return nil
}

func (m *InvalidResponse) GetCacheTime() uint64 {
	if m != nil {
		return m.CacheTime
	}
	return 0
}

type InvalidOriginator struct {
	Asn                  string   `protobuf:"bytes,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Ip                   []string `protobuf:"bytes,2,rep,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidOriginator) Reset()         { *m = InvalidOriginator{} }
func (m *InvalidOriginator) String() string { return proto.CompactTextString(m) }
func (*InvalidOriginator) ProtoMessage()    {}
func (*InvalidOriginator) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec22f2a0338f3ce, []int{32}
}

func (m *InvalidOriginator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidOriginator.Unmarshal(m, b)
}
func (m *InvalidOriginator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidOriginator.Marshal(b, m, deterministic)
}
func (m *InvalidOriginator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidOriginator.Merge(m, src)
}
func (m *InvalidOriginator) XXX_Size() int {
	return xxx_messageInfo_InvalidOriginator.Size(m)
}
func (m *InvalidOriginator) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidOriginator.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidOriginator proto.InternalMessageInfo

func (m *InvalidOriginator) GetAsn() string {
	if m != nil {
		return m.Asn
	}
	return ""
}

func (m *InvalidOriginator) GetIp() []string {
	if m != nil {
		return m.Ip
	}
	return nil
}

func init() {
	proto.RegisterEnum("glass.RoaResponse_ROAStatus", RoaResponse_ROAStatus_name, RoaResponse_ROAStatus_value)
	proto.RegisterType((*IpAddress)(nil), "glass.ip_address")
	proto.RegisterType((*OriginRequest)(nil), "glass.origin_request")
	proto.RegisterType((*CoordinatesRequest)(nil), "glass.coordinates_request")
	proto.RegisterType((*CoordinatesResponse)(nil), "glass.coordinates_response")
	proto.RegisterType((*OriginResponse)(nil), "glass.origin_response")
	proto.RegisterType((*OriginAsnameRoaRequest)(nil), "glass.origin_asname_roa_request")
	proto.RegisterType((*OriginAsnameRoaResponse)(nil), "glass.origin_asname_roa_response")
	proto.RegisterType((*SourceRequest)(nil), "glass.source_request")
	proto.RegisterType((*VrpsRequest)(nil), "glass.vrps_request")
	proto.RegisterType((*SourceResponse)(nil), "glass.source_response")
	proto.RegisterType((*Empty)(nil), "glass.empty")
	proto.RegisterType((*TotalResponse)(nil), "glass.total_response")
	proto.RegisterType((*AspathRequest)(nil), "glass.aspath_request")
	proto.RegisterType((*AspathResponse)(nil), "glass.aspath_response")
	proto.RegisterType((*Asn)(nil), "glass.asn")
	proto.RegisterType((*RouteRequest)(nil), "glass.route_request")
	proto.RegisterType((*RouteResponse)(nil), "glass.route_response")
	proto.RegisterType((*AsnameRequest)(nil), "glass.asname_request")
	proto.RegisterType((*AsnameResponse)(nil), "glass.asname_response")
	proto.RegisterType((*AsnamesResponse)(nil), "glass.asnames_response")
	proto.RegisterType((*AsnumberAsnames)(nil), "glass.asnumber_asnames")
	proto.RegisterType((*VrpsResponse)(nil), "glass.vrps_response")
	proto.RegisterType((*Vrp)(nil), "glass.vrp")
	proto.RegisterType((*TotalTransitRequest)(nil), "glass.total_transit_request")
	proto.RegisterType((*TotalTransitResponse)(nil), "glass.total_transit_response")
	proto.RegisterType((*TotalAsnsResponse)(nil), "glass.total_asns_response")
	proto.RegisterType((*RoaRequest)(nil), "glass.roa_request")
	proto.RegisterType((*RoaResponse)(nil), "glass.roa_response")
	proto.RegisterType((*LocationRequest)(nil), "glass.location_request")
	proto.RegisterType((*LocationResponse)(nil), "glass.location_response")
	proto.RegisterType((*InvalidsRequest)(nil), "glass.invalids_request")
	proto.RegisterType((*InvalidResponse)(nil), "glass.invalid_response")
	proto.RegisterType((*InvalidOriginator)(nil), "glass.invalid_originator")
}

func init() {
	proto.RegisterFile("glass.proto", fileDescriptor_9ec22f2a0338f3ce)
}

var fileDescriptor_9ec22f2a0338f3ce = []byte{
	// 1171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x17, 0xdb, 0x6e, 0x23, 0x35,
	0x94, 0xc9, 0xb5, 0x39, 0x6d, 0xd2, 0xd4, 0xbd, 0xa5, 0x59, 0x16, 0x95, 0x11, 0x48, 0x2b, 0xed,
	0xb6, 0xea, 0x96, 0x6c, 0x16, 0x21, 0x10, 0x6a, 0x85, 0x84, 0x2a, 0x20, 0x95, 0x86, 0xab, 0x90,
	0x20, 0x72, 0x93, 0x51, 0x6a, 0x76, 0x32, 0x1e, 0xc6, 0x4e, 0xb4, 0x79, 0x40, 0xe2, 0x81, 0xcf,
	0xe0, 0x8d, 0x77, 0xbe, 0x83, 0xcf, 0xe0, 0x53, 0x90, 0x8f, 0x3d, 0x37, 0xa7, 0x37, 0x5a, 0x69,
	0xdf, 0x7c, 0xae, 0x3e, 0xe7, 0xf8, 0xdc, 0x0c, 0xab, 0x93, 0x80, 0x0a, 0x71, 0x18, 0xc5, 0x5c,
	0x72, 0x52, 0x45, 0xc0, 0xfd, 0x08, 0x80, 0x45, 0x43, 0x3a, 0x1e, 0xc7, 0xbe, 0x10, 0xa4, 0x03,
	0x75, 0x73, 0xec, 0x38, 0xfb, 0xce, 0x93, 0x86, 0x97, 0x80, 0x84, 0x40, 0x65, 0x4a, 0xc5, 0xab,
	0x4e, 0x69, 0xdf, 0x79, 0xd2, 0xf4, 0xf0, 0xec, 0x9e, 0x42, 0x8b, 0xc7, 0x6c, 0xc2, 0xc2, 0x61,
	0xec, 0xff, 0x3a, 0xf3, 0x85, 0x24, 0x47, 0x79, 0x6d, 0xa8, 0x62, 0xf5, 0x78, 0xe3, 0x50, 0x5f,
	0x9b, 0x11, 0xbc, 0x06, 0x8b, 0x4e, 0xf4, 0xd1, 0xfd, 0x1c, 0x36, 0x47, 0x9c, 0xc7, 0x63, 0x16,
	0x52, 0xe9, 0x8b, 0x07, 0x28, 0xfa, 0xdd, 0x81, 0xad, 0xa2, 0x26, 0x11, 0xf1, 0x50, 0xf8, 0xca,
	0xf2, 0x11, 0x93, 0x0b, 0xe3, 0x10, 0x9e, 0x95, 0x9f, 0x23, 0x3e, 0x0b, 0x65, 0xbc, 0x40, 0x87,
	0x1a, 0x5e, 0x02, 0x92, 0x36, 0x94, 0x03, 0x2a, 0x3b, 0x65, 0xc4, 0xaa, 0xa3, 0x92, 0x0f, 0x78,
	0x38, 0xe9, 0x54, 0xb4, 0xbc, 0x3a, 0x93, 0x2d, 0xa8, 0xb2, 0x29, 0x9d, 0xf8, 0x9d, 0x2a, 0x22,
	0x35, 0xe0, 0x4e, 0x60, 0x3d, 0x8d, 0x87, 0xb9, 0xfc, 0x31, 0x80, 0x41, 0x51, 0x11, 0xa2, 0x09,
	0x4d, 0xaf, 0xa1, 0x31, 0x27, 0x22, 0x24, 0x3b, 0x50, 0xf3, 0x5f, 0x33, 0x21, 0x05, 0x9a, 0xb1,
	0xe2, 0x19, 0x48, 0x89, 0x8d, 0xe8, 0xe8, 0xd2, 0x1f, 0x4a, 0x36, 0xf5, 0xd1, 0x98, 0x8a, 0xd7,
	0x40, 0xcc, 0x37, 0x6c, 0xea, 0xbb, 0x5f, 0xc1, 0x5e, 0xa6, 0x95, 0x4e, 0xfd, 0x61, 0xcc, 0xe9,
	0x03, 0x42, 0xf7, 0x97, 0x03, 0xdd, 0xab, 0xf4, 0x19, 0x1f, 0x0e, 0xa1, 0xa6, 0xa9, 0x46, 0xd9,
	0x8e, 0x51, 0x66, 0xf9, 0xea, 0x19, 0x2e, 0xc5, 0xaf, 0xd5, 0xa0, 0x53, 0x19, 0x7f, 0xa2, 0x3b,
	0xe5, 0xd7, 0x08, 0xf2, 0x3e, 0x94, 0x63, 0x4e, 0xd1, 0xcb, 0xd5, 0xe3, 0x4d, 0xc3, 0x9c, 0xb7,
	0xc0, 0x53, 0x74, 0xf7, 0x00, 0x5a, 0x82, 0xcf, 0xe2, 0x91, 0x9f, 0x7a, 0xfa, 0x08, 0x1a, 0x54,
	0x0c, 0xc3, 0xd9, 0xf4, 0xc2, 0x8f, 0x4d, 0x6c, 0x57, 0xa8, 0x18, 0x20, 0xec, 0x3e, 0x85, 0xb5,
	0x79, 0x1c, 0x89, 0xbb, 0x31, 0xff, 0xed, 0xc0, 0x7a, 0xaa, 0xdc, 0xb8, 0x6d, 0xc7, 0xb1, 0x7c,
	0x5b, 0x1c, 0xaf, 0x7d, 0xcd, 0x0e, 0xd4, 0xe7, 0x3d, 0x4c, 0x30, 0x74, 0xb2, 0xe9, 0x25, 0x20,
	0x52, 0xfa, 0x9a, 0x52, 0x31, 0x14, 0x0d, 0x5a, 0x19, 0x50, 0xb5, 0x33, 0xa0, 0x0e, 0x55, 0x7f,
	0x1a, 0xc9, 0x85, 0xfb, 0x23, 0xb4, 0x24, 0x97, 0x34, 0xc8, 0xec, 0xde, 0x83, 0x15, 0x3a, 0x92,
	0x6c, 0xee, 0x0f, 0x7b, 0xa6, 0x5a, 0xeb, 0x1a, 0xee, 0xe5, 0x48, 0xfd, 0xe4, 0x3e, 0x0d, 0xf7,
	0x55, 0x96, 0xe7, 0x6e, 0xc2, 0xb3, 0xaa, 0x6f, 0x2a, 0x22, 0x2a, 0x2f, 0x1f, 0x90, 0x5b, 0x7f,
	0x38, 0xb0, 0x9e, 0x2a, 0x31, 0x16, 0xbe, 0x0d, 0x65, 0x5d, 0x0d, 0x2a, 0xa4, 0x90, 0x65, 0x87,
	0xa7, 0xd0, 0x8a, 0x2a, 0x7c, 0xd9, 0x29, 0x2d, 0x53, 0x85, 0x2f, 0x73, 0x31, 0x2e, 0xdf, 0x50,
	0x31, 0x15, 0x3b, 0x5e, 0x2f, 0xf0, 0x4a, 0xec, 0x6f, 0x22, 0x0a, 0x28, 0x4b, 0x6a, 0x31, 0x01,
	0x55, 0x45, 0x53, 0x31, 0xe6, 0xd2, 0xf4, 0x03, 0x0d, 0xb8, 0x27, 0xd0, 0x8c, 0xf9, 0x4c, 0xfa,
	0x0f, 0x08, 0xc0, 0x02, 0x5a, 0x89, 0x8a, 0x6b, 0x12, 0xcb, 0xb9, 0x77, 0x62, 0xdd, 0xd2, 0x26,
	0x0e, 0xd4, 0xfb, 0x99, 0x9a, 0xbb, 0x43, 0x11, 0x9c, 0xaa, 0x97, 0x2a, 0x94, 0x28, 0xd9, 0x55,
	0xf1, 0x1a, 0x62, 0x2d, 0xeb, 0xf6, 0x59, 0xa3, 0x62, 0xa0, 0x6a, 0x76, 0x07, 0x6a, 0x01, 0x1f,
	0xd1, 0xc0, 0x37, 0x9d, 0xd2, 0x40, 0xee, 0x2f, 0xd0, 0xd6, 0x3a, 0x72, 0x0d, 0xf8, 0x25, 0x00,
	0x15, 0xe1, 0x6c, 0x8a, 0x68, 0xf3, 0xea, 0xbb, 0xd9, 0xbb, 0xe2, 0xe5, 0xa6, 0xf1, 0x08, 0x2f,
	0xc7, 0x6a, 0xb9, 0x57, 0xb2, 0xdd, 0xfb, 0x09, 0xef, 0x2a, 0x88, 0xdf, 0xe8, 0x20, 0x79, 0x06,
	0x55, 0x6d, 0xc3, 0xcd, 0x7d, 0x49, 0x33, 0xb9, 0x03, 0x68, 0x9a, 0x06, 0x62, 0xfc, 0x78, 0x07,
	0x2a, 0x0a, 0x61, 0xe5, 0xed, 0x3c, 0x8e, 0x3c, 0xc4, 0xdf, 0x66, 0xee, 0x19, 0x94, 0xe7, 0x71,
	0x74, 0x8f, 0xd7, 0x6f, 0x43, 0x79, 0x4a, 0x5f, 0x9b, 0x5a, 0x56, 0x47, 0xb7, 0x07, 0xdb, 0xba,
	0xe8, 0x65, 0x4c, 0x43, 0xc1, 0xe4, 0xdd, 0xde, 0xf7, 0x10, 0x76, 0x6c, 0x29, 0xe3, 0xd9, 0x16,
	0x54, 0x91, 0x62, 0x44, 0x34, 0xe0, 0xfe, 0xe9, 0xc0, 0xa6, 0x16, 0xa0, 0x22, 0xcc, 0xc5, 0xa1,
	0xad, 0x6a, 0x29, 0xe9, 0x2d, 0xea, 0xa8, 0x31, 0x7d, 0xd3, 0xdc, 0xd4, 0x51, 0xb5, 0x13, 0x2a,
	0x9e, 0x1f, 0x99, 0x2e, 0x83, 0x67, 0xec, 0x3e, 0xa2, 0x37, 0xe4, 0x61, 0xb0, 0xc0, 0x36, 0x83,
	0xd5, 0xd7, 0x3b, 0x0f, 0x83, 0x85, 0x26, 0xf5, 0x35, 0xa9, 0x96, 0x90, 0xfa, 0x48, 0xd2, 0x29,
	0x78, 0xc1, 0xe5, 0xa5, 0xb1, 0xae, 0x46, 0xc5, 0x29, 0x97, 0x97, 0xee, 0xa7, 0xb0, 0xfa, 0xb0,
	0xb1, 0xf7, 0xaf, 0x03, 0x6b, 0x85, 0x41, 0xf7, 0xff, 0x9f, 0xe6, 0x05, 0xd4, 0x84, 0xa4, 0x72,
	0xa6, 0x53, 0xaa, 0x75, 0xfc, 0xf8, 0x8a, 0xe9, 0x75, 0xe8, 0x9d, 0x9f, 0x7c, 0x8d, 0x4c, 0x9e,
	0x61, 0xbe, 0x6f, 0x13, 0x3b, 0x82, 0x46, 0xaa, 0x8b, 0xac, 0x42, 0xfd, 0xdb, 0xc1, 0x17, 0x83,
	0xf3, 0xef, 0x07, 0xed, 0xb7, 0x48, 0x03, 0xaa, 0xdf, 0x9d, 0x7c, 0x79, 0xf6, 0x59, 0xdb, 0x51,
	0xf8, 0xb3, 0x81, 0x06, 0x4a, 0xee, 0x33, 0x68, 0xab, 0xc2, 0x94, 0x8c, 0x67, 0x3b, 0x9a, 0xea,
	0x81, 0x2c, 0x8e, 0x78, 0x2c, 0xd3, 0x1d, 0x4f, 0x83, 0xee, 0x6f, 0xb0, 0x91, 0xe3, 0x7e, 0xe3,
	0xeb, 0xd3, 0x7b, 0xd0, 0x66, 0xe1, 0x9c, 0x06, 0x6c, 0x9c, 0x4d, 0xed, 0x76, 0x32, 0x2a, 0x50,
	0x1f, 0x15, 0xa1, 0xfb, 0x73, 0xca, 0x95, 0xd9, 0xf8, 0x34, 0x3f, 0x50, 0xf6, 0x92, 0x17, 0x33,
	0x5c, 0x7a, 0x2b, 0xa1, 0x92, 0xc7, 0x7a, 0xbe, 0xdc, 0x52, 0xa6, 0x7d, 0x20, 0xcb, 0x92, 0xcb,
	0x76, 0x90, 0x16, 0x94, 0x58, 0x84, 0x53, 0xaa, 0xe1, 0x95, 0x58, 0x74, 0xfc, 0x4f, 0x0d, 0x9a,
	0x01, 0xe7, 0xaf, 0x58, 0x38, 0x19, 0xa2, 0x01, 0xe4, 0x65, 0xb2, 0x37, 0x91, 0x6d, 0x7b, 0x63,
	0x42, 0xe7, 0xba, 0xd7, 0x2c, 0x52, 0x4a, 0x50, 0x8f, 0xcc, 0x54, 0xb0, 0x38, 0x86, 0xbb, 0x3b,
	0x36, 0xda, 0x08, 0xf6, 0xa0, 0x8a, 0xb3, 0x86, 0x6c, 0xa5, 0x79, 0x98, 0x1b, 0x5e, 0xdd, 0x6d,
	0x0b, 0x9b, 0xbf, 0x0e, 0x37, 0xb1, 0x6d, 0xbb, 0x23, 0xda, 0xd7, 0x15, 0xa7, 0xc3, 0x91, 0x2a,
	0x4d, 0xdd, 0x77, 0xd7, 0x0c, 0x0b, 0x2e, 0x25, 0xdd, 0xdd, 0x82, 0x80, 0xc8, 0xaf, 0x92, 0x6a,
	0x95, 0x23, 0xa4, 0x50, 0x26, 0xfa, 0x92, 0xab, 0x16, 0x3f, 0xf2, 0x21, 0xd4, 0xf5, 0x5a, 0x36,
	0x4e, 0x6d, 0x2b, 0xee, 0x80, 0xa9, 0x6d, 0xf6, 0xf6, 0x76, 0x00, 0x35, 0xec, 0x5d, 0xb6, 0x69,
	0x89, 0x1a, 0x6b, 0x69, 0xea, 0x03, 0x64, 0xad, 0xce, 0x12, 0xe9, 0x16, 0x44, 0x8a, 0xbd, 0xf0,
	0x13, 0x58, 0x49, 0x4a, 0x86, 0x24, 0x5e, 0xdb, 0x15, 0xd7, 0xed, 0x2c, 0x13, 0x8c, 0xf8, 0xc7,
	0xb0, 0x92, 0xa4, 0x7c, 0x2a, 0x6e, 0xd7, 0x40, 0xd7, 0x22, 0x64, 0xd2, 0xcf, 0xf5, 0x40, 0x22,
	0x9b, 0xd9, 0x28, 0xca, 0xa4, 0xb6, 0x8a, 0x48, 0x23, 0xf2, 0x03, 0x6c, 0x2c, 0x6d, 0xfa, 0x64,
	0xbf, 0x98, 0x87, 0xcb, 0x7f, 0x8a, 0xee, 0xbb, 0x37, 0x70, 0x18, 0xcd, 0x67, 0xd0, 0x62, 0xd1,
	0x30, 0xf7, 0x03, 0x23, 0x49, 0xdc, 0xae, 0xf8, 0xdf, 0x75, 0x1f, 0x5d, 0x49, 0xd3, 0xaa, 0x2e,
	0x6a, 0xf8, 0x43, 0xfd, 0xe0, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x8b, 0x25, 0x1d, 0xb0,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LookingGlassClient is the client API for LookingGlass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LookingGlassClient interface {
	// origin will return the origin AS number
	Origin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*OriginResponse, error)
	// aspath will return the aspath.
	Aspath(ctx context.Context, in *AspathRequest, opts ...grpc.CallOption) (*AspathResponse, error)
	// route will return the full ip route output.
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// asname will return the AS name.
	Asname(ctx context.Context, in *AsnameRequest, opts ...grpc.CallOption) (*AsnameResponse, error)
	// asnames will return all as number to as names
	Asnames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AsnamesResponse, error)
	// roa will return the roa status.
	Roa(ctx context.Context, in *RoaRequest, opts ...grpc.CallOption) (*RoaResponse, error)
	// sourced will return all the IPv4 and IPv6 prefixes sources by an AS number
	Sourced(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*SourceResponse, error)
	// totals will return the current IPv4 and IPv6 BGP count.
	Totals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalResponse, error)
	// Total number of ASNs
	TotalAsns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalAsnsResponse, error)
	// location will return the city, country, lat/long co-ordinates, and Google maps image of an airport.
	Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
	// invalids will return a list of ASNs originating invalid prefixes, plus a list of prefixes actually originated
	Invalids(ctx context.Context, in *InvalidsRequest, opts ...grpc.CallOption) (*InvalidResponse, error)
	// vrps will return a list of all VRPs for a source AS
	Vrps(ctx context.Context, in *VrpsRequest, opts ...grpc.CallOption) (*VrpsResponse, error)
	// origin_asname_roa will return the three required fields for a tracerpki hop.
	OriginAsnameRoa(ctx context.Context, in *OriginAsnameRoaRequest, opts ...grpc.CallOption) (*OriginAsnameRoaResponse, error)
	// ip_coordinates will attempt to return the longitude and latitude of an IP.
	IpCoordinates(ctx context.Context, in *CoordinatesRequest, opts ...grpc.CallOption) (*CoordinatesResponse, error)
}

type lookingGlassClient struct {
	cc grpc.ClientConnInterface
}

func NewLookingGlassClient(cc grpc.ClientConnInterface) LookingGlassClient {
	return &lookingGlassClient{cc}
}

func (c *lookingGlassClient) Origin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*OriginResponse, error) {
	out := new(OriginResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/origin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Aspath(ctx context.Context, in *AspathRequest, opts ...grpc.CallOption) (*AspathResponse, error) {
	out := new(AspathResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/aspath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/route", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Asname(ctx context.Context, in *AsnameRequest, opts ...grpc.CallOption) (*AsnameResponse, error) {
	out := new(AsnameResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/asname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Asnames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AsnamesResponse, error) {
	out := new(AsnamesResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/asnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Roa(ctx context.Context, in *RoaRequest, opts ...grpc.CallOption) (*RoaResponse, error) {
	out := new(RoaResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/roa", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Sourced(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*SourceResponse, error) {
	out := new(SourceResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/sourced", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Totals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalResponse, error) {
	out := new(TotalResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/totals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) TotalAsns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalAsnsResponse, error) {
	out := new(TotalAsnsResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/total_asns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/location", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Invalids(ctx context.Context, in *InvalidsRequest, opts ...grpc.CallOption) (*InvalidResponse, error) {
	out := new(InvalidResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/invalids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) Vrps(ctx context.Context, in *VrpsRequest, opts ...grpc.CallOption) (*VrpsResponse, error) {
	out := new(VrpsResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/vrps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) OriginAsnameRoa(ctx context.Context, in *OriginAsnameRoaRequest, opts ...grpc.CallOption) (*OriginAsnameRoaResponse, error) {
	out := new(OriginAsnameRoaResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/origin_asname_roa", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookingGlassClient) IpCoordinates(ctx context.Context, in *CoordinatesRequest, opts ...grpc.CallOption) (*CoordinatesResponse, error) {
	out := new(CoordinatesResponse)
	err := c.cc.Invoke(ctx, "/glass.looking_glass/ip_coordinates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookingGlassServer is the server API for LookingGlass service.
type LookingGlassServer interface {
	// origin will return the origin AS number
	Origin(context.Context, *OriginRequest) (*OriginResponse, error)
	// aspath will return the aspath.
	Aspath(context.Context, *AspathRequest) (*AspathResponse, error)
	// route will return the full ip route output.
	Route(context.Context, *RouteRequest) (*RouteResponse, error)
	// asname will return the AS name.
	Asname(context.Context, *AsnameRequest) (*AsnameResponse, error)
	// asnames will return all as number to as names
	Asnames(context.Context, *Empty) (*AsnamesResponse, error)
	// roa will return the roa status.
	Roa(context.Context, *RoaRequest) (*RoaResponse, error)
	// sourced will return all the IPv4 and IPv6 prefixes sources by an AS number
	Sourced(context.Context, *SourceRequest) (*SourceResponse, error)
	// totals will return the current IPv4 and IPv6 BGP count.
	Totals(context.Context, *Empty) (*TotalResponse, error)
	// Total number of ASNs
	TotalAsns(context.Context, *Empty) (*TotalAsnsResponse, error)
	// location will return the city, country, lat/long co-ordinates, and Google maps image of an airport.
	Location(context.Context, *LocationRequest) (*LocationResponse, error)
	// invalids will return a list of ASNs originating invalid prefixes, plus a list of prefixes actually originated
	Invalids(context.Context, *InvalidsRequest) (*InvalidResponse, error)
	// vrps will return a list of all VRPs for a source AS
	Vrps(context.Context, *VrpsRequest) (*VrpsResponse, error)
	// origin_asname_roa will return the three required fields for a tracerpki hop.
	OriginAsnameRoa(context.Context, *OriginAsnameRoaRequest) (*OriginAsnameRoaResponse, error)
	// ip_coordinates will attempt to return the longitude and latitude of an IP.
	IpCoordinates(context.Context, *CoordinatesRequest) (*CoordinatesResponse, error)
}

// UnimplementedLookingGlassServer can be embedded to have forward compatible implementations.
type UnimplementedLookingGlassServer struct {
}

func (*UnimplementedLookingGlassServer) Origin(ctx context.Context, req *OriginRequest) (*OriginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Origin not implemented")
}
func (*UnimplementedLookingGlassServer) Aspath(ctx context.Context, req *AspathRequest) (*AspathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Aspath not implemented")
}
func (*UnimplementedLookingGlassServer) Route(ctx context.Context, req *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (*UnimplementedLookingGlassServer) Asname(ctx context.Context, req *AsnameRequest) (*AsnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Asname not implemented")
}
func (*UnimplementedLookingGlassServer) Asnames(ctx context.Context, req *Empty) (*AsnamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Asnames not implemented")
}
func (*UnimplementedLookingGlassServer) Roa(ctx context.Context, req *RoaRequest) (*RoaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Roa not implemented")
}
func (*UnimplementedLookingGlassServer) Sourced(ctx context.Context, req *SourceRequest) (*SourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sourced not implemented")
}
func (*UnimplementedLookingGlassServer) Totals(ctx context.Context, req *Empty) (*TotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Totals not implemented")
}
func (*UnimplementedLookingGlassServer) TotalAsns(ctx context.Context, req *Empty) (*TotalAsnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalAsns not implemented")
}
func (*UnimplementedLookingGlassServer) Location(ctx context.Context, req *LocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Location not implemented")
}
func (*UnimplementedLookingGlassServer) Invalids(ctx context.Context, req *InvalidsRequest) (*InvalidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invalids not implemented")
}
func (*UnimplementedLookingGlassServer) Vrps(ctx context.Context, req *VrpsRequest) (*VrpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vrps not implemented")
}
func (*UnimplementedLookingGlassServer) OriginAsnameRoa(ctx context.Context, req *OriginAsnameRoaRequest) (*OriginAsnameRoaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OriginAsnameRoa not implemented")
}
func (*UnimplementedLookingGlassServer) IpCoordinates(ctx context.Context, req *CoordinatesRequest) (*CoordinatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IpCoordinates not implemented")
}

func RegisterLookingGlassServer(s *grpc.Server, srv LookingGlassServer) {
	s.RegisterService(&_LookingGlass_serviceDesc, srv)
}

func _LookingGlass_Origin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Origin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Origin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Origin(ctx, req.(*OriginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Aspath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AspathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Aspath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Aspath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Aspath(ctx, req.(*AspathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Route",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Asname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Asname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Asname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Asname(ctx, req.(*AsnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Asnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Asnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Asnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Asnames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Roa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Roa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Roa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Roa(ctx, req.(*RoaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Sourced_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Sourced(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Sourced",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Sourced(ctx, req.(*SourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Totals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Totals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Totals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Totals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_TotalAsns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).TotalAsns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/TotalAsns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).TotalAsns(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Location_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Location(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Location",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Location(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Invalids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Invalids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Invalids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Invalids(ctx, req.(*InvalidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_Vrps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VrpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).Vrps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/Vrps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).Vrps(ctx, req.(*VrpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_OriginAsnameRoa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginAsnameRoaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).OriginAsnameRoa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/OriginAsnameRoa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).OriginAsnameRoa(ctx, req.(*OriginAsnameRoaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookingGlass_IpCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookingGlassServer).IpCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glass.looking_glass/IpCoordinates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookingGlassServer).IpCoordinates(ctx, req.(*CoordinatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LookingGlass_serviceDesc = grpc.ServiceDesc{
	ServiceName: "glass.looking_glass",
	HandlerType: (*LookingGlassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "origin",
			Handler:    _LookingGlass_Origin_Handler,
		},
		{
			MethodName: "aspath",
			Handler:    _LookingGlass_Aspath_Handler,
		},
		{
			MethodName: "route",
			Handler:    _LookingGlass_Route_Handler,
		},
		{
			MethodName: "asname",
			Handler:    _LookingGlass_Asname_Handler,
		},
		{
			MethodName: "asnames",
			Handler:    _LookingGlass_Asnames_Handler,
		},
		{
			MethodName: "roa",
			Handler:    _LookingGlass_Roa_Handler,
		},
		{
			MethodName: "sourced",
			Handler:    _LookingGlass_Sourced_Handler,
		},
		{
			MethodName: "totals",
			Handler:    _LookingGlass_Totals_Handler,
		},
		{
			MethodName: "total_asns",
			Handler:    _LookingGlass_TotalAsns_Handler,
		},
		{
			MethodName: "location",
			Handler:    _LookingGlass_Location_Handler,
		},
		{
			MethodName: "invalids",
			Handler:    _LookingGlass_Invalids_Handler,
		},
		{
			MethodName: "vrps",
			Handler:    _LookingGlass_Vrps_Handler,
		},
		{
			MethodName: "origin_asname_roa",
			Handler:    _LookingGlass_OriginAsnameRoa_Handler,
		},
		{
			MethodName: "ip_coordinates",
			Handler:    _LookingGlass_IpCoordinates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "glass.proto",
}
