// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grapher.proto

package grapher

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestRequest struct {
	Testmessage          string   `protobuf:"bytes,1,opt,name=testmessage,proto3" json:"testmessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{0}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetTestmessage() string {
	if m != nil {
		return m.Testmessage
	}
	return ""
}

type TestResponse struct {
	Testresponse         string   `protobuf:"bytes,1,opt,name=testresponse,proto3" json:"testresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{1}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetTestresponse() string {
	if m != nil {
		return m.Testresponse
	}
	return ""
}

type LineGraphRequest struct {
	// Requests a line graph for FIB totals in each address family.
	Metadatas            []*Metadata  `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	TotalsTime           []*TotalTime `protobuf:"bytes,2,rep,name=totals_time,json=totalsTime,proto3" json:"totals_time,omitempty"`
	Copyright            string       `protobuf:"bytes,3,opt,name=copyright,proto3" json:"copyright,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LineGraphRequest) Reset()         { *m = LineGraphRequest{} }
func (m *LineGraphRequest) String() string { return proto.CompactTextString(m) }
func (*LineGraphRequest) ProtoMessage()    {}
func (*LineGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{2}
}

func (m *LineGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineGraphRequest.Unmarshal(m, b)
}
func (m *LineGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineGraphRequest.Marshal(b, m, deterministic)
}
func (m *LineGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineGraphRequest.Merge(m, src)
}
func (m *LineGraphRequest) XXX_Size() int {
	return xxx_messageInfo_LineGraphRequest.Size(m)
}
func (m *LineGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LineGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LineGraphRequest proto.InternalMessageInfo

func (m *LineGraphRequest) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

func (m *LineGraphRequest) GetTotalsTime() []*TotalTime {
	if m != nil {
		return m.TotalsTime
	}
	return nil
}

func (m *LineGraphRequest) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

type PieChartRequest struct {
	// Requests a pie chart showing subnet distribution from the total.
	Metadatas            []*Metadata   `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	Subnets              *SubnetFamily `protobuf:"bytes,2,opt,name=subnets,proto3" json:"subnets,omitempty"`
	Copyright            string        `protobuf:"bytes,3,opt,name=copyright,proto3" json:"copyright,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PieChartRequest) Reset()         { *m = PieChartRequest{} }
func (m *PieChartRequest) String() string { return proto.CompactTextString(m) }
func (*PieChartRequest) ProtoMessage()    {}
func (*PieChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{3}
}

func (m *PieChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChartRequest.Unmarshal(m, b)
}
func (m *PieChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChartRequest.Marshal(b, m, deterministic)
}
func (m *PieChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChartRequest.Merge(m, src)
}
func (m *PieChartRequest) XXX_Size() int {
	return xxx_messageInfo_PieChartRequest.Size(m)
}
func (m *PieChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieChartRequest proto.InternalMessageInfo

func (m *PieChartRequest) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

func (m *PieChartRequest) GetSubnets() *SubnetFamily {
	if m != nil {
		return m.Subnets
	}
	return nil
}

func (m *PieChartRequest) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

type RPKIRequest struct {
	// Requests an RPKI spread chart.
	Metadatas            []*Metadata `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	Rpkis                *RPKI       `protobuf:"bytes,2,opt,name=rpkis,proto3" json:"rpkis,omitempty"`
	Copyright            string      `protobuf:"bytes,3,opt,name=copyright,proto3" json:"copyright,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RPKIRequest) Reset()         { *m = RPKIRequest{} }
func (m *RPKIRequest) String() string { return proto.CompactTextString(m) }
func (*RPKIRequest) ProtoMessage()    {}
func (*RPKIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{4}
}

func (m *RPKIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPKIRequest.Unmarshal(m, b)
}
func (m *RPKIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPKIRequest.Marshal(b, m, deterministic)
}
func (m *RPKIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPKIRequest.Merge(m, src)
}
func (m *RPKIRequest) XXX_Size() int {
	return xxx_messageInfo_RPKIRequest.Size(m)
}
func (m *RPKIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPKIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPKIRequest proto.InternalMessageInfo

func (m *RPKIRequest) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

func (m *RPKIRequest) GetRpkis() *RPKI {
	if m != nil {
		return m.Rpkis
	}
	return nil
}

func (m *RPKIRequest) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

type RPKI struct {
	V4Valid              uint32   `protobuf:"varint,1,opt,name=v4_valid,json=v4Valid,proto3" json:"v4_valid,omitempty"`
	V4Invalid            uint32   `protobuf:"varint,2,opt,name=v4_invalid,json=v4Invalid,proto3" json:"v4_invalid,omitempty"`
	V4Unknown            uint32   `protobuf:"varint,3,opt,name=v4_unknown,json=v4Unknown,proto3" json:"v4_unknown,omitempty"`
	V6Valid              uint32   `protobuf:"varint,4,opt,name=v6_valid,json=v6Valid,proto3" json:"v6_valid,omitempty"`
	V6Invalid            uint32   `protobuf:"varint,5,opt,name=v6_invalid,json=v6Invalid,proto3" json:"v6_invalid,omitempty"`
	V6Unknown            uint32   `protobuf:"varint,6,opt,name=v6_unknown,json=v6Unknown,proto3" json:"v6_unknown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPKI) Reset()         { *m = RPKI{} }
func (m *RPKI) String() string { return proto.CompactTextString(m) }
func (*RPKI) ProtoMessage()    {}
func (*RPKI) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{5}
}

func (m *RPKI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPKI.Unmarshal(m, b)
}
func (m *RPKI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPKI.Marshal(b, m, deterministic)
}
func (m *RPKI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPKI.Merge(m, src)
}
func (m *RPKI) XXX_Size() int {
	return xxx_messageInfo_RPKI.Size(m)
}
func (m *RPKI) XXX_DiscardUnknown() {
	xxx_messageInfo_RPKI.DiscardUnknown(m)
}

var xxx_messageInfo_RPKI proto.InternalMessageInfo

func (m *RPKI) GetV4Valid() uint32 {
	if m != nil {
		return m.V4Valid
	}
	return 0
}

func (m *RPKI) GetV4Invalid() uint32 {
	if m != nil {
		return m.V4Invalid
	}
	return 0
}

func (m *RPKI) GetV4Unknown() uint32 {
	if m != nil {
		return m.V4Unknown
	}
	return 0
}

func (m *RPKI) GetV6Valid() uint32 {
	if m != nil {
		return m.V6Valid
	}
	return 0
}

func (m *RPKI) GetV6Invalid() uint32 {
	if m != nil {
		return m.V6Invalid
	}
	return 0
}

func (m *RPKI) GetV6Unknown() uint32 {
	if m != nil {
		return m.V6Unknown
	}
	return 0
}

type TotalTime struct {
	// v4 FIB, v6 FIB, and the time it was at those values.
	V4Values             uint32   `protobuf:"varint,1,opt,name=v4_values,json=v4Values,proto3" json:"v4_values,omitempty"`
	V6Values             uint32   `protobuf:"varint,2,opt,name=v6_values,json=v6Values,proto3" json:"v6_values,omitempty"`
	Time                 uint64   `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalTime) Reset()         { *m = TotalTime{} }
func (m *TotalTime) String() string { return proto.CompactTextString(m) }
func (*TotalTime) ProtoMessage()    {}
func (*TotalTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{6}
}

func (m *TotalTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalTime.Unmarshal(m, b)
}
func (m *TotalTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalTime.Marshal(b, m, deterministic)
}
func (m *TotalTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalTime.Merge(m, src)
}
func (m *TotalTime) XXX_Size() int {
	return xxx_messageInfo_TotalTime.Size(m)
}
func (m *TotalTime) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalTime.DiscardUnknown(m)
}

var xxx_messageInfo_TotalTime proto.InternalMessageInfo

func (m *TotalTime) GetV4Values() uint32 {
	if m != nil {
		return m.V4Values
	}
	return 0
}

func (m *TotalTime) GetV6Values() uint32 {
	if m != nil {
		return m.V6Values
	}
	return 0
}

func (m *TotalTime) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type SubnetFamily struct {
	V4Values             []uint32 `protobuf:"varint,1,rep,packed,name=v4_values,json=v4Values,proto3" json:"v4_values,omitempty"`
	V6Values             []uint32 `protobuf:"varint,2,rep,packed,name=v6_values,json=v6Values,proto3" json:"v6_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubnetFamily) Reset()         { *m = SubnetFamily{} }
func (m *SubnetFamily) String() string { return proto.CompactTextString(m) }
func (*SubnetFamily) ProtoMessage()    {}
func (*SubnetFamily) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{7}
}

func (m *SubnetFamily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubnetFamily.Unmarshal(m, b)
}
func (m *SubnetFamily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubnetFamily.Marshal(b, m, deterministic)
}
func (m *SubnetFamily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetFamily.Merge(m, src)
}
func (m *SubnetFamily) XXX_Size() int {
	return xxx_messageInfo_SubnetFamily.Size(m)
}
func (m *SubnetFamily) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetFamily.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetFamily proto.InternalMessageInfo

func (m *SubnetFamily) GetV4Values() []uint32 {
	if m != nil {
		return m.V4Values
	}
	return nil
}

func (m *SubnetFamily) GetV6Values() []uint32 {
	if m != nil {
		return m.V6Values
	}
	return nil
}

type Metadata struct {
	// Used to create the image.
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XAxis                uint32   `protobuf:"varint,2,opt,name=x_axis,json=xAxis,proto3" json:"x_axis,omitempty"`
	YAxis                uint32   `protobuf:"varint,3,opt,name=y_axis,json=yAxis,proto3" json:"y_axis,omitempty"`
	Colour               string   `protobuf:"bytes,4,opt,name=colour,proto3" json:"colour,omitempty"`
	Colours              []string `protobuf:"bytes,5,rep,name=colours,proto3" json:"colours,omitempty"`
	Labels               []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Theme                string   `protobuf:"bytes,7,opt,name=theme,proto3" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{8}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Metadata) GetXAxis() uint32 {
	if m != nil {
		return m.XAxis
	}
	return 0
}

func (m *Metadata) GetYAxis() uint32 {
	if m != nil {
		return m.YAxis
	}
	return 0
}

func (m *Metadata) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Metadata) GetColours() []string {
	if m != nil {
		return m.Colours
	}
	return nil
}

func (m *Metadata) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Metadata) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

type GrapherResponse struct {
	// There should always be two images sent back, once for each address family.
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrapherResponse) Reset()         { *m = GrapherResponse{} }
func (m *GrapherResponse) String() string { return proto.CompactTextString(m) }
func (*GrapherResponse) ProtoMessage()    {}
func (*GrapherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{9}
}

func (m *GrapherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrapherResponse.Unmarshal(m, b)
}
func (m *GrapherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrapherResponse.Marshal(b, m, deterministic)
}
func (m *GrapherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrapherResponse.Merge(m, src)
}
func (m *GrapherResponse) XXX_Size() int {
	return xxx_messageInfo_GrapherResponse.Size(m)
}
func (m *GrapherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrapherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrapherResponse proto.InternalMessageInfo

func (m *GrapherResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Image struct {
	// The image itself. Also the title of each if required.
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_be4babf5a89407b9, []int{10}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Image) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "grapher.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "grapher.TestResponse")
	proto.RegisterType((*LineGraphRequest)(nil), "grapher.LineGraphRequest")
	proto.RegisterType((*PieChartRequest)(nil), "grapher.PieChartRequest")
	proto.RegisterType((*RPKIRequest)(nil), "grapher.RPKIRequest")
	proto.RegisterType((*RPKI)(nil), "grapher.RPKI")
	proto.RegisterType((*TotalTime)(nil), "grapher.TotalTime")
	proto.RegisterType((*SubnetFamily)(nil), "grapher.SubnetFamily")
	proto.RegisterType((*Metadata)(nil), "grapher.Metadata")
	proto.RegisterType((*GrapherResponse)(nil), "grapher.GrapherResponse")
	proto.RegisterType((*Image)(nil), "grapher.Image")
}

func init() {
	proto.RegisterFile("grapher.proto", fileDescriptor_be4babf5a89407b9)
}

var fileDescriptor_be4babf5a89407b9 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0x45, 0xb2, 0x25, 0x45, 0x23, 0xe7, 0x97, 0x5f, 0x97, 0xa4, 0x28, 0x69, 0x0b, 0x46, 0x85,
	0xe2, 0x53, 0x02, 0x8e, 0x11, 0xe4, 0x18, 0x02, 0x75, 0x43, 0x5b, 0x08, 0xdb, 0xb4, 0xd0, 0x93,
	0xd9, 0x24, 0x8b, 0xbd, 0x44, 0x7f, 0x5c, 0xed, 0xca, 0xb5, 0x8f, 0x85, 0x7e, 0x81, 0x5e, 0xfa,
	0x31, 0x7a, 0xee, 0xc7, 0x2b, 0xfb, 0x4f, 0x56, 0x7c, 0x88, 0x21, 0x37, 0xcd, 0x7b, 0x33, 0x6f,
	0xdf, 0x6a, 0x67, 0x06, 0x76, 0xa7, 0x15, 0x99, 0xcf, 0x68, 0x75, 0x3c, 0xaf, 0x4a, 0x51, 0xa2,
	0xc0, 0x84, 0xc9, 0x09, 0x44, 0xd7, 0x94, 0x0b, 0x4c, 0xbf, 0xd5, 0x94, 0x0b, 0xd4, 0x87, 0x48,
	0x50, 0x2e, 0x72, 0xca, 0x39, 0x99, 0xd2, 0xd8, 0xe9, 0x3b, 0x83, 0x10, 0xb7, 0xa1, 0x64, 0x08,
	0x3d, 0x5d, 0xc0, 0xe7, 0x65, 0xc1, 0x29, 0x4a, 0xa0, 0x27, 0xe9, 0xca, 0xc4, 0xa6, 0xe4, 0x01,
	0x96, 0xfc, 0x76, 0xe0, 0xff, 0x0f, 0xac, 0xa0, 0x63, 0x79, 0xa8, 0x3d, 0xea, 0x04, 0xc2, 0x9c,
	0x0a, 0x72, 0x47, 0x04, 0xe1, 0xb1, 0xd3, 0xef, 0x0c, 0xa2, 0xe1, 0xb3, 0x63, 0xeb, 0xf2, 0xa3,
	0x61, 0xf0, 0x3a, 0x07, 0x9d, 0x42, 0x24, 0x4a, 0x41, 0x32, 0x3e, 0x11, 0x2c, 0xa7, 0xb1, 0xab,
	0x4a, 0x50, 0x53, 0x72, 0x2d, 0xb9, 0x6b, 0x96, 0x53, 0x0c, 0x3a, 0x4d, 0x7e, 0xa3, 0x97, 0x10,
	0xde, 0x96, 0xf3, 0x55, 0xc5, 0xa6, 0x33, 0x11, 0x77, 0x94, 0xb7, 0x35, 0x90, 0xfc, 0x72, 0x60,
	0xef, 0x8a, 0xd1, 0x8b, 0x19, 0xa9, 0xc4, 0x93, 0x7d, 0x9d, 0x40, 0xc0, 0xeb, 0x9b, 0x82, 0x0a,
	0x1e, 0xbb, 0x7d, 0x67, 0x10, 0x0d, 0x0f, 0x9a, 0xf4, 0x4f, 0x0a, 0x7f, 0x4b, 0x72, 0x96, 0xad,
	0xb0, 0xcd, 0xda, 0xe2, 0xe9, 0x87, 0x03, 0x11, 0xbe, 0x7a, 0x7f, 0xf9, 0x64, 0x3f, 0xaf, 0xc1,
	0xab, 0xe6, 0xf7, 0xcc, 0xba, 0xd9, 0x6d, 0x92, 0x95, 0xaa, 0xe6, 0xb6, 0x78, 0xf8, 0xeb, 0x40,
	0x57, 0x66, 0xa3, 0x43, 0xd8, 0x59, 0x8c, 0x26, 0x0b, 0x92, 0xb1, 0x3b, 0xf5, 0xb2, 0xbb, 0x38,
	0x58, 0x8c, 0xbe, 0xc8, 0x10, 0xbd, 0x02, 0x58, 0x8c, 0x26, 0xac, 0xd0, 0xa4, 0xab, 0xc8, 0x70,
	0x31, 0xba, 0xd4, 0x80, 0xa1, 0xeb, 0xe2, 0xbe, 0x28, 0xbf, 0x17, 0xea, 0x04, 0x45, 0x7f, 0xd6,
	0x80, 0x12, 0x4e, 0x8d, 0x70, 0xd7, 0x08, 0xa7, 0x6b, 0xe1, 0xb4, 0x11, 0xf6, 0x4c, 0x65, 0xda,
	0x16, 0x4e, 0x1b, 0x61, 0xdf, 0xd2, 0x46, 0x38, 0xf9, 0x0a, 0x61, 0xd3, 0x09, 0xe8, 0x05, 0x84,
	0xda, 0x7e, 0x4d, 0xb9, 0xf1, 0xbf, 0xa3, 0xfc, 0xd7, 0x94, 0x2b, 0x32, 0xb5, 0xa4, 0x6b, 0xc8,
	0xd4, 0x90, 0x08, 0xba, 0xaa, 0xcb, 0xa4, 0xf1, 0x2e, 0x56, 0xdf, 0xc9, 0x3b, 0xe8, 0xb5, 0x1f,
	0x74, 0x53, 0xbd, 0xf3, 0x98, 0x7a, 0xa7, 0xad, 0x9e, 0xfc, 0x71, 0x60, 0xc7, 0x3e, 0x1d, 0xda,
	0x07, 0x4f, 0x30, 0x91, 0xd9, 0xd1, 0xd1, 0x01, 0x3a, 0x00, 0x7f, 0x39, 0x21, 0x4b, 0x66, 0xad,
	0x79, 0xcb, 0xf3, 0x25, 0xe3, 0x12, 0x5e, 0x69, 0x58, 0xff, 0x52, 0x6f, 0xa5, 0xe0, 0xe7, 0xe0,
	0xdf, 0x96, 0x59, 0x59, 0x57, 0xea, 0x67, 0x86, 0xd8, 0x44, 0x28, 0x86, 0x40, 0x7f, 0xf1, 0xd8,
	0xeb, 0x77, 0x06, 0x21, 0xb6, 0xa1, 0xac, 0xc8, 0xc8, 0x0d, 0xcd, 0x78, 0xec, 0x2b, 0xc2, 0x44,
	0xca, 0xcd, 0x8c, 0xe6, 0x34, 0x0e, 0x8c, 0x1b, 0x19, 0x24, 0x67, 0xb0, 0x37, 0xd6, 0x5d, 0xd4,
	0x0c, 0xfe, 0x1b, 0xf0, 0x59, 0x4e, 0xa6, 0xd4, 0x36, 0xe5, 0x7f, 0x4d, 0x9f, 0x5d, 0x4a, 0x18,
	0x1b, 0x36, 0x39, 0x05, 0x4f, 0x01, 0x52, 0x59, 0x41, 0xea, 0x9e, 0x3d, 0xac, 0x83, 0xf5, 0xed,
	0xdd, 0xd6, 0xed, 0x87, 0x3f, 0x5d, 0x08, 0xcc, 0x81, 0xe8, 0x02, 0x7a, 0x63, 0x2a, 0x9a, 0xfd,
	0x81, 0x0e, 0x9b, 0x83, 0x36, 0x77, 0xca, 0x51, 0xdc, 0x50, 0x9b, 0x6e, 0xcf, 0x21, 0x1a, 0x53,
	0x61, 0x67, 0x1d, 0xad, 0x13, 0x37, 0xc6, 0xff, 0x11, 0x89, 0x33, 0x08, 0xc6, 0x54, 0xa8, 0xb1,
	0xd8, 0x7f, 0x38, 0x53, 0x5b, 0x4b, 0x53, 0x08, 0xd4, 0xd2, 0xbc, 0xba, 0x68, 0x95, 0xb6, 0xf6,
	0xee, 0xd1, 0xc1, 0x06, 0xaa, 0xeb, 0x6e, 0x7c, 0xb5, 0xad, 0x4f, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x9b, 0xcf, 0x02, 0xbe, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrapherClient is the client API for Grapher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrapherClient interface {
	GetLineGraph(ctx context.Context, in *LineGraphRequest, opts ...grpc.CallOption) (*GrapherResponse, error)
	GetPieChart(ctx context.Context, in *PieChartRequest, opts ...grpc.CallOption) (*GrapherResponse, error)
	GetRPKI(ctx context.Context, in *RPKIRequest, opts ...grpc.CallOption) (*GrapherResponse, error)
	TestRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type grapherClient struct {
	cc grpc.ClientConnInterface
}

func NewGrapherClient(cc grpc.ClientConnInterface) GrapherClient {
	return &grapherClient{cc}
}

func (c *grapherClient) GetLineGraph(ctx context.Context, in *LineGraphRequest, opts ...grpc.CallOption) (*GrapherResponse, error) {
	out := new(GrapherResponse)
	err := c.cc.Invoke(ctx, "/grapher.Grapher/GetLineGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grapherClient) GetPieChart(ctx context.Context, in *PieChartRequest, opts ...grpc.CallOption) (*GrapherResponse, error) {
	out := new(GrapherResponse)
	err := c.cc.Invoke(ctx, "/grapher.Grapher/GetPieChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grapherClient) GetRPKI(ctx context.Context, in *RPKIRequest, opts ...grpc.CallOption) (*GrapherResponse, error) {
	out := new(GrapherResponse)
	err := c.cc.Invoke(ctx, "/grapher.Grapher/GetRPKI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grapherClient) TestRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/grapher.Grapher/TestRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrapherServer is the server API for Grapher service.
type GrapherServer interface {
	GetLineGraph(context.Context, *LineGraphRequest) (*GrapherResponse, error)
	GetPieChart(context.Context, *PieChartRequest) (*GrapherResponse, error)
	GetRPKI(context.Context, *RPKIRequest) (*GrapherResponse, error)
	TestRPC(context.Context, *TestRequest) (*TestResponse, error)
}

// UnimplementedGrapherServer can be embedded to have forward compatible implementations.
type UnimplementedGrapherServer struct {
}

func (*UnimplementedGrapherServer) GetLineGraph(ctx context.Context, req *LineGraphRequest) (*GrapherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLineGraph not implemented")
}
func (*UnimplementedGrapherServer) GetPieChart(ctx context.Context, req *PieChartRequest) (*GrapherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPieChart not implemented")
}
func (*UnimplementedGrapherServer) GetRPKI(ctx context.Context, req *RPKIRequest) (*GrapherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRPKI not implemented")
}
func (*UnimplementedGrapherServer) TestRPC(ctx context.Context, req *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestRPC not implemented")
}

func RegisterGrapherServer(s *grpc.Server, srv GrapherServer) {
	s.RegisterService(&_Grapher_serviceDesc, srv)
}

func _Grapher_GetLineGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LineGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrapherServer).GetLineGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapher.Grapher/GetLineGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrapherServer).GetLineGraph(ctx, req.(*LineGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grapher_GetPieChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PieChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrapherServer).GetPieChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapher.Grapher/GetPieChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrapherServer).GetPieChart(ctx, req.(*PieChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grapher_GetRPKI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPKIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrapherServer).GetRPKI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapher.Grapher/GetRPKI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrapherServer).GetRPKI(ctx, req.(*RPKIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grapher_TestRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrapherServer).TestRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapher.Grapher/TestRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrapherServer).TestRPC(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grapher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grapher.Grapher",
	HandlerType: (*GrapherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLineGraph",
			Handler:    _Grapher_GetLineGraph_Handler,
		},
		{
			MethodName: "GetPieChart",
			Handler:    _Grapher_GetPieChart_Handler,
		},
		{
			MethodName: "GetRPKI",
			Handler:    _Grapher_GetRPKI_Handler,
		},
		{
			MethodName: "TestRPC",
			Handler:    _Grapher_TestRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grapher.proto",
}
