// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tweeter.proto

package poster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostMessageRequest struct {
	Message              string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MastadonAccount      *MastadonAccount `protobuf:"bytes,2,opt,name=mastadon_account,json=mastadonAccount,proto3" json:"mastadon_account,omitempty"`
	TwitterAccount       *TwitterAccount  `protobuf:"bytes,3,opt,name=twitter_account,json=twitterAccount,proto3" json:"twitter_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PostMessageRequest) Reset()         { *m = PostMessageRequest{} }
func (m *PostMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PostMessageRequest) ProtoMessage()    {}
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{0}
}

func (m *PostMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageRequest.Unmarshal(m, b)
}
func (m *PostMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageRequest.Marshal(b, m, deterministic)
}
func (m *PostMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageRequest.Merge(m, src)
}
func (m *PostMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PostMessageRequest.Size(m)
}
func (m *PostMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageRequest proto.InternalMessageInfo

func (m *PostMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostMessageRequest) GetMastadonAccount() *MastadonAccount {
	if m != nil {
		return m.MastadonAccount
	}
	return nil
}

func (m *PostMessageRequest) GetTwitterAccount() *TwitterAccount {
	if m != nil {
		return m.TwitterAccount
	}
	return nil
}

type PostMessagesRequest struct {
	PostMessageRequests          []*PostMessageRequest          `protobuf:"bytes,1,rep,name=post_message_requests,json=postMessageRequests,proto3" json:"post_message_requests,omitempty"`
	PostMessageWithImageRequests []*PostMessageWithImageRequest `protobuf:"bytes,2,rep,name=post_message_with_image_requests,json=postMessageWithImageRequests,proto3" json:"post_message_with_image_requests,omitempty"`
	PostMessageWithVideoRequests []*PostMessageWithVideoRequest `protobuf:"bytes,3,rep,name=post_message_with_video_requests,json=postMessageWithVideoRequests,proto3" json:"post_message_with_video_requests,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                       `json:"-"`
	XXX_unrecognized             []byte                         `json:"-"`
	XXX_sizecache                int32                          `json:"-"`
}

func (m *PostMessagesRequest) Reset()         { *m = PostMessagesRequest{} }
func (m *PostMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*PostMessagesRequest) ProtoMessage()    {}
func (*PostMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{1}
}

func (m *PostMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessagesRequest.Unmarshal(m, b)
}
func (m *PostMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessagesRequest.Marshal(b, m, deterministic)
}
func (m *PostMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessagesRequest.Merge(m, src)
}
func (m *PostMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_PostMessagesRequest.Size(m)
}
func (m *PostMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessagesRequest proto.InternalMessageInfo

func (m *PostMessagesRequest) GetPostMessageRequests() []*PostMessageRequest {
	if m != nil {
		return m.PostMessageRequests
	}
	return nil
}

func (m *PostMessagesRequest) GetPostMessageWithImageRequests() []*PostMessageWithImageRequest {
	if m != nil {
		return m.PostMessageWithImageRequests
	}
	return nil
}

func (m *PostMessagesRequest) GetPostMessageWithVideoRequests() []*PostMessageWithVideoRequest {
	if m != nil {
		return m.PostMessageWithVideoRequests
	}
	return nil
}

type PostMessageWithImageRequest struct {
	Message              string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MastadonAccount      *MastadonAccount `protobuf:"bytes,2,opt,name=mastadon_account,json=mastadonAccount,proto3" json:"mastadon_account,omitempty"`
	TwitterAccount       *TwitterAccount  `protobuf:"bytes,3,opt,name=twitter_account,json=twitterAccount,proto3" json:"twitter_account,omitempty"`
	Image                string           `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PostMessageWithImageRequest) Reset()         { *m = PostMessageWithImageRequest{} }
func (m *PostMessageWithImageRequest) String() string { return proto.CompactTextString(m) }
func (*PostMessageWithImageRequest) ProtoMessage()    {}
func (*PostMessageWithImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{2}
}

func (m *PostMessageWithImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageWithImageRequest.Unmarshal(m, b)
}
func (m *PostMessageWithImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageWithImageRequest.Marshal(b, m, deterministic)
}
func (m *PostMessageWithImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageWithImageRequest.Merge(m, src)
}
func (m *PostMessageWithImageRequest) XXX_Size() int {
	return xxx_messageInfo_PostMessageWithImageRequest.Size(m)
}
func (m *PostMessageWithImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageWithImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageWithImageRequest proto.InternalMessageInfo

func (m *PostMessageWithImageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostMessageWithImageRequest) GetMastadonAccount() *MastadonAccount {
	if m != nil {
		return m.MastadonAccount
	}
	return nil
}

func (m *PostMessageWithImageRequest) GetTwitterAccount() *TwitterAccount {
	if m != nil {
		return m.TwitterAccount
	}
	return nil
}

func (m *PostMessageWithImageRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type PostMessageWithVideoRequest struct {
	Message              string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MastadonAccount      *MastadonAccount `protobuf:"bytes,2,opt,name=mastadon_account,json=mastadonAccount,proto3" json:"mastadon_account,omitempty"`
	TwitterAccount       *TwitterAccount  `protobuf:"bytes,3,opt,name=twitter_account,json=twitterAccount,proto3" json:"twitter_account,omitempty"`
	Video                string           `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PostMessageWithVideoRequest) Reset()         { *m = PostMessageWithVideoRequest{} }
func (m *PostMessageWithVideoRequest) String() string { return proto.CompactTextString(m) }
func (*PostMessageWithVideoRequest) ProtoMessage()    {}
func (*PostMessageWithVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{3}
}

func (m *PostMessageWithVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageWithVideoRequest.Unmarshal(m, b)
}
func (m *PostMessageWithVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageWithVideoRequest.Marshal(b, m, deterministic)
}
func (m *PostMessageWithVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageWithVideoRequest.Merge(m, src)
}
func (m *PostMessageWithVideoRequest) XXX_Size() int {
	return xxx_messageInfo_PostMessageWithVideoRequest.Size(m)
}
func (m *PostMessageWithVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageWithVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageWithVideoRequest proto.InternalMessageInfo

func (m *PostMessageWithVideoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostMessageWithVideoRequest) GetMastadonAccount() *MastadonAccount {
	if m != nil {
		return m.MastadonAccount
	}
	return nil
}

func (m *PostMessageWithVideoRequest) GetTwitterAccount() *TwitterAccount {
	if m != nil {
		return m.TwitterAccount
	}
	return nil
}

func (m *PostMessageWithVideoRequest) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

type PostMessageResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMessageResponse) Reset()         { *m = PostMessageResponse{} }
func (m *PostMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PostMessageResponse) ProtoMessage()    {}
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{4}
}

func (m *PostMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageResponse.Unmarshal(m, b)
}
func (m *PostMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageResponse.Marshal(b, m, deterministic)
}
func (m *PostMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageResponse.Merge(m, src)
}
func (m *PostMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PostMessageResponse.Size(m)
}
func (m *PostMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageResponse proto.InternalMessageInfo

func (m *PostMessageResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type PostMessagesResponse struct {
	PostMessagesResponses []*PostMessageResponse `protobuf:"bytes,1,rep,name=post_messages_responses,json=postMessagesResponses,proto3" json:"post_messages_responses,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *PostMessagesResponse) Reset()         { *m = PostMessagesResponse{} }
func (m *PostMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*PostMessagesResponse) ProtoMessage()    {}
func (*PostMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{5}
}

func (m *PostMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessagesResponse.Unmarshal(m, b)
}
func (m *PostMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessagesResponse.Marshal(b, m, deterministic)
}
func (m *PostMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessagesResponse.Merge(m, src)
}
func (m *PostMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_PostMessagesResponse.Size(m)
}
func (m *PostMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessagesResponse proto.InternalMessageInfo

func (m *PostMessagesResponse) GetPostMessagesResponses() []*PostMessageResponse {
	if m != nil {
		return m.PostMessagesResponses
	}
	return nil
}

type TwitterAccount struct {
	ConsumerKey          string   `protobuf:"bytes,1,opt,name=consumer_key,json=consumerKey,proto3" json:"consumer_key,omitempty"`
	ConsumerSecret       string   `protobuf:"bytes,2,opt,name=consumer_secret,json=consumerSecret,proto3" json:"consumer_secret,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessSecret         string   `protobuf:"bytes,4,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwitterAccount) Reset()         { *m = TwitterAccount{} }
func (m *TwitterAccount) String() string { return proto.CompactTextString(m) }
func (*TwitterAccount) ProtoMessage()    {}
func (*TwitterAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{6}
}

func (m *TwitterAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwitterAccount.Unmarshal(m, b)
}
func (m *TwitterAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwitterAccount.Marshal(b, m, deterministic)
}
func (m *TwitterAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwitterAccount.Merge(m, src)
}
func (m *TwitterAccount) XXX_Size() int {
	return xxx_messageInfo_TwitterAccount.Size(m)
}
func (m *TwitterAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_TwitterAccount.DiscardUnknown(m)
}

var xxx_messageInfo_TwitterAccount proto.InternalMessageInfo

func (m *TwitterAccount) GetConsumerKey() string {
	if m != nil {
		return m.ConsumerKey
	}
	return ""
}

func (m *TwitterAccount) GetConsumerSecret() string {
	if m != nil {
		return m.ConsumerSecret
	}
	return ""
}

func (m *TwitterAccount) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *TwitterAccount) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

type MastadonAccount struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MastadonAccount) Reset()         { *m = MastadonAccount{} }
func (m *MastadonAccount) String() string { return proto.CompactTextString(m) }
func (*MastadonAccount) ProtoMessage()    {}
func (*MastadonAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{7}
}

func (m *MastadonAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MastadonAccount.Unmarshal(m, b)
}
func (m *MastadonAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MastadonAccount.Marshal(b, m, deterministic)
}
func (m *MastadonAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MastadonAccount.Merge(m, src)
}
func (m *MastadonAccount) XXX_Size() int {
	return xxx_messageInfo_MastadonAccount.Size(m)
}
func (m *MastadonAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MastadonAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MastadonAccount proto.InternalMessageInfo

func (m *MastadonAccount) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *MastadonAccount) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MastadonAccount) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *MastadonAccount) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *MastadonAccount) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MastadonAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BlueSkyAccount struct {
	Handle               string   `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlueSkyAccount) Reset()         { *m = BlueSkyAccount{} }
func (m *BlueSkyAccount) String() string { return proto.CompactTextString(m) }
func (*BlueSkyAccount) ProtoMessage()    {}
func (*BlueSkyAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35be3e5f54b31d0, []int{8}
}

func (m *BlueSkyAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlueSkyAccount.Unmarshal(m, b)
}
func (m *BlueSkyAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlueSkyAccount.Marshal(b, m, deterministic)
}
func (m *BlueSkyAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlueSkyAccount.Merge(m, src)
}
func (m *BlueSkyAccount) XXX_Size() int {
	return xxx_messageInfo_BlueSkyAccount.Size(m)
}
func (m *BlueSkyAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BlueSkyAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BlueSkyAccount proto.InternalMessageInfo

func (m *BlueSkyAccount) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *BlueSkyAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*PostMessageRequest)(nil), "poster.PostMessageRequest")
	proto.RegisterType((*PostMessagesRequest)(nil), "poster.PostMessagesRequest")
	proto.RegisterType((*PostMessageWithImageRequest)(nil), "poster.PostMessageWithImageRequest")
	proto.RegisterType((*PostMessageWithVideoRequest)(nil), "poster.PostMessageWithVideoRequest")
	proto.RegisterType((*PostMessageResponse)(nil), "poster.PostMessageResponse")
	proto.RegisterType((*PostMessagesResponse)(nil), "poster.PostMessagesResponse")
	proto.RegisterType((*TwitterAccount)(nil), "poster.TwitterAccount")
	proto.RegisterType((*MastadonAccount)(nil), "poster.MastadonAccount")
	proto.RegisterType((*BlueSkyAccount)(nil), "poster.BlueSkyAccount")
}

func init() {
	proto.RegisterFile("tweeter.proto", fileDescriptor_f35be3e5f54b31d0)
}

var fileDescriptor_f35be3e5f54b31d0 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x96, 0x49, 0x42, 0xc3, 0x40, 0xa0, 0xda, 0x90, 0xc4, 0x82, 0x1c, 0xa8, 0x73, 0x28, 0x27,
	0xa4, 0xd2, 0x07, 0xa8, 0x1a, 0xf5, 0x82, 0xaa, 0x54, 0x91, 0x89, 0xda, 0xa3, 0xe5, 0xda, 0xa3,
	0x62, 0x81, 0xbd, 0xee, 0xce, 0x12, 0xc4, 0xfb, 0xf4, 0x0d, 0xfa, 0x00, 0xed, 0x33, 0xf4, 0x89,
	0x2a, 0xef, 0x0f, 0xb5, 0x8b, 0xc9, 0xb9, 0xbd, 0xf1, 0x7d, 0x33, 0xfb, 0xcd, 0x37, 0x3b, 0xb3,
	0x18, 0xce, 0xe4, 0x06, 0x51, 0xa2, 0x98, 0xe4, 0x82, 0x4b, 0xce, 0x9a, 0x39, 0x27, 0x89, 0xc2,
	0xfb, 0xee, 0x00, 0xbb, 0xe7, 0x24, 0xef, 0x90, 0x28, 0xfc, 0x82, 0x3e, 0x7e, 0x5d, 0x23, 0x49,
	0xe6, 0xc2, 0xb3, 0x54, 0x33, 0xae, 0x33, 0x72, 0xc6, 0x2d, 0xdf, 0x42, 0x76, 0x0b, 0xcf, 0xd3,
	0x90, 0x64, 0x18, 0xf3, 0x2c, 0x08, 0xa3, 0x88, 0xaf, 0x33, 0xe9, 0x36, 0x46, 0xce, 0xb8, 0x3d,
	0xbd, 0x9a, 0x68, 0xcd, 0xc9, 0x9d, 0x89, 0xbf, 0xd5, 0x61, 0xbf, 0x97, 0x56, 0x09, 0xf6, 0x06,
	0x7a, 0x72, 0x93, 0x48, 0x89, 0x62, 0x27, 0x71, 0xa4, 0x24, 0x2e, 0xad, 0xc4, 0x83, 0x0e, 0x5b,
	0x85, 0xae, 0xac, 0x60, 0xef, 0x47, 0x03, 0xce, 0x4b, 0xae, 0xc9, 0xda, 0xfe, 0x00, 0x17, 0x85,
	0x40, 0x60, 0xcc, 0x06, 0x42, 0xf3, 0xe4, 0x3a, 0xa3, 0xa3, 0x71, 0x7b, 0x3a, 0xb0, 0xf2, 0xfb,
	0x1d, 0xfb, 0xe7, 0xf9, 0x1e, 0x47, 0x6c, 0x09, 0xa3, 0x8a, 0xde, 0x26, 0x91, 0x8b, 0x20, 0x49,
	0x2b, 0xd2, 0x0d, 0x25, 0x7d, 0x53, 0x23, 0xfd, 0x29, 0x91, 0x8b, 0x59, 0x5a, 0xaa, 0x71, 0x9d,
	0x1f, 0x0e, 0x1e, 0x28, 0xf6, 0x98, 0xc4, 0xc8, 0xff, 0x14, 0x3b, 0x7a, 0xb2, 0xd8, 0xc7, 0x22,
	0xf9, 0x50, 0xb1, 0x72, 0x90, 0xbc, 0x5f, 0x0e, 0x0c, 0x9f, 0xb0, 0xfa, 0x8f, 0x2f, 0x00, 0xeb,
	0xc3, 0x89, 0x1a, 0x83, 0x7b, 0xac, 0xcc, 0x69, 0x50, 0xd7, 0x54, 0xb9, 0xeb, 0xff, 0xa0, 0x29,
	0x35, 0x6e, 0xdb, 0x94, 0x02, 0xde, 0xab, 0xca, 0xaa, 0xfb, 0x48, 0x39, 0xcf, 0x08, 0xd9, 0x00,
	0x4e, 0x85, 0xf9, 0x6d, 0x9a, 0xd9, 0x61, 0x6f, 0x09, 0xfd, 0xea, 0xeb, 0x30, 0x67, 0xe6, 0x70,
	0x55, 0xde, 0x30, 0x0a, 0xec, 0x09, 0xfb, 0x40, 0x86, 0xb5, 0x0f, 0x44, 0xe7, 0xf8, 0x17, 0x79,
	0x8d, 0x26, 0x79, 0xdf, 0x1c, 0xe8, 0x56, 0x1b, 0x63, 0x2f, 0xa0, 0x13, 0xf1, 0x8c, 0xd6, 0x29,
	0x8a, 0x60, 0x89, 0x5b, 0xe3, 0xaf, 0x6d, 0xb9, 0xf7, 0xb8, 0x65, 0x2f, 0xa1, 0xb7, 0x4b, 0x21,
	0x8c, 0x04, 0xea, 0xfb, 0x6e, 0xf9, 0x5d, 0x4b, 0xcf, 0x15, 0x5b, 0x68, 0x85, 0x51, 0x84, 0x44,
	0x81, 0xe4, 0x4b, 0xcc, 0xd4, 0x95, 0xb6, 0xfc, 0xb6, 0xe6, 0x1e, 0x0a, 0x8a, 0xdd, 0xc0, 0x99,
	0x49, 0x31, 0x4a, 0xfa, 0xfe, 0xcc, 0x39, 0xad, 0xe3, 0xfd, 0x74, 0xa0, 0xf7, 0xd7, 0x08, 0xd9,
	0x25, 0x34, 0x09, 0xc5, 0x23, 0x0a, 0xe3, 0xd0, 0x20, 0x36, 0x84, 0x56, 0xb4, 0x4a, 0x30, 0x93,
	0x41, 0x12, 0x1b, 0x5b, 0xa7, 0x9a, 0x98, 0xc5, 0x45, 0x35, 0x13, 0x34, 0xd5, 0xb4, 0xa3, 0x8e,
	0x26, 0x0f, 0xb8, 0x3e, 0xde, 0x77, 0xdd, 0x87, 0x13, 0x4c, 0xc3, 0x64, 0xe5, 0x9e, 0xe8, 0x69,
	0x2b, 0x50, 0x8c, 0x35, 0x0f, 0x89, 0x36, 0x5c, 0xc4, 0x6e, 0x53, 0x57, 0xb6, 0xd8, 0x7b, 0x07,
	0xdd, 0xdb, 0xd5, 0x1a, 0xe7, 0xcb, 0x6d, 0xa9, 0x81, 0x45, 0x98, 0xc5, 0x2b, 0xbb, 0x02, 0x06,
	0x55, 0x54, 0x1a, 0x55, 0x95, 0xe9, 0x1c, 0x9a, 0xf7, 0x6a, 0xc8, 0x6c, 0x06, 0x9d, 0xf2, 0x9a,
	0xb0, 0xba, 0xe9, 0xdb, 0xbf, 0xd6, 0xc1, 0x75, 0x7d, 0x50, 0x6f, 0xc1, 0xe7, 0xa6, 0xfa, 0xaa,
	0xbc, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x37, 0xb6, 0x34, 0x66, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PosterClient is the client API for Poster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PosterClient interface {
	PostMessages(ctx context.Context, in *PostMessagesRequest, opts ...grpc.CallOption) (*PostMessagesResponse, error)
}

type posterClient struct {
	cc grpc.ClientConnInterface
}

func NewPosterClient(cc grpc.ClientConnInterface) PosterClient {
	return &posterClient{cc}
}

func (c *posterClient) PostMessages(ctx context.Context, in *PostMessagesRequest, opts ...grpc.CallOption) (*PostMessagesResponse, error) {
	out := new(PostMessagesResponse)
	err := c.cc.Invoke(ctx, "/poster.Poster/PostMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PosterServer is the server API for Poster service.
type PosterServer interface {
	PostMessages(context.Context, *PostMessagesRequest) (*PostMessagesResponse, error)
}

// UnimplementedPosterServer can be embedded to have forward compatible implementations.
type UnimplementedPosterServer struct {
}

func (*UnimplementedPosterServer) PostMessages(ctx context.Context, req *PostMessagesRequest) (*PostMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessages not implemented")
}

func RegisterPosterServer(s *grpc.Server, srv PosterServer) {
	s.RegisterService(&_Poster_serviceDesc, srv)
}

func _Poster_PostMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosterServer).PostMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poster.Poster/PostMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosterServer).PostMessages(ctx, req.(*PostMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "poster.Poster",
	HandlerType: (*PosterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostMessages",
			Handler:    _Poster_PostMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tweeter.proto",
}
