// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bgpsql.proto

package bgpsql

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressFamily int32

const (
	AddressFamily_IPV6 AddressFamily = 0
	AddressFamily_IPV4 AddressFamily = 1
)

var AddressFamily_name = map[int32]string{
	0: "IPV6",
	1: "IPV4",
}

var AddressFamily_value = map[string]int32{
	"IPV6": 0,
	"IPV4": 1,
}

func (x AddressFamily) String() string {
	return proto.EnumName(AddressFamily_name, int32(x))
}

func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{0}
}

// graph requests determined by what time period
// I am graphing for.
type MovementRequest_TimePeriod int32

const (
	MovementRequest_WEEK     MovementRequest_TimePeriod = 0
	MovementRequest_MONTH    MovementRequest_TimePeriod = 1
	MovementRequest_SIXMONTH MovementRequest_TimePeriod = 2
	MovementRequest_ANNUAL   MovementRequest_TimePeriod = 3
)

var MovementRequest_TimePeriod_name = map[int32]string{
	0: "WEEK",
	1: "MONTH",
	2: "SIXMONTH",
	3: "ANNUAL",
}

var MovementRequest_TimePeriod_value = map[string]int32{
	"WEEK":     0,
	"MONTH":    1,
	"SIXMONTH": 2,
	"ANNUAL":   3,
}

func (x MovementRequest_TimePeriod) String() string {
	return proto.EnumName(MovementRequest_TimePeriod_name, int32(x))
}

func (MovementRequest_TimePeriod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{21, 0}
}

type Values struct {
	// Values holds the data required to update the database every five minutes.
	Time                 uint64          `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	PrefixCount          *PrefixCount    `protobuf:"bytes,2,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	Peers                *PeerCount      `protobuf:"bytes,3,opt,name=peers,proto3" json:"peers,omitempty"`
	AsCount              *AsCount        `protobuf:"bytes,4,opt,name=as_count,json=asCount,proto3" json:"as_count,omitempty"`
	Masks                *Masks          `protobuf:"bytes,5,opt,name=masks,proto3" json:"masks,omitempty"`
	LargeCommunity       *LargeCommunity `protobuf:"bytes,6,opt,name=large_community,json=largeCommunity,proto3" json:"large_community,omitempty"`
	Roas                 *Roas           `protobuf:"bytes,7,opt,name=roas,proto3" json:"roas,omitempty"`
	Source               string          `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	SampleTime           uint64          `protobuf:"varint,9,opt,name=sample_time,json=sampleTime,proto3" json:"sample_time,omitempty"`
	Quality              string          `protobuf:"bytes,10,opt,name=quality,proto3" json:"quality,omitempty"`
	QualityNote          string          `protobuf:"bytes,11,opt,name=quality_note,json=qualityNote,proto3" json:"quality_note,omitempty"`
	Tweeted              bool            `protobuf:"varint,12,opt,name=tweeted,proto3" json:"tweeted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{0}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Values) GetPrefixCount() *PrefixCount {
	if m != nil {
		return m.PrefixCount
	}
	return nil
}

func (m *Values) GetPeers() *PeerCount {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Values) GetAsCount() *AsCount {
	if m != nil {
		return m.AsCount
	}
	return nil
}

func (m *Values) GetMasks() *Masks {
	if m != nil {
		return m.Masks
	}
	return nil
}

func (m *Values) GetLargeCommunity() *LargeCommunity {
	if m != nil {
		return m.LargeCommunity
	}
	return nil
}

func (m *Values) GetRoas() *Roas {
	if m != nil {
		return m.Roas
	}
	return nil
}

func (m *Values) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Values) GetSampleTime() uint64 {
	if m != nil {
		return m.SampleTime
	}
	return 0
}

func (m *Values) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

func (m *Values) GetQualityNote() string {
	if m != nil {
		return m.QualityNote
	}
	return ""
}

func (m *Values) GetTweeted() bool {
	if m != nil {
		return m.Tweeted
	}
	return false
}

type SampleKey struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Time                 uint64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Quality              string   `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Tweeted              bool     `protobuf:"varint,4,opt,name=tweeted,proto3" json:"tweeted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleKey) Reset()         { *m = SampleKey{} }
func (m *SampleKey) String() string { return proto.CompactTextString(m) }
func (*SampleKey) ProtoMessage()    {}
func (*SampleKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{1}
}

func (m *SampleKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleKey.Unmarshal(m, b)
}
func (m *SampleKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleKey.Marshal(b, m, deterministic)
}
func (m *SampleKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleKey.Merge(m, src)
}
func (m *SampleKey) XXX_Size() int {
	return xxx_messageInfo_SampleKey.Size(m)
}
func (m *SampleKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleKey.DiscardUnknown(m)
}

var xxx_messageInfo_SampleKey proto.InternalMessageInfo

func (m *SampleKey) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SampleKey) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SampleKey) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

func (m *SampleKey) GetTweeted() bool {
	if m != nil {
		return m.Tweeted
	}
	return false
}

type SampleIndexRequest struct {
	SinceTime            uint64   `protobuf:"varint,1,opt,name=since_time,json=sinceTime,proto3" json:"since_time,omitempty"`
	UntilTime            uint64   `protobuf:"varint,2,opt,name=until_time,json=untilTime,proto3" json:"until_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleIndexRequest) Reset()         { *m = SampleIndexRequest{} }
func (m *SampleIndexRequest) String() string { return proto.CompactTextString(m) }
func (*SampleIndexRequest) ProtoMessage()    {}
func (*SampleIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{2}
}

func (m *SampleIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleIndexRequest.Unmarshal(m, b)
}
func (m *SampleIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleIndexRequest.Marshal(b, m, deterministic)
}
func (m *SampleIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleIndexRequest.Merge(m, src)
}
func (m *SampleIndexRequest) XXX_Size() int {
	return xxx_messageInfo_SampleIndexRequest.Size(m)
}
func (m *SampleIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleIndexRequest proto.InternalMessageInfo

func (m *SampleIndexRequest) GetSinceTime() uint64 {
	if m != nil {
		return m.SinceTime
	}
	return 0
}

func (m *SampleIndexRequest) GetUntilTime() uint64 {
	if m != nil {
		return m.UntilTime
	}
	return 0
}

type SampleIndexResponse struct {
	Keys                 []*SampleKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SampleIndexResponse) Reset()         { *m = SampleIndexResponse{} }
func (m *SampleIndexResponse) String() string { return proto.CompactTextString(m) }
func (*SampleIndexResponse) ProtoMessage()    {}
func (*SampleIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{3}
}

func (m *SampleIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleIndexResponse.Unmarshal(m, b)
}
func (m *SampleIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleIndexResponse.Marshal(b, m, deterministic)
}
func (m *SampleIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleIndexResponse.Merge(m, src)
}
func (m *SampleIndexResponse) XXX_Size() int {
	return xxx_messageInfo_SampleIndexResponse.Size(m)
}
func (m *SampleIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SampleIndexResponse proto.InternalMessageInfo

func (m *SampleIndexResponse) GetKeys() []*SampleKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type SampleBatchRequest struct {
	Keys                 []*SampleKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SampleBatchRequest) Reset()         { *m = SampleBatchRequest{} }
func (m *SampleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*SampleBatchRequest) ProtoMessage()    {}
func (*SampleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{4}
}

func (m *SampleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleBatchRequest.Unmarshal(m, b)
}
func (m *SampleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleBatchRequest.Marshal(b, m, deterministic)
}
func (m *SampleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleBatchRequest.Merge(m, src)
}
func (m *SampleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_SampleBatchRequest.Size(m)
}
func (m *SampleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleBatchRequest proto.InternalMessageInfo

func (m *SampleBatchRequest) GetKeys() []*SampleKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type SampleBatchResponse struct {
	Samples              []*Values `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SampleBatchResponse) Reset()         { *m = SampleBatchResponse{} }
func (m *SampleBatchResponse) String() string { return proto.CompactTextString(m) }
func (*SampleBatchResponse) ProtoMessage()    {}
func (*SampleBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{5}
}

func (m *SampleBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleBatchResponse.Unmarshal(m, b)
}
func (m *SampleBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleBatchResponse.Marshal(b, m, deterministic)
}
func (m *SampleBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleBatchResponse.Merge(m, src)
}
func (m *SampleBatchResponse) XXX_Size() int {
	return xxx_messageInfo_SampleBatchResponse.Size(m)
}
func (m *SampleBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SampleBatchResponse proto.InternalMessageInfo

func (m *SampleBatchResponse) GetSamples() []*Values {
	if m != nil {
		return m.Samples
	}
	return nil
}

type ListOfValues struct {
	Values               []*Values `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListOfValues) Reset()         { *m = ListOfValues{} }
func (m *ListOfValues) String() string { return proto.CompactTextString(m) }
func (*ListOfValues) ProtoMessage()    {}
func (*ListOfValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{6}
}

func (m *ListOfValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfValues.Unmarshal(m, b)
}
func (m *ListOfValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfValues.Marshal(b, m, deterministic)
}
func (m *ListOfValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfValues.Merge(m, src)
}
func (m *ListOfValues) XXX_Size() int {
	return xxx_messageInfo_ListOfValues.Size(m)
}
func (m *ListOfValues) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfValues.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfValues proto.InternalMessageInfo

func (m *ListOfValues) GetValues() []*Values {
	if m != nil {
		return m.Values
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PrefixCountResponse struct {
	// Used to formulate a tweet every six hours with
	// the current status, plus compared to both 6 hours ago
	// and a week ago. Contains count of /24 and /48.
	Active_4             uint32   `protobuf:"varint,1,opt,name=active_4,json=active4,proto3" json:"active_4,omitempty"`
	Active_6             uint32   `protobuf:"varint,2,opt,name=active_6,json=active6,proto3" json:"active_6,omitempty"`
	Sixhoursv4           uint32   `protobuf:"varint,3,opt,name=sixhoursv4,proto3" json:"sixhoursv4,omitempty"`
	Sixhoursv6           uint32   `protobuf:"varint,4,opt,name=sixhoursv6,proto3" json:"sixhoursv6,omitempty"`
	Weekagov4            uint32   `protobuf:"varint,5,opt,name=weekagov4,proto3" json:"weekagov4,omitempty"`
	Weekagov6            uint32   `protobuf:"varint,6,opt,name=weekagov6,proto3" json:"weekagov6,omitempty"`
	Slash24              uint32   `protobuf:"varint,7,opt,name=slash24,proto3" json:"slash24,omitempty"`
	Slash48              uint32   `protobuf:"varint,8,opt,name=slash48,proto3" json:"slash48,omitempty"`
	Time                 uint64   `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrefixCountResponse) Reset()         { *m = PrefixCountResponse{} }
func (m *PrefixCountResponse) String() string { return proto.CompactTextString(m) }
func (*PrefixCountResponse) ProtoMessage()    {}
func (*PrefixCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{8}
}

func (m *PrefixCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixCountResponse.Unmarshal(m, b)
}
func (m *PrefixCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixCountResponse.Marshal(b, m, deterministic)
}
func (m *PrefixCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixCountResponse.Merge(m, src)
}
func (m *PrefixCountResponse) XXX_Size() int {
	return xxx_messageInfo_PrefixCountResponse.Size(m)
}
func (m *PrefixCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixCountResponse proto.InternalMessageInfo

func (m *PrefixCountResponse) GetActive_4() uint32 {
	if m != nil {
		return m.Active_4
	}
	return 0
}

func (m *PrefixCountResponse) GetActive_6() uint32 {
	if m != nil {
		return m.Active_6
	}
	return 0
}

func (m *PrefixCountResponse) GetSixhoursv4() uint32 {
	if m != nil {
		return m.Sixhoursv4
	}
	return 0
}

func (m *PrefixCountResponse) GetSixhoursv6() uint32 {
	if m != nil {
		return m.Sixhoursv6
	}
	return 0
}

func (m *PrefixCountResponse) GetWeekagov4() uint32 {
	if m != nil {
		return m.Weekagov4
	}
	return 0
}

func (m *PrefixCountResponse) GetWeekagov6() uint32 {
	if m != nil {
		return m.Weekagov6
	}
	return 0
}

func (m *PrefixCountResponse) GetSlash24() uint32 {
	if m != nil {
		return m.Slash24
	}
	return 0
}

func (m *PrefixCountResponse) GetSlash48() uint32 {
	if m != nil {
		return m.Slash48
	}
	return 0
}

func (m *PrefixCountResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type AsnamesRequest struct {
	AsnNames             []*AsnName `protobuf:"bytes,1,rep,name=asn_names,json=asnNames,proto3" json:"asn_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AsnamesRequest) Reset()         { *m = AsnamesRequest{} }
func (m *AsnamesRequest) String() string { return proto.CompactTextString(m) }
func (*AsnamesRequest) ProtoMessage()    {}
func (*AsnamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{9}
}

func (m *AsnamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnamesRequest.Unmarshal(m, b)
}
func (m *AsnamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnamesRequest.Marshal(b, m, deterministic)
}
func (m *AsnamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnamesRequest.Merge(m, src)
}
func (m *AsnamesRequest) XXX_Size() int {
	return xxx_messageInfo_AsnamesRequest.Size(m)
}
func (m *AsnamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AsnamesRequest proto.InternalMessageInfo

func (m *AsnamesRequest) GetAsnNames() []*AsnName {
	if m != nil {
		return m.AsnNames
	}
	return nil
}

type AsnName struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	AsName               string   `protobuf:"bytes,2,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	AsLocale             string   `protobuf:"bytes,3,opt,name=as_locale,json=asLocale,proto3" json:"as_locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsnName) Reset()         { *m = AsnName{} }
func (m *AsnName) String() string { return proto.CompactTextString(m) }
func (*AsnName) ProtoMessage()    {}
func (*AsnName) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{10}
}

func (m *AsnName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnName.Unmarshal(m, b)
}
func (m *AsnName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnName.Marshal(b, m, deterministic)
}
func (m *AsnName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnName.Merge(m, src)
}
func (m *AsnName) XXX_Size() int {
	return xxx_messageInfo_AsnName.Size(m)
}
func (m *AsnName) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnName.DiscardUnknown(m)
}

var xxx_messageInfo_AsnName proto.InternalMessageInfo

func (m *AsnName) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

func (m *AsnName) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *AsnName) GetAsLocale() string {
	if m != nil {
		return m.AsLocale
	}
	return ""
}

type GetAsnameRequest struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAsnameRequest) Reset()         { *m = GetAsnameRequest{} }
func (m *GetAsnameRequest) String() string { return proto.CompactTextString(m) }
func (*GetAsnameRequest) ProtoMessage()    {}
func (*GetAsnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{11}
}

func (m *GetAsnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAsnameRequest.Unmarshal(m, b)
}
func (m *GetAsnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAsnameRequest.Marshal(b, m, deterministic)
}
func (m *GetAsnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAsnameRequest.Merge(m, src)
}
func (m *GetAsnameRequest) XXX_Size() int {
	return xxx_messageInfo_GetAsnameRequest.Size(m)
}
func (m *GetAsnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAsnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAsnameRequest proto.InternalMessageInfo

func (m *GetAsnameRequest) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

type GetAsnameResponse struct {
	AsName               string   `protobuf:"bytes,1,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	AsLocale             string   `protobuf:"bytes,2,opt,name=as_locale,json=asLocale,proto3" json:"as_locale,omitempty"`
	Exists               bool     `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAsnameResponse) Reset()         { *m = GetAsnameResponse{} }
func (m *GetAsnameResponse) String() string { return proto.CompactTextString(m) }
func (*GetAsnameResponse) ProtoMessage()    {}
func (*GetAsnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{12}
}

func (m *GetAsnameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAsnameResponse.Unmarshal(m, b)
}
func (m *GetAsnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAsnameResponse.Marshal(b, m, deterministic)
}
func (m *GetAsnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAsnameResponse.Merge(m, src)
}
func (m *GetAsnameResponse) XXX_Size() int {
	return xxx_messageInfo_GetAsnameResponse.Size(m)
}
func (m *GetAsnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAsnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAsnameResponse proto.InternalMessageInfo

func (m *GetAsnameResponse) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *GetAsnameResponse) GetAsLocale() string {
	if m != nil {
		return m.AsLocale
	}
	return ""
}

func (m *GetAsnameResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type GetAsnamesResponse struct {
	Asnumnames           []*AsnumberAsnames `protobuf:"bytes,1,rep,name=asnumnames,proto3" json:"asnumnames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAsnamesResponse) Reset()         { *m = GetAsnamesResponse{} }
func (m *GetAsnamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAsnamesResponse) ProtoMessage()    {}
func (*GetAsnamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{13}
}

func (m *GetAsnamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAsnamesResponse.Unmarshal(m, b)
}
func (m *GetAsnamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAsnamesResponse.Marshal(b, m, deterministic)
}
func (m *GetAsnamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAsnamesResponse.Merge(m, src)
}
func (m *GetAsnamesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAsnamesResponse.Size(m)
}
func (m *GetAsnamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAsnamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAsnamesResponse proto.InternalMessageInfo

func (m *GetAsnamesResponse) GetAsnumnames() []*AsnumberAsnames {
	if m != nil {
		return m.Asnumnames
	}
	return nil
}

type AsnumberAsnames struct {
	AsNumber             uint32   `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	AsName               string   `protobuf:"bytes,2,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	AsLocale             string   `protobuf:"bytes,3,opt,name=as_locale,json=asLocale,proto3" json:"as_locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsnumberAsnames) Reset()         { *m = AsnumberAsnames{} }
func (m *AsnumberAsnames) String() string { return proto.CompactTextString(m) }
func (*AsnumberAsnames) ProtoMessage()    {}
func (*AsnumberAsnames) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{14}
}

func (m *AsnumberAsnames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsnumberAsnames.Unmarshal(m, b)
}
func (m *AsnumberAsnames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsnumberAsnames.Marshal(b, m, deterministic)
}
func (m *AsnumberAsnames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsnumberAsnames.Merge(m, src)
}
func (m *AsnumberAsnames) XXX_Size() int {
	return xxx_messageInfo_AsnumberAsnames.Size(m)
}
func (m *AsnumberAsnames) XXX_DiscardUnknown() {
	xxx_messageInfo_AsnumberAsnames.DiscardUnknown(m)
}

var xxx_messageInfo_AsnumberAsnames proto.InternalMessageInfo

func (m *AsnumberAsnames) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

func (m *AsnumberAsnames) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *AsnumberAsnames) GetAsLocale() string {
	if m != nil {
		return m.AsLocale
	}
	return ""
}

type PieSubnetsResponse struct {
	// Used to create a pie graph showing the percentage
	// that each subnet is using from the complete total.
	V4Total              uint32   `protobuf:"varint,1,opt,name=v4_total,json=v4Total,proto3" json:"v4_total,omitempty"`
	V6Total              uint32   `protobuf:"varint,2,opt,name=v6_total,json=v6Total,proto3" json:"v6_total,omitempty"`
	Masks                *Masks   `protobuf:"bytes,3,opt,name=masks,proto3" json:"masks,omitempty"`
	Time                 uint64   `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieSubnetsResponse) Reset()         { *m = PieSubnetsResponse{} }
func (m *PieSubnetsResponse) String() string { return proto.CompactTextString(m) }
func (*PieSubnetsResponse) ProtoMessage()    {}
func (*PieSubnetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{15}
}

func (m *PieSubnetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieSubnetsResponse.Unmarshal(m, b)
}
func (m *PieSubnetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieSubnetsResponse.Marshal(b, m, deterministic)
}
func (m *PieSubnetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieSubnetsResponse.Merge(m, src)
}
func (m *PieSubnetsResponse) XXX_Size() int {
	return xxx_messageInfo_PieSubnetsResponse.Size(m)
}
func (m *PieSubnetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieSubnetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieSubnetsResponse proto.InternalMessageInfo

func (m *PieSubnetsResponse) GetV4Total() uint32 {
	if m != nil {
		return m.V4Total
	}
	return 0
}

func (m *PieSubnetsResponse) GetV6Total() uint32 {
	if m != nil {
		return m.V6Total
	}
	return 0
}

func (m *PieSubnetsResponse) GetMasks() *Masks {
	if m != nil {
		return m.Masks
	}
	return nil
}

func (m *PieSubnetsResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MovementTotalsResponse struct {
	// Used to create a graph showing table movement for the
	// given time period.
	Values               []*V4V6Time `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MovementTotalsResponse) Reset()         { *m = MovementTotalsResponse{} }
func (m *MovementTotalsResponse) String() string { return proto.CompactTextString(m) }
func (*MovementTotalsResponse) ProtoMessage()    {}
func (*MovementTotalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{16}
}

func (m *MovementTotalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovementTotalsResponse.Unmarshal(m, b)
}
func (m *MovementTotalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovementTotalsResponse.Marshal(b, m, deterministic)
}
func (m *MovementTotalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovementTotalsResponse.Merge(m, src)
}
func (m *MovementTotalsResponse) XXX_Size() int {
	return xxx_messageInfo_MovementTotalsResponse.Size(m)
}
func (m *MovementTotalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovementTotalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovementTotalsResponse proto.InternalMessageInfo

func (m *MovementTotalsResponse) GetValues() []*V4V6Time {
	if m != nil {
		return m.Values
	}
	return nil
}

type V4V6Time struct {
	V4Values             uint32   `protobuf:"varint,1,opt,name=v4_values,json=v4Values,proto3" json:"v4_values,omitempty"`
	V6Values             uint32   `protobuf:"varint,2,opt,name=v6_values,json=v6Values,proto3" json:"v6_values,omitempty"`
	Time                 uint64   `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *V4V6Time) Reset()         { *m = V4V6Time{} }
func (m *V4V6Time) String() string { return proto.CompactTextString(m) }
func (*V4V6Time) ProtoMessage()    {}
func (*V4V6Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{17}
}

func (m *V4V6Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_V4V6Time.Unmarshal(m, b)
}
func (m *V4V6Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_V4V6Time.Marshal(b, m, deterministic)
}
func (m *V4V6Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_V4V6Time.Merge(m, src)
}
func (m *V4V6Time) XXX_Size() int {
	return xxx_messageInfo_V4V6Time.Size(m)
}
func (m *V4V6Time) XXX_DiscardUnknown() {
	xxx_messageInfo_V4V6Time.DiscardUnknown(m)
}

var xxx_messageInfo_V4V6Time proto.InternalMessageInfo

func (m *V4V6Time) GetV4Values() uint32 {
	if m != nil {
		return m.V4Values
	}
	return 0
}

func (m *V4V6Time) GetV6Values() uint32 {
	if m != nil {
		return m.V6Values
	}
	return 0
}

func (m *V4V6Time) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Timestamp struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{18}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Result struct {
	// Bool stating whether the update was a success or not.
	// Ragerdless of result, we can check that via the returned result.
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{19}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type AsCount struct {
	// as_count will hold the total amount of unique ASs.
	// Total number of unique IPv4 source AS numbers.
	As4 uint32 `protobuf:"varint,1,opt,name=as4,proto3" json:"as4,omitempty"`
	// Total number of unique IPv6 source AS numbers.
	As6 uint32 `protobuf:"varint,2,opt,name=as6,proto3" json:"as6,omitempty"`
	// Total unique source AS numbers
	As10 uint32 `protobuf:"varint,3,opt,name=as10,proto3" json:"as10,omitempty"`
	// IPv4-only source AS.
	As4Only uint32 `protobuf:"varint,4,opt,name=as4_only,json=as4Only,proto3" json:"as4_only,omitempty"`
	// IPv6-only source AS.
	As6Only uint32 `protobuf:"varint,5,opt,name=as6_only,json=as6Only,proto3" json:"as6_only,omitempty"`
	// Unique AS originating both IPv4 and IPv6
	AsBoth               uint32   `protobuf:"varint,6,opt,name=as_both,json=asBoth,proto3" json:"as_both,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsCount) Reset()         { *m = AsCount{} }
func (m *AsCount) String() string { return proto.CompactTextString(m) }
func (*AsCount) ProtoMessage()    {}
func (*AsCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{20}
}

func (m *AsCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsCount.Unmarshal(m, b)
}
func (m *AsCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsCount.Marshal(b, m, deterministic)
}
func (m *AsCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsCount.Merge(m, src)
}
func (m *AsCount) XXX_Size() int {
	return xxx_messageInfo_AsCount.Size(m)
}
func (m *AsCount) XXX_DiscardUnknown() {
	xxx_messageInfo_AsCount.DiscardUnknown(m)
}

var xxx_messageInfo_AsCount proto.InternalMessageInfo

func (m *AsCount) GetAs4() uint32 {
	if m != nil {
		return m.As4
	}
	return 0
}

func (m *AsCount) GetAs6() uint32 {
	if m != nil {
		return m.As6
	}
	return 0
}

func (m *AsCount) GetAs10() uint32 {
	if m != nil {
		return m.As10
	}
	return 0
}

func (m *AsCount) GetAs4Only() uint32 {
	if m != nil {
		return m.As4Only
	}
	return 0
}

func (m *AsCount) GetAs6Only() uint32 {
	if m != nil {
		return m.As6Only
	}
	return 0
}

func (m *AsCount) GetAsBoth() uint32 {
	if m != nil {
		return m.AsBoth
	}
	return 0
}

type MovementRequest struct {
	Period               MovementRequest_TimePeriod `protobuf:"varint,1,opt,name=period,proto3,enum=bgpsql.MovementRequest_TimePeriod" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MovementRequest) Reset()         { *m = MovementRequest{} }
func (m *MovementRequest) String() string { return proto.CompactTextString(m) }
func (*MovementRequest) ProtoMessage()    {}
func (*MovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{21}
}

func (m *MovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovementRequest.Unmarshal(m, b)
}
func (m *MovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovementRequest.Marshal(b, m, deterministic)
}
func (m *MovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovementRequest.Merge(m, src)
}
func (m *MovementRequest) XXX_Size() int {
	return xxx_messageInfo_MovementRequest.Size(m)
}
func (m *MovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovementRequest proto.InternalMessageInfo

func (m *MovementRequest) GetPeriod() MovementRequest_TimePeriod {
	if m != nil {
		return m.Period
	}
	return MovementRequest_WEEK
}

type PeerCount struct {
	// how many peers do I have
	PeerCount_4          uint32   `protobuf:"varint,1,opt,name=peer_count_4,json=peerCount4,proto3" json:"peer_count_4,omitempty"`
	PeerUp_4             uint32   `protobuf:"varint,2,opt,name=peer_up_4,json=peerUp4,proto3" json:"peer_up_4,omitempty"`
	PeerCount_6          uint32   `protobuf:"varint,3,opt,name=peer_count_6,json=peerCount6,proto3" json:"peer_count_6,omitempty"`
	PeerUp_6             uint32   `protobuf:"varint,4,opt,name=peer_up_6,json=peerUp6,proto3" json:"peer_up_6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerCount) Reset()         { *m = PeerCount{} }
func (m *PeerCount) String() string { return proto.CompactTextString(m) }
func (*PeerCount) ProtoMessage()    {}
func (*PeerCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{22}
}

func (m *PeerCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerCount.Unmarshal(m, b)
}
func (m *PeerCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerCount.Marshal(b, m, deterministic)
}
func (m *PeerCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerCount.Merge(m, src)
}
func (m *PeerCount) XXX_Size() int {
	return xxx_messageInfo_PeerCount.Size(m)
}
func (m *PeerCount) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerCount.DiscardUnknown(m)
}

var xxx_messageInfo_PeerCount proto.InternalMessageInfo

func (m *PeerCount) GetPeerCount_4() uint32 {
	if m != nil {
		return m.PeerCount_4
	}
	return 0
}

func (m *PeerCount) GetPeerUp_4() uint32 {
	if m != nil {
		return m.PeerUp_4
	}
	return 0
}

func (m *PeerCount) GetPeerCount_6() uint32 {
	if m != nil {
		return m.PeerCount_6
	}
	return 0
}

func (m *PeerCount) GetPeerUp_6() uint32 {
	if m != nil {
		return m.PeerUp_6
	}
	return 0
}

type PrefixCount struct {
	// prefix counts. Most used info
	Total_4              uint32   `protobuf:"varint,1,opt,name=total_4,json=total4,proto3" json:"total_4,omitempty"`
	Active_4             uint32   `protobuf:"varint,2,opt,name=active_4,json=active4,proto3" json:"active_4,omitempty"`
	Total_6              uint32   `protobuf:"varint,3,opt,name=total_6,json=total6,proto3" json:"total_6,omitempty"`
	Active_6             uint32   `protobuf:"varint,4,opt,name=active_6,json=active6,proto3" json:"active_6,omitempty"`
	Time                 uint64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrefixCount) Reset()         { *m = PrefixCount{} }
func (m *PrefixCount) String() string { return proto.CompactTextString(m) }
func (*PrefixCount) ProtoMessage()    {}
func (*PrefixCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{23}
}

func (m *PrefixCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixCount.Unmarshal(m, b)
}
func (m *PrefixCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixCount.Marshal(b, m, deterministic)
}
func (m *PrefixCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixCount.Merge(m, src)
}
func (m *PrefixCount) XXX_Size() int {
	return xxx_messageInfo_PrefixCount.Size(m)
}
func (m *PrefixCount) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixCount.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixCount proto.InternalMessageInfo

func (m *PrefixCount) GetTotal_4() uint32 {
	if m != nil {
		return m.Total_4
	}
	return 0
}

func (m *PrefixCount) GetActive_4() uint32 {
	if m != nil {
		return m.Active_4
	}
	return 0
}

func (m *PrefixCount) GetTotal_6() uint32 {
	if m != nil {
		return m.Total_6
	}
	return 0
}

func (m *PrefixCount) GetActive_6() uint32 {
	if m != nil {
		return m.Active_6
	}
	return 0
}

func (m *PrefixCount) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Masks struct {
	// how many subnets of each mask is active
	V4_08                uint32   `protobuf:"varint,1,opt,name=v4_08,json=v408,proto3" json:"v4_08,omitempty"`
	V4_09                uint32   `protobuf:"varint,2,opt,name=v4_09,json=v409,proto3" json:"v4_09,omitempty"`
	V4_10                uint32   `protobuf:"varint,3,opt,name=v4_10,json=v410,proto3" json:"v4_10,omitempty"`
	V4_11                uint32   `protobuf:"varint,4,opt,name=v4_11,json=v411,proto3" json:"v4_11,omitempty"`
	V4_12                uint32   `protobuf:"varint,5,opt,name=v4_12,json=v412,proto3" json:"v4_12,omitempty"`
	V4_13                uint32   `protobuf:"varint,6,opt,name=v4_13,json=v413,proto3" json:"v4_13,omitempty"`
	V4_14                uint32   `protobuf:"varint,7,opt,name=v4_14,json=v414,proto3" json:"v4_14,omitempty"`
	V4_15                uint32   `protobuf:"varint,8,opt,name=v4_15,json=v415,proto3" json:"v4_15,omitempty"`
	V4_16                uint32   `protobuf:"varint,9,opt,name=v4_16,json=v416,proto3" json:"v4_16,omitempty"`
	V4_17                uint32   `protobuf:"varint,10,opt,name=v4_17,json=v417,proto3" json:"v4_17,omitempty"`
	V4_18                uint32   `protobuf:"varint,11,opt,name=v4_18,json=v418,proto3" json:"v4_18,omitempty"`
	V4_19                uint32   `protobuf:"varint,12,opt,name=v4_19,json=v419,proto3" json:"v4_19,omitempty"`
	V4_20                uint32   `protobuf:"varint,13,opt,name=v4_20,json=v420,proto3" json:"v4_20,omitempty"`
	V4_21                uint32   `protobuf:"varint,14,opt,name=v4_21,json=v421,proto3" json:"v4_21,omitempty"`
	V4_22                uint32   `protobuf:"varint,15,opt,name=v4_22,json=v422,proto3" json:"v4_22,omitempty"`
	V4_23                uint32   `protobuf:"varint,16,opt,name=v4_23,json=v423,proto3" json:"v4_23,omitempty"`
	V4_24                uint32   `protobuf:"varint,17,opt,name=v4_24,json=v424,proto3" json:"v4_24,omitempty"`
	V6_08                uint32   `protobuf:"varint,18,opt,name=v6_08,json=v608,proto3" json:"v6_08,omitempty"`
	V6_09                uint32   `protobuf:"varint,19,opt,name=v6_09,json=v609,proto3" json:"v6_09,omitempty"`
	V6_10                uint32   `protobuf:"varint,20,opt,name=v6_10,json=v610,proto3" json:"v6_10,omitempty"`
	V6_11                uint32   `protobuf:"varint,21,opt,name=v6_11,json=v611,proto3" json:"v6_11,omitempty"`
	V6_12                uint32   `protobuf:"varint,22,opt,name=v6_12,json=v612,proto3" json:"v6_12,omitempty"`
	V6_13                uint32   `protobuf:"varint,23,opt,name=v6_13,json=v613,proto3" json:"v6_13,omitempty"`
	V6_14                uint32   `protobuf:"varint,24,opt,name=v6_14,json=v614,proto3" json:"v6_14,omitempty"`
	V6_15                uint32   `protobuf:"varint,25,opt,name=v6_15,json=v615,proto3" json:"v6_15,omitempty"`
	V6_16                uint32   `protobuf:"varint,26,opt,name=v6_16,json=v616,proto3" json:"v6_16,omitempty"`
	V6_17                uint32   `protobuf:"varint,27,opt,name=v6_17,json=v617,proto3" json:"v6_17,omitempty"`
	V6_18                uint32   `protobuf:"varint,28,opt,name=v6_18,json=v618,proto3" json:"v6_18,omitempty"`
	V6_19                uint32   `protobuf:"varint,29,opt,name=v6_19,json=v619,proto3" json:"v6_19,omitempty"`
	V6_20                uint32   `protobuf:"varint,30,opt,name=v6_20,json=v620,proto3" json:"v6_20,omitempty"`
	V6_21                uint32   `protobuf:"varint,31,opt,name=v6_21,json=v621,proto3" json:"v6_21,omitempty"`
	V6_22                uint32   `protobuf:"varint,32,opt,name=v6_22,json=v622,proto3" json:"v6_22,omitempty"`
	V6_23                uint32   `protobuf:"varint,33,opt,name=v6_23,json=v623,proto3" json:"v6_23,omitempty"`
	V6_24                uint32   `protobuf:"varint,34,opt,name=v6_24,json=v624,proto3" json:"v6_24,omitempty"`
	V6_25                uint32   `protobuf:"varint,35,opt,name=v6_25,json=v625,proto3" json:"v6_25,omitempty"`
	V6_26                uint32   `protobuf:"varint,36,opt,name=v6_26,json=v626,proto3" json:"v6_26,omitempty"`
	V6_27                uint32   `protobuf:"varint,37,opt,name=v6_27,json=v627,proto3" json:"v6_27,omitempty"`
	V6_28                uint32   `protobuf:"varint,38,opt,name=v6_28,json=v628,proto3" json:"v6_28,omitempty"`
	V6_29                uint32   `protobuf:"varint,39,opt,name=v6_29,json=v629,proto3" json:"v6_29,omitempty"`
	V6_30                uint32   `protobuf:"varint,40,opt,name=v6_30,json=v630,proto3" json:"v6_30,omitempty"`
	V6_31                uint32   `protobuf:"varint,41,opt,name=v6_31,json=v631,proto3" json:"v6_31,omitempty"`
	V6_32                uint32   `protobuf:"varint,42,opt,name=v6_32,json=v632,proto3" json:"v6_32,omitempty"`
	V6_33                uint32   `protobuf:"varint,43,opt,name=v6_33,json=v633,proto3" json:"v6_33,omitempty"`
	V6_34                uint32   `protobuf:"varint,44,opt,name=v6_34,json=v634,proto3" json:"v6_34,omitempty"`
	V6_35                uint32   `protobuf:"varint,45,opt,name=v6_35,json=v635,proto3" json:"v6_35,omitempty"`
	V6_36                uint32   `protobuf:"varint,46,opt,name=v6_36,json=v636,proto3" json:"v6_36,omitempty"`
	V6_37                uint32   `protobuf:"varint,47,opt,name=v6_37,json=v637,proto3" json:"v6_37,omitempty"`
	V6_38                uint32   `protobuf:"varint,48,opt,name=v6_38,json=v638,proto3" json:"v6_38,omitempty"`
	V6_39                uint32   `protobuf:"varint,49,opt,name=v6_39,json=v639,proto3" json:"v6_39,omitempty"`
	V6_40                uint32   `protobuf:"varint,50,opt,name=v6_40,json=v640,proto3" json:"v6_40,omitempty"`
	V6_41                uint32   `protobuf:"varint,51,opt,name=v6_41,json=v641,proto3" json:"v6_41,omitempty"`
	V6_42                uint32   `protobuf:"varint,52,opt,name=v6_42,json=v642,proto3" json:"v6_42,omitempty"`
	V6_43                uint32   `protobuf:"varint,53,opt,name=v6_43,json=v643,proto3" json:"v6_43,omitempty"`
	V6_44                uint32   `protobuf:"varint,54,opt,name=v6_44,json=v644,proto3" json:"v6_44,omitempty"`
	V6_45                uint32   `protobuf:"varint,55,opt,name=v6_45,json=v645,proto3" json:"v6_45,omitempty"`
	V6_46                uint32   `protobuf:"varint,56,opt,name=v6_46,json=v646,proto3" json:"v6_46,omitempty"`
	V6_47                uint32   `protobuf:"varint,57,opt,name=v6_47,json=v647,proto3" json:"v6_47,omitempty"`
	V6_48                uint32   `protobuf:"varint,58,opt,name=v6_48,json=v648,proto3" json:"v6_48,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Masks) Reset()         { *m = Masks{} }
func (m *Masks) String() string { return proto.CompactTextString(m) }
func (*Masks) ProtoMessage()    {}
func (*Masks) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{24}
}

func (m *Masks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Masks.Unmarshal(m, b)
}
func (m *Masks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Masks.Marshal(b, m, deterministic)
}
func (m *Masks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Masks.Merge(m, src)
}
func (m *Masks) XXX_Size() int {
	return xxx_messageInfo_Masks.Size(m)
}
func (m *Masks) XXX_DiscardUnknown() {
	xxx_messageInfo_Masks.DiscardUnknown(m)
}

var xxx_messageInfo_Masks proto.InternalMessageInfo

func (m *Masks) GetV4_08() uint32 {
	if m != nil {
		return m.V4_08
	}
	return 0
}

func (m *Masks) GetV4_09() uint32 {
	if m != nil {
		return m.V4_09
	}
	return 0
}

func (m *Masks) GetV4_10() uint32 {
	if m != nil {
		return m.V4_10
	}
	return 0
}

func (m *Masks) GetV4_11() uint32 {
	if m != nil {
		return m.V4_11
	}
	return 0
}

func (m *Masks) GetV4_12() uint32 {
	if m != nil {
		return m.V4_12
	}
	return 0
}

func (m *Masks) GetV4_13() uint32 {
	if m != nil {
		return m.V4_13
	}
	return 0
}

func (m *Masks) GetV4_14() uint32 {
	if m != nil {
		return m.V4_14
	}
	return 0
}

func (m *Masks) GetV4_15() uint32 {
	if m != nil {
		return m.V4_15
	}
	return 0
}

func (m *Masks) GetV4_16() uint32 {
	if m != nil {
		return m.V4_16
	}
	return 0
}

func (m *Masks) GetV4_17() uint32 {
	if m != nil {
		return m.V4_17
	}
	return 0
}

func (m *Masks) GetV4_18() uint32 {
	if m != nil {
		return m.V4_18
	}
	return 0
}

func (m *Masks) GetV4_19() uint32 {
	if m != nil {
		return m.V4_19
	}
	return 0
}

func (m *Masks) GetV4_20() uint32 {
	if m != nil {
		return m.V4_20
	}
	return 0
}

func (m *Masks) GetV4_21() uint32 {
	if m != nil {
		return m.V4_21
	}
	return 0
}

func (m *Masks) GetV4_22() uint32 {
	if m != nil {
		return m.V4_22
	}
	return 0
}

func (m *Masks) GetV4_23() uint32 {
	if m != nil {
		return m.V4_23
	}
	return 0
}

func (m *Masks) GetV4_24() uint32 {
	if m != nil {
		return m.V4_24
	}
	return 0
}

func (m *Masks) GetV6_08() uint32 {
	if m != nil {
		return m.V6_08
	}
	return 0
}

func (m *Masks) GetV6_09() uint32 {
	if m != nil {
		return m.V6_09
	}
	return 0
}

func (m *Masks) GetV6_10() uint32 {
	if m != nil {
		return m.V6_10
	}
	return 0
}

func (m *Masks) GetV6_11() uint32 {
	if m != nil {
		return m.V6_11
	}
	return 0
}

func (m *Masks) GetV6_12() uint32 {
	if m != nil {
		return m.V6_12
	}
	return 0
}

func (m *Masks) GetV6_13() uint32 {
	if m != nil {
		return m.V6_13
	}
	return 0
}

func (m *Masks) GetV6_14() uint32 {
	if m != nil {
		return m.V6_14
	}
	return 0
}

func (m *Masks) GetV6_15() uint32 {
	if m != nil {
		return m.V6_15
	}
	return 0
}

func (m *Masks) GetV6_16() uint32 {
	if m != nil {
		return m.V6_16
	}
	return 0
}

func (m *Masks) GetV6_17() uint32 {
	if m != nil {
		return m.V6_17
	}
	return 0
}

func (m *Masks) GetV6_18() uint32 {
	if m != nil {
		return m.V6_18
	}
	return 0
}

func (m *Masks) GetV6_19() uint32 {
	if m != nil {
		return m.V6_19
	}
	return 0
}

func (m *Masks) GetV6_20() uint32 {
	if m != nil {
		return m.V6_20
	}
	return 0
}

func (m *Masks) GetV6_21() uint32 {
	if m != nil {
		return m.V6_21
	}
	return 0
}

func (m *Masks) GetV6_22() uint32 {
	if m != nil {
		return m.V6_22
	}
	return 0
}

func (m *Masks) GetV6_23() uint32 {
	if m != nil {
		return m.V6_23
	}
	return 0
}

func (m *Masks) GetV6_24() uint32 {
	if m != nil {
		return m.V6_24
	}
	return 0
}

func (m *Masks) GetV6_25() uint32 {
	if m != nil {
		return m.V6_25
	}
	return 0
}

func (m *Masks) GetV6_26() uint32 {
	if m != nil {
		return m.V6_26
	}
	return 0
}

func (m *Masks) GetV6_27() uint32 {
	if m != nil {
		return m.V6_27
	}
	return 0
}

func (m *Masks) GetV6_28() uint32 {
	if m != nil {
		return m.V6_28
	}
	return 0
}

func (m *Masks) GetV6_29() uint32 {
	if m != nil {
		return m.V6_29
	}
	return 0
}

func (m *Masks) GetV6_30() uint32 {
	if m != nil {
		return m.V6_30
	}
	return 0
}

func (m *Masks) GetV6_31() uint32 {
	if m != nil {
		return m.V6_31
	}
	return 0
}

func (m *Masks) GetV6_32() uint32 {
	if m != nil {
		return m.V6_32
	}
	return 0
}

func (m *Masks) GetV6_33() uint32 {
	if m != nil {
		return m.V6_33
	}
	return 0
}

func (m *Masks) GetV6_34() uint32 {
	if m != nil {
		return m.V6_34
	}
	return 0
}

func (m *Masks) GetV6_35() uint32 {
	if m != nil {
		return m.V6_35
	}
	return 0
}

func (m *Masks) GetV6_36() uint32 {
	if m != nil {
		return m.V6_36
	}
	return 0
}

func (m *Masks) GetV6_37() uint32 {
	if m != nil {
		return m.V6_37
	}
	return 0
}

func (m *Masks) GetV6_38() uint32 {
	if m != nil {
		return m.V6_38
	}
	return 0
}

func (m *Masks) GetV6_39() uint32 {
	if m != nil {
		return m.V6_39
	}
	return 0
}

func (m *Masks) GetV6_40() uint32 {
	if m != nil {
		return m.V6_40
	}
	return 0
}

func (m *Masks) GetV6_41() uint32 {
	if m != nil {
		return m.V6_41
	}
	return 0
}

func (m *Masks) GetV6_42() uint32 {
	if m != nil {
		return m.V6_42
	}
	return 0
}

func (m *Masks) GetV6_43() uint32 {
	if m != nil {
		return m.V6_43
	}
	return 0
}

func (m *Masks) GetV6_44() uint32 {
	if m != nil {
		return m.V6_44
	}
	return 0
}

func (m *Masks) GetV6_45() uint32 {
	if m != nil {
		return m.V6_45
	}
	return 0
}

func (m *Masks) GetV6_46() uint32 {
	if m != nil {
		return m.V6_46
	}
	return 0
}

func (m *Masks) GetV6_47() uint32 {
	if m != nil {
		return m.V6_47
	}
	return 0
}

func (m *Masks) GetV6_48() uint32 {
	if m != nil {
		return m.V6_48
	}
	return 0
}

type Response struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Priority             uint32   `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{25}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type LargeCommunity struct {
	// Large Community count (RFC 8092)
	C4                   uint32   `protobuf:"varint,1,opt,name=c4,proto3" json:"c4,omitempty"`
	C6                   uint32   `protobuf:"varint,2,opt,name=c6,proto3" json:"c6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeCommunity) Reset()         { *m = LargeCommunity{} }
func (m *LargeCommunity) String() string { return proto.CompactTextString(m) }
func (*LargeCommunity) ProtoMessage()    {}
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{26}
}

func (m *LargeCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeCommunity.Unmarshal(m, b)
}
func (m *LargeCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeCommunity.Marshal(b, m, deterministic)
}
func (m *LargeCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeCommunity.Merge(m, src)
}
func (m *LargeCommunity) XXX_Size() int {
	return xxx_messageInfo_LargeCommunity.Size(m)
}
func (m *LargeCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_LargeCommunity proto.InternalMessageInfo

func (m *LargeCommunity) GetC4() uint32 {
	if m != nil {
		return m.C4
	}
	return 0
}

func (m *LargeCommunity) GetC6() uint32 {
	if m != nil {
		return m.C6
	}
	return 0
}

type Roas struct {
	// RPKI Route Origin Authorization
	V4Valid              uint32   `protobuf:"varint,1,opt,name=v4_valid,json=v4Valid,proto3" json:"v4_valid,omitempty"`
	V4Invalid            uint32   `protobuf:"varint,2,opt,name=v4_invalid,json=v4Invalid,proto3" json:"v4_invalid,omitempty"`
	V4Unknown            uint32   `protobuf:"varint,3,opt,name=v4_unknown,json=v4Unknown,proto3" json:"v4_unknown,omitempty"`
	V6Valid              uint32   `protobuf:"varint,4,opt,name=v6_valid,json=v6Valid,proto3" json:"v6_valid,omitempty"`
	V6Invalid            uint32   `protobuf:"varint,5,opt,name=v6_invalid,json=v6Invalid,proto3" json:"v6_invalid,omitempty"`
	V6Unknown            uint32   `protobuf:"varint,6,opt,name=v6_unknown,json=v6Unknown,proto3" json:"v6_unknown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Roas) Reset()         { *m = Roas{} }
func (m *Roas) String() string { return proto.CompactTextString(m) }
func (*Roas) ProtoMessage()    {}
func (*Roas) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3cdd74a87c7cfdf, []int{27}
}

func (m *Roas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roas.Unmarshal(m, b)
}
func (m *Roas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roas.Marshal(b, m, deterministic)
}
func (m *Roas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roas.Merge(m, src)
}
func (m *Roas) XXX_Size() int {
	return xxx_messageInfo_Roas.Size(m)
}
func (m *Roas) XXX_DiscardUnknown() {
	xxx_messageInfo_Roas.DiscardUnknown(m)
}

var xxx_messageInfo_Roas proto.InternalMessageInfo

func (m *Roas) GetV4Valid() uint32 {
	if m != nil {
		return m.V4Valid
	}
	return 0
}

func (m *Roas) GetV4Invalid() uint32 {
	if m != nil {
		return m.V4Invalid
	}
	return 0
}

func (m *Roas) GetV4Unknown() uint32 {
	if m != nil {
		return m.V4Unknown
	}
	return 0
}

func (m *Roas) GetV6Valid() uint32 {
	if m != nil {
		return m.V6Valid
	}
	return 0
}

func (m *Roas) GetV6Invalid() uint32 {
	if m != nil {
		return m.V6Invalid
	}
	return 0
}

func (m *Roas) GetV6Unknown() uint32 {
	if m != nil {
		return m.V6Unknown
	}
	return 0
}

func init() {
	proto.RegisterEnum("bgpsql.AddressFamily", AddressFamily_name, AddressFamily_value)
	proto.RegisterEnum("bgpsql.MovementRequest_TimePeriod", MovementRequest_TimePeriod_name, MovementRequest_TimePeriod_value)
	proto.RegisterType((*Values)(nil), "bgpsql.values")
	proto.RegisterType((*SampleKey)(nil), "bgpsql.sample_key")
	proto.RegisterType((*SampleIndexRequest)(nil), "bgpsql.sample_index_request")
	proto.RegisterType((*SampleIndexResponse)(nil), "bgpsql.sample_index_response")
	proto.RegisterType((*SampleBatchRequest)(nil), "bgpsql.sample_batch_request")
	proto.RegisterType((*SampleBatchResponse)(nil), "bgpsql.sample_batch_response")
	proto.RegisterType((*ListOfValues)(nil), "bgpsql.list_of_values")
	proto.RegisterType((*Empty)(nil), "bgpsql.empty")
	proto.RegisterType((*PrefixCountResponse)(nil), "bgpsql.prefix_count_response")
	proto.RegisterType((*AsnamesRequest)(nil), "bgpsql.asnames_request")
	proto.RegisterType((*AsnName)(nil), "bgpsql.asn_name")
	proto.RegisterType((*GetAsnameRequest)(nil), "bgpsql.get_asname_request")
	proto.RegisterType((*GetAsnameResponse)(nil), "bgpsql.get_asname_response")
	proto.RegisterType((*GetAsnamesResponse)(nil), "bgpsql.get_asnames_response")
	proto.RegisterType((*AsnumberAsnames)(nil), "bgpsql.asnumber_asnames")
	proto.RegisterType((*PieSubnetsResponse)(nil), "bgpsql.pie_subnets_response")
	proto.RegisterType((*MovementTotalsResponse)(nil), "bgpsql.movement_totals_response")
	proto.RegisterType((*V4V6Time)(nil), "bgpsql.v4v6time")
	proto.RegisterType((*Timestamp)(nil), "bgpsql.timestamp")
	proto.RegisterType((*Result)(nil), "bgpsql.result")
	proto.RegisterType((*AsCount)(nil), "bgpsql.as_count")
	proto.RegisterType((*MovementRequest)(nil), "bgpsql.movement_request")
	proto.RegisterType((*PeerCount)(nil), "bgpsql.peer_count")
	proto.RegisterType((*PrefixCount)(nil), "bgpsql.prefix_count")
	proto.RegisterType((*Masks)(nil), "bgpsql.masks")
	proto.RegisterType((*Response)(nil), "bgpsql.response")
	proto.RegisterType((*LargeCommunity)(nil), "bgpsql.large_community")
	proto.RegisterType((*Roas)(nil), "bgpsql.roas")
}

func init() {
	proto.RegisterFile("bgpsql.proto", fileDescriptor_d3cdd74a87c7cfdf)
}

var fileDescriptor_d3cdd74a87c7cfdf = []byte{
	// 1863 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x98, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0xc7, 0x43, 0x8a, 0xa2, 0xc8, 0xa3, 0x0f, 0x33, 0x1b, 0x39, 0xde, 0xc8, 0x76, 0xac, 0xc0,
	0xa9, 0xa3, 0xe6, 0xc3, 0x25, 0x81, 0x25, 0x48, 0x3a, 0x33, 0xae, 0xdd, 0xd4, 0x33, 0xf5, 0x34,
	0x95, 0x5d, 0xd4, 0x76, 0x73, 0xd3, 0xc1, 0x40, 0xe4, 0x5a, 0xc2, 0x08, 0x04, 0x68, 0x2e, 0x08,
	0x5b, 0x0f, 0xd0, 0x99, 0x4e, 0xa7, 0x17, 0xcd, 0xdb, 0xf4, 0x05, 0x7a, 0xd1, 0xb7, 0xea, 0xec,
	0xc7, 0x59, 0x00, 0x94, 0xec, 0xe9, 0x4d, 0xaf, 0xc8, 0xfd, 0x9d, 0x3d, 0xbb, 0xe7, 0xbf, 0x9f,
	0x67, 0x01, 0x3b, 0x27, 0xa7, 0x0b, 0xf1, 0x26, 0xb9, 0xbf, 0x58, 0x66, 0x79, 0x46, 0xda, 0xba,
	0xe4, 0xfc, 0x7b, 0x03, 0xda, 0x45, 0x94, 0xac, 0xb8, 0x20, 0x04, 0x5a, 0x79, 0x3c, 0xe7, 0xb4,
	0x71, 0xd8, 0x38, 0x6a, 0x05, 0xea, 0x3f, 0x19, 0xc1, 0xce, 0x62, 0xc9, 0x5f, 0xc7, 0xef, 0xc2,
	0x69, 0xb6, 0x4a, 0x73, 0xda, 0x3c, 0x6c, 0x1c, 0x6d, 0xbb, 0xfb, 0xf7, 0x6d, 0x5b, 0xa5, 0x2d,
	0xd8, 0xd6, 0xa5, 0x1f, 0x64, 0x81, 0x1c, 0xc1, 0xe6, 0x82, 0xf3, 0xa5, 0xa0, 0x1b, 0xca, 0x83,
	0x58, 0x0f, 0xce, 0x97, 0xa6, 0xbe, 0xae, 0x40, 0xbe, 0x81, 0x4e, 0x24, 0x4c, 0xf3, 0x2d, 0x55,
	0xb9, 0x87, 0x95, 0x91, 0x07, 0x5b, 0x91, 0xd0, 0xcd, 0xde, 0x85, 0xcd, 0x79, 0x24, 0xce, 0x05,
	0xdd, 0x54, 0x35, 0x77, 0xb1, 0xa6, 0x82, 0x81, 0xb6, 0x91, 0x47, 0x70, 0x2d, 0x89, 0x96, 0xa7,
	0x3c, 0x9c, 0x66, 0xf3, 0xf9, 0x2a, 0x8d, 0xf3, 0x0b, 0xda, 0x56, 0xd5, 0x6f, 0x60, 0xf5, 0x35,
	0x73, 0xb0, 0xa7, 0xc0, 0x0f, 0x58, 0x26, 0x87, 0xd0, 0x5a, 0x66, 0x91, 0xa0, 0x5b, 0xca, 0x6d,
	0x07, 0xdd, 0x24, 0x0b, 0x94, 0x85, 0x7c, 0x0a, 0x6d, 0x91, 0xad, 0x96, 0x53, 0x4e, 0x3b, 0x87,
	0x8d, 0xa3, 0x6e, 0x60, 0x4a, 0xe4, 0x0e, 0x6c, 0x8b, 0x68, 0xbe, 0x48, 0x78, 0xa8, 0xc6, 0xb2,
	0xab, 0xc6, 0x12, 0x34, 0x7a, 0x21, 0x47, 0x94, 0xc2, 0xd6, 0x9b, 0x55, 0x94, 0xc8, 0xa0, 0x40,
	0x79, 0x62, 0x91, 0x7c, 0x01, 0x3b, 0xe6, 0x6f, 0x98, 0x66, 0x39, 0xa7, 0xdb, 0xca, 0xbc, 0x6d,
	0xd8, 0x71, 0x96, 0x2b, 0xe7, 0xfc, 0x2d, 0xe7, 0x39, 0x9f, 0xd1, 0x9d, 0xc3, 0xc6, 0x51, 0x27,
	0xc0, 0xa2, 0x93, 0x80, 0xe9, 0x24, 0x3c, 0xe7, 0x17, 0x95, 0xe8, 0x1a, 0xb5, 0xe8, 0x70, 0x8a,
	0x9b, 0x95, 0x29, 0xae, 0x04, 0xb4, 0x51, 0x0f, 0xa8, 0xd2, 0x5b, 0xab, 0xde, 0xdb, 0x0b, 0xd8,
	0x37, 0xbd, 0xc5, 0xe9, 0x8c, 0xbf, 0x0b, 0x97, 0xfc, 0xcd, 0x8a, 0x8b, 0x9c, 0xdc, 0x06, 0x10,
	0x71, 0x3a, 0x35, 0xe2, 0xf5, 0x42, 0xea, 0x2a, 0xa2, 0xb4, 0xdf, 0x06, 0x58, 0xa5, 0x79, 0x9c,
	0x84, 0x95, 0x20, 0xba, 0x8a, 0x48, 0xb3, 0xf3, 0x6b, 0xb8, 0xbe, 0xd6, 0xaa, 0x58, 0x64, 0xa9,
	0xe0, 0xe4, 0x1e, 0xb4, 0xce, 0xf9, 0x85, 0xa0, 0x8d, 0xc3, 0x8d, 0xea, 0x5a, 0x2a, 0x05, 0x07,
	0xca, 0xee, 0x3c, 0xb4, 0x61, 0x9d, 0x44, 0xf9, 0xf4, 0xcc, 0x86, 0xf5, 0xbf, 0xfa, 0x3f, 0xb6,
	0x01, 0xa0, 0xbf, 0x09, 0xe0, 0x08, 0xb6, 0xb4, 0x01, 0xdb, 0xd8, 0xc3, 0x36, 0xf4, 0xde, 0x09,
	0xd0, 0xec, 0x8c, 0x61, 0x2f, 0x89, 0x45, 0x1e, 0x66, 0xaf, 0x43, 0xb3, 0xad, 0xee, 0xe1, 0x06,
	0x7b, 0x8f, 0xab, 0xb1, 0x3a, 0x5b, 0xb0, 0xc9, 0xe7, 0x8b, 0xfc, 0xc2, 0xf9, 0xb9, 0x09, 0xd7,
	0xab, 0x1b, 0xab, 0x0c, 0xe3, 0x33, 0xe8, 0x44, 0xd3, 0x3c, 0x2e, 0x78, 0xc8, 0xd4, 0xe0, 0xee,
	0x06, 0x5b, 0xba, 0xcc, 0x2a, 0x26, 0x5f, 0x0d, 0xac, 0x35, 0xf9, 0xe4, 0x73, 0x39, 0x29, 0xef,
	0xce, 0xb2, 0xd5, 0x52, 0x14, 0x4c, 0xcd, 0xf1, 0x6e, 0x50, 0x21, 0x35, 0xbb, 0xaf, 0x66, 0xba,
	0x6a, 0xf7, 0xc9, 0x2d, 0xe8, 0xbe, 0xe5, 0xfc, 0x3c, 0x3a, 0xcd, 0x0a, 0xa6, 0xf6, 0xdd, 0x6e,
	0x50, 0x82, 0xaa, 0xd5, 0x57, 0xdb, 0xac, 0x62, 0xf5, 0xe5, 0x12, 0x12, 0x49, 0x24, 0xce, 0x5c,
	0xa6, 0xf6, 0xd2, 0x6e, 0x80, 0x45, 0x6b, 0x61, 0x63, 0xb5, 0x83, 0xd0, 0xc2, 0xc6, 0x76, 0x91,
	0x76, 0xcb, 0x45, 0xea, 0x3c, 0x82, 0x6b, 0x91, 0x48, 0xa3, 0x39, 0x17, 0x76, 0x52, 0xbf, 0x83,
	0x6e, 0x24, 0xd2, 0x50, 0x41, 0x33, 0xb4, 0x95, 0x83, 0x43, 0x1b, 0x82, 0x4e, 0x24, 0xd2, 0x63,
	0x59, 0xc3, 0xf9, 0x8b, 0x3c, 0x66, 0x34, 0x25, 0x37, 0xa5, 0x6b, 0x98, 0xae, 0xe6, 0x27, 0x7c,
	0x69, 0x06, 0xb2, 0x13, 0x89, 0x63, 0x55, 0x26, 0x37, 0x60, 0x4b, 0x1a, 0x23, 0xb3, 0x42, 0xbb,
	0x41, 0x3b, 0x12, 0xc7, 0xa5, 0x57, 0x92, 0x4d, 0xa3, 0x84, 0x9b, 0xad, 0xd2, 0x89, 0xc4, 0x8f,
	0xaa, 0xec, 0x0c, 0x80, 0x9c, 0xf2, 0x3c, 0xd4, 0x41, 0xda, 0x18, 0x3f, 0xd4, 0x91, 0x33, 0x85,
	0x4f, 0x6a, 0x2e, 0x66, 0x92, 0x2b, 0xfd, 0x37, 0xde, 0xdf, 0x7f, 0xb3, 0xde, 0xbf, 0xdc, 0xf1,
	0xfc, 0x5d, 0x2c, 0x72, 0x7d, 0xe0, 0x76, 0x02, 0x53, 0x72, 0x9e, 0xc3, 0x7e, 0xd9, 0x89, 0x28,
	0x7b, 0x19, 0x03, 0x44, 0x22, 0x5d, 0xcd, 0xab, 0xc3, 0x47, 0x2b, 0xc3, 0xa7, 0x42, 0x44, 0xb7,
	0xa0, 0x52, 0xd7, 0xe1, 0xd0, 0x5b, 0xb7, 0xff, 0x3f, 0x06, 0xf4, 0xaf, 0x0d, 0xd8, 0x5f, 0xc4,
	0x3c, 0x14, 0xab, 0x93, 0x94, 0xe7, 0xa2, 0xb6, 0x09, 0x0a, 0x16, 0xe6, 0x59, 0x1e, 0x25, 0xb8,
	0x09, 0x0a, 0xf6, 0x42, 0x16, 0x95, 0xc9, 0x37, 0x26, 0xb3, 0x09, 0x0a, 0x5f, 0x9b, 0xec, 0xc5,
	0xb1, 0xf1, 0x81, 0x8b, 0x03, 0x57, 0x5e, 0xab, 0xb2, 0xf2, 0x7e, 0x0b, 0x74, 0x9e, 0x15, 0x7c,
	0xce, 0xd3, 0x5c, 0xb7, 0x2c, 0xaa, 0xc7, 0x42, 0x7d, 0x6b, 0xdb, 0xf5, 0x57, 0xb0, 0xc2, 0x97,
	0xde, 0x76, 0x73, 0xff, 0x24, 0x83, 0xd6, 0x4c, 0xca, 0x2e, 0x58, 0x68, 0x1d, 0xd5, 0x60, 0x15,
	0xec, 0x95, 0x3e, 0x2d, 0xa4, 0xd1, 0x47, 0x63, 0xd3, 0x18, 0xfd, 0x57, 0xf5, 0x1b, 0x7a, 0xa3,
	0x12, 0xdf, 0x1d, 0xe8, 0xca, 0x5f, 0x91, 0x47, 0xf3, 0xc5, 0x55, 0x57, 0xb8, 0xf3, 0x00, 0xda,
	0x4b, 0x2e, 0x56, 0x49, 0xae, 0xb6, 0xdc, 0x6a, 0x3a, 0xe5, 0x42, 0x77, 0xdb, 0x09, 0xb0, 0x28,
	0x57, 0x8f, 0xae, 0x83, 0x33, 0xa4, 0x4b, 0xce, 0xcf, 0x8d, 0xf2, 0x72, 0x26, 0x3d, 0xd8, 0x88,
	0x04, 0x1e, 0x3c, 0xf2, 0xaf, 0x26, 0x78, 0xde, 0xc8, 0xbf, 0x32, 0x80, 0x48, 0x0c, 0xfa, 0xe6,
	0x94, 0x51, 0xff, 0xd5, 0xd1, 0x24, 0x58, 0x98, 0xa5, 0xc9, 0x85, 0x39, 0x5d, 0xb6, 0x22, 0xc1,
	0x9e, 0xa5, 0xc9, 0x85, 0x36, 0xf9, 0xda, 0xb4, 0x89, 0x26, 0x5f, 0x99, 0xf4, 0xaa, 0x39, 0xc9,
	0xf2, 0x33, 0x73, 0xaa, 0xb4, 0x23, 0xf1, 0x9b, 0x2c, 0x3f, 0x73, 0xfe, 0xd1, 0x80, 0x9e, 0x9d,
	0x11, 0xdc, 0x68, 0xdf, 0x43, 0x7b, 0xc1, 0x97, 0x71, 0x36, 0x53, 0xe1, 0xed, 0xb9, 0x77, 0xed,
	0xfc, 0xae, 0xd5, 0xbc, 0x2f, 0x6f, 0x9a, 0xe7, 0xaa, 0x6a, 0x60, 0x5c, 0x9c, 0xef, 0x01, 0x4a,
	0x4a, 0x3a, 0xd0, 0xfa, 0xf3, 0x93, 0x27, 0xbf, 0xef, 0x7d, 0x44, 0xba, 0xb0, 0xf9, 0x87, 0x67,
	0xc7, 0x2f, 0x7e, 0xd7, 0x6b, 0x90, 0x1d, 0xe8, 0xfc, 0xe9, 0xe9, 0x4f, 0xba, 0xd4, 0x24, 0x00,
	0xed, 0xc7, 0xc7, 0xc7, 0x2f, 0x1f, 0xff, 0xd8, 0xdb, 0x70, 0xfe, 0xd6, 0x00, 0x28, 0x93, 0x1a,
	0x72, 0x08, 0x3b, 0x65, 0xc9, 0x1e, 0xd3, 0xaa, 0x86, 0xca, 0x60, 0x18, 0x39, 0x80, 0xae, 0xaa,
	0xb1, 0x5a, 0x84, 0x0c, 0x57, 0xa9, 0x04, 0x2f, 0x17, 0x6c, 0xcd, 0xdb, 0xc7, 0xc3, 0xda, 0x7a,
	0xfb, 0x55, 0x6f, 0x3c, 0xab, 0x8d, 0xb7, 0xef, 0xfc, 0xbd, 0x51, 0xcf, 0xd6, 0xe4, 0x18, 0xaa,
	0x25, 0x6b, 0xe3, 0x68, 0xab, 0x22, 0xab, 0x5d, 0x24, 0xcd, 0xfa, 0x45, 0x62, 0x7d, 0xb0, 0x77,
	0xed, 0xe3, 0xd7, 0x6e, 0x98, 0x56, 0xfd, 0x86, 0xc1, 0x65, 0xb7, 0x59, 0x59, 0x76, 0xff, 0xe9,
	0x9a, 0x1d, 0x47, 0x3e, 0x81, 0xcd, 0x82, 0x85, 0xfd, 0xb1, 0x89, 0xa1, 0x55, 0xb0, 0xfe, 0x18,
	0xe1, 0xc4, 0x74, 0x2f, 0xe1, 0xc4, 0xc0, 0x72, 0xf9, 0x14, 0x6c, 0xd0, 0x47, 0x38, 0x30, 0x9d,
	0x4a, 0x38, 0x40, 0xe8, 0x9a, 0x55, 0x23, 0xa1, 0x8b, 0xd0, 0x33, 0x0b, 0x46, 0x42, 0x0f, 0x21,
	0xde, 0x3f, 0x12, 0x32, 0x84, 0x43, 0x73, 0xf5, 0x48, 0x38, 0x44, 0xe8, 0xab, 0x8b, 0x47, 0x43,
	0x1f, 0xe1, 0x48, 0x25, 0x6b, 0x1a, 0x8e, 0x10, 0x8e, 0x55, 0x8a, 0xa6, 0x21, 0x2a, 0x1a, 0x4c,
	0x54, 0x66, 0xa6, 0x21, 0x2a, 0x72, 0xfb, 0x74, 0x17, 0xa1, 0x8b, 0x8a, 0xdc, 0x01, 0xdd, 0xb3,
	0x10, 0x15, 0xb9, 0x2e, 0xbd, 0x66, 0x21, 0x2a, 0x72, 0x3d, 0xda, 0xb3, 0x10, 0x15, 0xb9, 0x8c,
	0x7e, 0x6c, 0xa1, 0x56, 0xe4, 0xcb, 0x41, 0x26, 0x06, 0xfa, 0x66, 0x90, 0x7d, 0x39, 0xc8, 0x9f,
	0x58, 0x38, 0x31, 0x70, 0xd0, 0xa7, 0xfb, 0x08, 0xcd, 0x20, 0xfb, 0x72, 0x90, 0xaf, 0x5b, 0x38,
	0x40, 0xe8, 0xd2, 0x4f, 0x2d, 0x74, 0x11, 0x7a, 0xf4, 0x86, 0x85, 0x1e, 0x42, 0x46, 0xa9, 0x85,
	0x18, 0xd2, 0x60, 0x48, 0x3f, 0xb3, 0x70, 0x88, 0xd0, 0xa7, 0x07, 0x16, 0xfa, 0x08, 0x47, 0xf4,
	0xa6, 0x85, 0x23, 0x84, 0x63, 0x7a, 0xcb, 0x42, 0x54, 0x34, 0x98, 0xd0, 0xdb, 0x16, 0xa2, 0x22,
	0xb7, 0x4f, 0x3f, 0x47, 0xe8, 0xa2, 0x22, 0x77, 0x40, 0xef, 0x58, 0x88, 0x8a, 0x5c, 0x97, 0x1e,
	0x5a, 0x88, 0x8a, 0x5c, 0x8f, 0x7e, 0x61, 0x21, 0x2a, 0x72, 0x19, 0x75, 0x2c, 0x44, 0x45, 0xee,
	0x90, 0xde, 0xb5, 0x10, 0x15, 0xb9, 0x3e, 0xfd, 0xd2, 0x42, 0x54, 0xe4, 0x8e, 0xe8, 0x2f, 0x2c,
	0x44, 0x45, 0xee, 0x98, 0xde, 0xb3, 0x10, 0x15, 0xb9, 0x13, 0xfa, 0x95, 0x85, 0xa8, 0xc8, 0xeb,
	0xd3, 0x23, 0x84, 0x1e, 0x2a, 0xf2, 0x06, 0xf4, 0x97, 0x16, 0xa2, 0x22, 0xcf, 0xa5, 0x5f, 0x5b,
	0x88, 0x8a, 0x3c, 0x8f, 0x7e, 0x63, 0x21, 0x2a, 0xf2, 0x18, 0xfd, 0xd6, 0x42, 0x54, 0xe4, 0x0d,
	0xe9, 0x77, 0x16, 0xa2, 0x22, 0xcf, 0xa7, 0xf7, 0x2d, 0x44, 0x45, 0xde, 0x88, 0xfe, 0xca, 0x42,
	0x54, 0xe4, 0x8d, 0x69, 0xdf, 0x42, 0x54, 0xe4, 0x4d, 0xe8, 0xc0, 0x42, 0x54, 0xc4, 0xfa, 0xd4,
	0x45, 0xc8, 0x50, 0x11, 0x1b, 0x50, 0xcf, 0x42, 0x54, 0xc4, 0x5c, 0xca, 0x2c, 0x44, 0x45, 0xcc,
	0xa3, 0x43, 0x0b, 0x51, 0x11, 0x63, 0xd4, 0xb7, 0x10, 0x15, 0xb1, 0x21, 0x1d, 0x59, 0x88, 0x8a,
	0x98, 0x4f, 0xc7, 0x16, 0xa2, 0x22, 0x36, 0xa2, 0x13, 0x0b, 0x51, 0x11, 0x1b, 0xd3, 0x07, 0x16,
	0x8e, 0x9d, 0x87, 0xd0, 0xb1, 0x77, 0xbe, 0x7c, 0x5a, 0xe5, 0x51, 0xbe, 0xc2, 0x3b, 0xd4, 0x94,
	0xc8, 0x01, 0x74, 0x16, 0xcb, 0x38, 0x5b, 0xca, 0x77, 0x94, 0xb9, 0xb7, 0xb1, 0xec, 0x0c, 0x2e,
	0x3d, 0x48, 0xc9, 0x1e, 0x34, 0xa7, 0x78, 0x2a, 0x37, 0xa7, 0x4c, 0x95, 0xf1, 0x26, 0x6d, 0x4e,
	0x7d, 0xe7, 0x5f, 0x0d, 0xfd, 0x04, 0x35, 0xe9, 0x4e, 0x11, 0x25, 0xf1, 0xac, 0x4c, 0x77, 0x5e,
	0xc9, 0xa2, 0x7c, 0x4e, 0x15, 0x2c, 0x8c, 0x53, 0x6d, 0xd4, 0xbe, 0xdd, 0x82, 0x3d, 0xd5, 0xc0,
	0x98, 0x57, 0xe9, 0x79, 0x9a, 0xbd, 0x4d, 0xcd, 0x91, 0xda, 0x2d, 0xd8, 0x4b, 0x0d, 0x4c, 0xb2,
	0xa4, 0x7d, 0x5b, 0x98, 0x2c, 0x95, 0x0d, 0xfb, 0xb6, 0x61, 0x93, 0xf2, 0x17, 0x7e, 0xb5, 0x61,
	0xdf, 0x36, 0xdc, 0x46, 0xb3, 0x69, 0xf8, 0xeb, 0x2f, 0x61, 0x2f, 0x9a, 0xcd, 0x96, 0x5c, 0x88,
	0xf0, 0x75, 0x34, 0x8f, 0x93, 0x0b, 0x79, 0xa5, 0x3e, 0x7d, 0xfe, 0xca, 0xef, 0x7d, 0x64, 0xfe,
	0xb1, 0x5e, 0xc3, 0xfd, 0x67, 0x1b, 0x3a, 0x27, 0xa7, 0x8b, 0x30, 0x4e, 0x5f, 0x67, 0xe4, 0x5b,
	0x80, 0x68, 0x36, 0x0b, 0x93, 0x28, 0x97, 0x97, 0xf9, 0xda, 0x0b, 0xe9, 0xc0, 0x96, 0x4d, 0x1e,
	0xf3, 0x08, 0x7a, 0x32, 0xa7, 0xad, 0x5d, 0x75, 0x36, 0xa1, 0x53, 0x6f, 0xa8, 0x83, 0xdb, 0x57,
	0x7d, 0xa1, 0x28, 0x13, 0xb7, 0x21, 0xf4, 0x56, 0x8b, 0x59, 0x94, 0xf3, 0x50, 0xbd, 0x68, 0xc3,
	0x93, 0x38, 0x27, 0x1f, 0xa3, 0x8b, 0x4d, 0xa7, 0x2e, 0x75, 0xfc, 0x10, 0xae, 0xa9, 0x8e, 0xcb,
	0xb4, 0x74, 0xbd, 0xdf, 0x5b, 0xb6, 0xdf, 0xab, 0x52, 0xd7, 0x3f, 0xea, 0x8c, 0x7f, 0x2d, 0x9f,
	0x24, 0xf4, 0x7d, 0xc9, 0xca, 0xc1, 0xe1, 0x25, 0xcb, 0x7a, 0x0a, 0xfa, 0x15, 0x74, 0x64, 0x93,
	0xcb, 0xc5, 0x79, 0xbc, 0x1e, 0x4b, 0xed, 0xb3, 0x05, 0x99, 0xc0, 0x9e, 0x91, 0x8c, 0x49, 0xfb,
	0x8d, 0x4a, 0xba, 0x5f, 0x7d, 0x59, 0x5d, 0x92, 0xfd, 0x04, 0xa0, 0x7c, 0x43, 0x90, 0x03, 0xb4,
	0x5e, 0x7e, 0xef, 0x1c, 0xdc, 0xbc, 0xd2, 0x66, 0x42, 0x7d, 0x00, 0xdb, 0x95, 0xa7, 0xc8, 0x7b,
	0x47, 0xee, 0xca, 0xe7, 0xca, 0x33, 0x3d, 0xe5, 0xd5, 0xcf, 0x03, 0xe4, 0xd6, 0xda, 0x3b, 0xbe,
	0xf6, 0x29, 0xa2, 0x5c, 0x01, 0x57, 0x7f, 0x52, 0xa8, 0x37, 0xa8, 0x9e, 0xfb, 0x97, 0x1a, 0xac,
	0x7d, 0x44, 0xb8, 0xd4, 0xe0, 0xda, 0x27, 0x82, 0xc7, 0xd0, 0x93, 0x4b, 0xb8, 0xd6, 0xe0, 0x87,
	0x5d, 0xd6, 0xc7, 0xf9, 0xa4, 0xad, 0x3e, 0xcd, 0x79, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xfa, 0x70, 0x51, 0xaa, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BgpInfoClient is the client API for BgpInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BgpInfoClient interface {
	AddLatest(ctx context.Context, in *Values, opts ...grpc.CallOption) (*Result, error)
	GetPrefixCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PrefixCountResponse, error)
	UpdateTweetBit(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Result, error)
	GetPieSubnets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PieSubnetsResponse, error)
	GetMovementTotals(ctx context.Context, in *MovementRequest, opts ...grpc.CallOption) (*MovementTotalsResponse, error)
	GetRpki(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Roas, error)
	UpdateAsnames(ctx context.Context, in *AsnamesRequest, opts ...grpc.CallOption) (*Result, error)
	GetAsname(ctx context.Context, in *GetAsnameRequest, opts ...grpc.CallOption) (*GetAsnameResponse, error)
	GetAsnames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAsnamesResponse, error)
	GetSampleIndex(ctx context.Context, in *SampleIndexRequest, opts ...grpc.CallOption) (*SampleIndexResponse, error)
	GetSampleBatch(ctx context.Context, in *SampleBatchRequest, opts ...grpc.CallOption) (*SampleBatchResponse, error)
	AddSampleBatch(ctx context.Context, in *SampleBatchResponse, opts ...grpc.CallOption) (*Result, error)
}

type bgpInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewBgpInfoClient(cc grpc.ClientConnInterface) BgpInfoClient {
	return &bgpInfoClient{cc}
}

func (c *bgpInfoClient) AddLatest(ctx context.Context, in *Values, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/add_latest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetPrefixCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PrefixCountResponse, error) {
	out := new(PrefixCountResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_prefix_count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) UpdateTweetBit(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/update_tweet_bit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetPieSubnets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PieSubnetsResponse, error) {
	out := new(PieSubnetsResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_pie_subnets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetMovementTotals(ctx context.Context, in *MovementRequest, opts ...grpc.CallOption) (*MovementTotalsResponse, error) {
	out := new(MovementTotalsResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_movement_totals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetRpki(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Roas, error) {
	out := new(Roas)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_rpki", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) UpdateAsnames(ctx context.Context, in *AsnamesRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/update_asnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetAsname(ctx context.Context, in *GetAsnameRequest, opts ...grpc.CallOption) (*GetAsnameResponse, error) {
	out := new(GetAsnameResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_asname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetAsnames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAsnamesResponse, error) {
	out := new(GetAsnamesResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_asnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetSampleIndex(ctx context.Context, in *SampleIndexRequest, opts ...grpc.CallOption) (*SampleIndexResponse, error) {
	out := new(SampleIndexResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_sample_index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) GetSampleBatch(ctx context.Context, in *SampleBatchRequest, opts ...grpc.CallOption) (*SampleBatchResponse, error) {
	out := new(SampleBatchResponse)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/get_sample_batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpInfoClient) AddSampleBatch(ctx context.Context, in *SampleBatchResponse, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/bgpsql.bgp_info/add_sample_batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BgpInfoServer is the server API for BgpInfo service.
type BgpInfoServer interface {
	AddLatest(context.Context, *Values) (*Result, error)
	GetPrefixCount(context.Context, *Empty) (*PrefixCountResponse, error)
	UpdateTweetBit(context.Context, *Timestamp) (*Result, error)
	GetPieSubnets(context.Context, *Empty) (*PieSubnetsResponse, error)
	GetMovementTotals(context.Context, *MovementRequest) (*MovementTotalsResponse, error)
	GetRpki(context.Context, *Empty) (*Roas, error)
	UpdateAsnames(context.Context, *AsnamesRequest) (*Result, error)
	GetAsname(context.Context, *GetAsnameRequest) (*GetAsnameResponse, error)
	GetAsnames(context.Context, *Empty) (*GetAsnamesResponse, error)
	GetSampleIndex(context.Context, *SampleIndexRequest) (*SampleIndexResponse, error)
	GetSampleBatch(context.Context, *SampleBatchRequest) (*SampleBatchResponse, error)
	AddSampleBatch(context.Context, *SampleBatchResponse) (*Result, error)
}

// UnimplementedBgpInfoServer can be embedded to have forward compatible implementations.
type UnimplementedBgpInfoServer struct {
}

func (*UnimplementedBgpInfoServer) AddLatest(ctx context.Context, req *Values) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLatest not implemented")
}
func (*UnimplementedBgpInfoServer) GetPrefixCount(ctx context.Context, req *Empty) (*PrefixCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrefixCount not implemented")
}
func (*UnimplementedBgpInfoServer) UpdateTweetBit(ctx context.Context, req *Timestamp) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTweetBit not implemented")
}
func (*UnimplementedBgpInfoServer) GetPieSubnets(ctx context.Context, req *Empty) (*PieSubnetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPieSubnets not implemented")
}
func (*UnimplementedBgpInfoServer) GetMovementTotals(ctx context.Context, req *MovementRequest) (*MovementTotalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovementTotals not implemented")
}
func (*UnimplementedBgpInfoServer) GetRpki(ctx context.Context, req *Empty) (*Roas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRpki not implemented")
}
func (*UnimplementedBgpInfoServer) UpdateAsnames(ctx context.Context, req *AsnamesRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAsnames not implemented")
}
func (*UnimplementedBgpInfoServer) GetAsname(ctx context.Context, req *GetAsnameRequest) (*GetAsnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsname not implemented")
}
func (*UnimplementedBgpInfoServer) GetAsnames(ctx context.Context, req *Empty) (*GetAsnamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsnames not implemented")
}
func (*UnimplementedBgpInfoServer) GetSampleIndex(ctx context.Context, req *SampleIndexRequest) (*SampleIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleIndex not implemented")
}
func (*UnimplementedBgpInfoServer) GetSampleBatch(ctx context.Context, req *SampleBatchRequest) (*SampleBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleBatch not implemented")
}
func (*UnimplementedBgpInfoServer) AddSampleBatch(ctx context.Context, req *SampleBatchResponse) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSampleBatch not implemented")
}

func RegisterBgpInfoServer(s *grpc.Server, srv BgpInfoServer) {
	s.RegisterService(&_BgpInfo_serviceDesc, srv)
}

func _BgpInfo_AddLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Values)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).AddLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/AddLatest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).AddLatest(ctx, req.(*Values))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetPrefixCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetPrefixCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetPrefixCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetPrefixCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_UpdateTweetBit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).UpdateTweetBit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/UpdateTweetBit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).UpdateTweetBit(ctx, req.(*Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetPieSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetPieSubnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetPieSubnets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetPieSubnets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetMovementTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetMovementTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetMovementTotals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetMovementTotals(ctx, req.(*MovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetRpki_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetRpki(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetRpki",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetRpki(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_UpdateAsnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsnamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).UpdateAsnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/UpdateAsnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).UpdateAsnames(ctx, req.(*AsnamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetAsname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAsnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetAsname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetAsname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetAsname(ctx, req.(*GetAsnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetAsnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetAsnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetAsnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetAsnames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetSampleIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetSampleIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetSampleIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetSampleIndex(ctx, req.(*SampleIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_GetSampleBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).GetSampleBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/GetSampleBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).GetSampleBatch(ctx, req.(*SampleBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpInfo_AddSampleBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleBatchResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpInfoServer).AddSampleBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpsql.bgp_info/AddSampleBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpInfoServer).AddSampleBatch(ctx, req.(*SampleBatchResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _BgpInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bgpsql.bgp_info",
	HandlerType: (*BgpInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add_latest",
			Handler:    _BgpInfo_AddLatest_Handler,
		},
		{
			MethodName: "get_prefix_count",
			Handler:    _BgpInfo_GetPrefixCount_Handler,
		},
		{
			MethodName: "update_tweet_bit",
			Handler:    _BgpInfo_UpdateTweetBit_Handler,
		},
		{
			MethodName: "get_pie_subnets",
			Handler:    _BgpInfo_GetPieSubnets_Handler,
		},
		{
			MethodName: "get_movement_totals",
			Handler:    _BgpInfo_GetMovementTotals_Handler,
		},
		{
			MethodName: "get_rpki",
			Handler:    _BgpInfo_GetRpki_Handler,
		},
		{
			MethodName: "update_asnames",
			Handler:    _BgpInfo_UpdateAsnames_Handler,
		},
		{
			MethodName: "get_asname",
			Handler:    _BgpInfo_GetAsname_Handler,
		},
		{
			MethodName: "get_asnames",
			Handler:    _BgpInfo_GetAsnames_Handler,
		},
		{
			MethodName: "get_sample_index",
			Handler:    _BgpInfo_GetSampleIndex_Handler,
		},
		{
			MethodName: "get_sample_batch",
			Handler:    _BgpInfo_GetSampleBatch_Handler,
		},
		{
			MethodName: "add_sample_batch",
			Handler:    _BgpInfo_AddSampleBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bgpsql.proto",
}
