# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bgpsql_pb2 as bgpsql__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bgpsql_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class bgp_infoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_latest = channel.unary_unary(
                '/bgpsql.bgp_info/add_latest',
                request_serializer=bgpsql__pb2.values.SerializeToString,
                response_deserializer=bgpsql__pb2.result.FromString,
                _registered_method=True)
        self.get_prefix_count = channel.unary_unary(
                '/bgpsql.bgp_info/get_prefix_count',
                request_serializer=bgpsql__pb2.empty.SerializeToString,
                response_deserializer=bgpsql__pb2.prefix_count_response.FromString,
                _registered_method=True)
        self.update_tweet_bit = channel.unary_unary(
                '/bgpsql.bgp_info/update_tweet_bit',
                request_serializer=bgpsql__pb2.timestamp.SerializeToString,
                response_deserializer=bgpsql__pb2.result.FromString,
                _registered_method=True)
        self.get_pie_subnets = channel.unary_unary(
                '/bgpsql.bgp_info/get_pie_subnets',
                request_serializer=bgpsql__pb2.empty.SerializeToString,
                response_deserializer=bgpsql__pb2.pie_subnets_response.FromString,
                _registered_method=True)
        self.get_movement_totals = channel.unary_unary(
                '/bgpsql.bgp_info/get_movement_totals',
                request_serializer=bgpsql__pb2.movement_request.SerializeToString,
                response_deserializer=bgpsql__pb2.movement_totals_response.FromString,
                _registered_method=True)
        self.get_rpki = channel.unary_unary(
                '/bgpsql.bgp_info/get_rpki',
                request_serializer=bgpsql__pb2.empty.SerializeToString,
                response_deserializer=bgpsql__pb2.roas.FromString,
                _registered_method=True)
        self.update_asnames = channel.unary_unary(
                '/bgpsql.bgp_info/update_asnames',
                request_serializer=bgpsql__pb2.asnames_request.SerializeToString,
                response_deserializer=bgpsql__pb2.result.FromString,
                _registered_method=True)
        self.get_asname = channel.unary_unary(
                '/bgpsql.bgp_info/get_asname',
                request_serializer=bgpsql__pb2.get_asname_request.SerializeToString,
                response_deserializer=bgpsql__pb2.get_asname_response.FromString,
                _registered_method=True)
        self.get_asnames = channel.unary_unary(
                '/bgpsql.bgp_info/get_asnames',
                request_serializer=bgpsql__pb2.empty.SerializeToString,
                response_deserializer=bgpsql__pb2.get_asnames_response.FromString,
                _registered_method=True)


class bgp_infoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_latest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_prefix_count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_tweet_bit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_pie_subnets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_movement_totals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_rpki(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_asnames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_asname(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_asnames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_bgp_infoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_latest': grpc.unary_unary_rpc_method_handler(
                    servicer.add_latest,
                    request_deserializer=bgpsql__pb2.values.FromString,
                    response_serializer=bgpsql__pb2.result.SerializeToString,
            ),
            'get_prefix_count': grpc.unary_unary_rpc_method_handler(
                    servicer.get_prefix_count,
                    request_deserializer=bgpsql__pb2.empty.FromString,
                    response_serializer=bgpsql__pb2.prefix_count_response.SerializeToString,
            ),
            'update_tweet_bit': grpc.unary_unary_rpc_method_handler(
                    servicer.update_tweet_bit,
                    request_deserializer=bgpsql__pb2.timestamp.FromString,
                    response_serializer=bgpsql__pb2.result.SerializeToString,
            ),
            'get_pie_subnets': grpc.unary_unary_rpc_method_handler(
                    servicer.get_pie_subnets,
                    request_deserializer=bgpsql__pb2.empty.FromString,
                    response_serializer=bgpsql__pb2.pie_subnets_response.SerializeToString,
            ),
            'get_movement_totals': grpc.unary_unary_rpc_method_handler(
                    servicer.get_movement_totals,
                    request_deserializer=bgpsql__pb2.movement_request.FromString,
                    response_serializer=bgpsql__pb2.movement_totals_response.SerializeToString,
            ),
            'get_rpki': grpc.unary_unary_rpc_method_handler(
                    servicer.get_rpki,
                    request_deserializer=bgpsql__pb2.empty.FromString,
                    response_serializer=bgpsql__pb2.roas.SerializeToString,
            ),
            'update_asnames': grpc.unary_unary_rpc_method_handler(
                    servicer.update_asnames,
                    request_deserializer=bgpsql__pb2.asnames_request.FromString,
                    response_serializer=bgpsql__pb2.result.SerializeToString,
            ),
            'get_asname': grpc.unary_unary_rpc_method_handler(
                    servicer.get_asname,
                    request_deserializer=bgpsql__pb2.get_asname_request.FromString,
                    response_serializer=bgpsql__pb2.get_asname_response.SerializeToString,
            ),
            'get_asnames': grpc.unary_unary_rpc_method_handler(
                    servicer.get_asnames,
                    request_deserializer=bgpsql__pb2.empty.FromString,
                    response_serializer=bgpsql__pb2.get_asnames_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bgpsql.bgp_info', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bgpsql.bgp_info', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class bgp_info(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_latest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/add_latest',
            bgpsql__pb2.values.SerializeToString,
            bgpsql__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_prefix_count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_prefix_count',
            bgpsql__pb2.empty.SerializeToString,
            bgpsql__pb2.prefix_count_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_tweet_bit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/update_tweet_bit',
            bgpsql__pb2.timestamp.SerializeToString,
            bgpsql__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_pie_subnets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_pie_subnets',
            bgpsql__pb2.empty.SerializeToString,
            bgpsql__pb2.pie_subnets_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_movement_totals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_movement_totals',
            bgpsql__pb2.movement_request.SerializeToString,
            bgpsql__pb2.movement_totals_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_rpki(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_rpki',
            bgpsql__pb2.empty.SerializeToString,
            bgpsql__pb2.roas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_asnames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/update_asnames',
            bgpsql__pb2.asnames_request.SerializeToString,
            bgpsql__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_asname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_asname',
            bgpsql__pb2.get_asname_request.SerializeToString,
            bgpsql__pb2.get_asname_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_asnames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bgpsql.bgp_info/get_asnames',
            bgpsql__pb2.empty.SerializeToString,
            bgpsql__pb2.get_asnames_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
