# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grapher_pb2 as grapher__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grapher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrapherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLineGraph = channel.unary_unary(
                '/grapher.Grapher/GetLineGraph',
                request_serializer=grapher__pb2.LineGraphRequest.SerializeToString,
                response_deserializer=grapher__pb2.GrapherResponse.FromString,
                _registered_method=True)
        self.GetPieChart = channel.unary_unary(
                '/grapher.Grapher/GetPieChart',
                request_serializer=grapher__pb2.PieChartRequest.SerializeToString,
                response_deserializer=grapher__pb2.GrapherResponse.FromString,
                _registered_method=True)
        self.GetRPKI = channel.unary_unary(
                '/grapher.Grapher/GetRPKI',
                request_serializer=grapher__pb2.RPKIRequest.SerializeToString,
                response_deserializer=grapher__pb2.GrapherResponse.FromString,
                _registered_method=True)
        self.TestRPC = channel.unary_unary(
                '/grapher.Grapher/TestRPC',
                request_serializer=grapher__pb2.TestRequest.SerializeToString,
                response_deserializer=grapher__pb2.TestResponse.FromString,
                _registered_method=True)


class GrapherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLineGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPieChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRPKI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrapherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLineGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLineGraph,
                    request_deserializer=grapher__pb2.LineGraphRequest.FromString,
                    response_serializer=grapher__pb2.GrapherResponse.SerializeToString,
            ),
            'GetPieChart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPieChart,
                    request_deserializer=grapher__pb2.PieChartRequest.FromString,
                    response_serializer=grapher__pb2.GrapherResponse.SerializeToString,
            ),
            'GetRPKI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRPKI,
                    request_deserializer=grapher__pb2.RPKIRequest.FromString,
                    response_serializer=grapher__pb2.GrapherResponse.SerializeToString,
            ),
            'TestRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRPC,
                    request_deserializer=grapher__pb2.TestRequest.FromString,
                    response_serializer=grapher__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grapher.Grapher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grapher.Grapher', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Grapher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLineGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grapher.Grapher/GetLineGraph',
            grapher__pb2.LineGraphRequest.SerializeToString,
            grapher__pb2.GrapherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPieChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grapher.Grapher/GetPieChart',
            grapher__pb2.PieChartRequest.SerializeToString,
            grapher__pb2.GrapherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRPKI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grapher.Grapher/GetRPKI',
            grapher__pb2.RPKIRequest.SerializeToString,
            grapher__pb2.GrapherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grapher.Grapher/TestRPC',
            grapher__pb2.TestRequest.SerializeToString,
            grapher__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
